[[noderegression-pipelines-predict]]
[.alpha]
= Applying a trained model for prediction
:description: This section describes prediction using Node regression pipelines in the Neo4j Graph Data Science library.
:modelType: NodeRegression
:entity: node
:result: predicted property

include::partial$/operations-reference/alpha-note.adoc[]


In the previous sections we have seen how to build up a Node Regression training pipeline and train it to produce a regression model.
After xref:machine-learning/node-property-prediction/noderegression-pipelines/training.adoc[training], the produced, runnable model is of type `{modelType}` and resides in the xref:model-catalog/index.adoc[model catalog].
The regression model can be applied on a graph in the graph catalog to predict a property value for previously unseen nodes.

Since the model has been trained on features which are created using the feature pipeline, the same feature pipeline is stored within the model and executed at prediction time.
As during training, intermediate node properties created by the node property steps in the feature pipeline are transient and not visible after execution.

The predict graph must contain the properties that the pipeline requires and the used array properties must have the same dimensions as in the train graph.
If the predict and train graphs are distinct, it is also beneficial that they have similar origins and semantics, so that the model is able to generalize well.


== Syntax

.Node Regression prediction syntax per mode
[.tabbed-example, caption = ]
====
[.include-with-stream]
======
.Run Node Regression in stream mode:
[source, cypher, role=noplay]
----
CALL gds.alpha.pipeline.nodeRegression.predict.stream(
  graphName: String,
  configuration: Map
) YIELD
  nodeId: Integer,
  predictedValue: Float
----

include::partial$/algorithms/common-configuration/common-parameters.adoc[]

.Configuration
[opts="header",cols="3,2,3m,2,8"]
|===
| Name          | Type   | Default | Optional | Description
include::partial$/algorithms/common-configuration/common-stream-stats-configuration-entries.adoc[]
|===

.Results
[opts="header",cols="1,1,6"]
|===
| Name           | Type    | Description
| nodeId         | Integer | Node ID.
| predictedValue | Float   | Predicted property value for this node.
|===
======

[.include-with-mutate]
======
.Run Node Regression in mutate mode:
[source, cypher, role=noplay]
----
CALL gds.alpha.pipeline.nodeRegression.predict.mutate(
  graphName: String,
  configuration: Map
) YIELD
  preProcessingMillis: Integer,
  computeMillis: Integer,
  postProcessingMillis: Integer,
  mutateMillis: Integer,
  nodePropertiesWritten: Integer,
  configuration: Map
----

include::partial$/algorithms/common-configuration/common-parameters.adoc[]

.Configuration
[opts="header",cols="3,2,3m,2,8"]
|===
| Name          | Type   | Default | Optional | Description
include::partial$/algorithms/common-configuration/common-mutate-configuration-entries.adoc[]
|===

.Results
[opts="header",cols="1,1,6"]
|===
| Name                    | Type    | Description
| preProcessingMillis     | Integer | Milliseconds for preprocessing the graph.
| computeMillis           | Integer | Milliseconds for running the algorithm.
| postProcessingMillis    | Integer | Milliseconds for computing the global metrics.
| mutateMillis            | Integer | Milliseconds for adding properties to the in-memory graph.
| nodePropertiesWritten   | Integer | Number of node properties written.
| configuration           | Map     | Configuration used for running the algorithm.
|===
======

====


== Examples

In the following examples we will show how to use a regression model to predict a property value of a node in your in-memory graph.
In order to do this, we must first have an already trained model registered in the Model Catalog.
We will use the model which we trained in the xref:machine-learning/node-property-prediction/noderegression-pipelines/training.adoc#noderegression-pipelines-examples-train[train example] which we gave the name `'nr-pipeline-model'`.


[[noderegression-pipelines-predict-examples-stream]]
=== Stream

[role=query-example, group=nr]
--
[source, cypher]
----
CALL gds.alpha.pipeline.nodeRegression.predict.stream('myGraph', {
  modelName: 'nr-pipeline-model',
  nodeLabels: ['UnknownHouse']
}) YIELD nodeId, predictedValue
WITH gds.util.asNode(nodeId) AS houseNode, predictedValue AS predictedPrice
RETURN
  houseNode.color AS houseColor, predictedPrice
  ORDER BY predictedPrice
----

.Results
[opts="header",cols="m,m"]
|===
| houseColor | predictedPrice
| "Tan"      | 108.63
| "Pink"     | 113.074
| "Yellow"   | 125.546
|===

As we can see, the model is predicting the "Tan" house to be the cheapest, and the "Yellow" house to be the most expensive.
This may not seem accurate given that the "Yellow" house has only one story.
To get a prediction that better matches our expectations, we may need to tune the model candidate parameters.
--


[[noderegression-pipelines-predict-examples-mutate]]
=== Mutate

The `mutate` execution mode updates the named graph with a new node property containing the predicted value for each node.
The name of the new property is specified using the mandatory configuration parameter `mutateProperty`.
The result is a single summary row including information about timings and how many properties were written.
The `mutate` mode is especially useful when multiple algorithms are used in conjunction.

For more details on the `mutate` mode in general, see xref:common-usage/running-algos.adoc#running-algos-mutate[Mutate].

[role=query-example, group=nr]
--
[source, cypher, role=noplay]
----
CALL gds.alpha.pipeline.nodeRegression.predict.mutate('myGraph', {
  nodeLabels: ['UnknownHouse'],
  modelName: 'nr-pipeline-model',
  mutateProperty: 'predictedPrice'
}) YIELD nodePropertiesWritten
----

.Results
[opts="header"]
|===
| nodePropertiesWritten
| 3
|===
--

The output tells us that we added a property for each of the `UnknownHouse` nodes.
To use this property, we can run another algorithm using the `predictedPrice` property, or inspect it using xref:graph-catalog-node-ops.adoc#catalog-graph-examples-stream[`gds.graph.nodeProperty.stream`].
