[[alpha-algorithms-topological-sort]]
[.alpha]
= Topological Sort
:description: This section describes the Topological Sort algorithm in the Neo4j Graph Data Science library.
:entity: graph
:result: topological sorting of the nodes
:algorithm: Topological Sort


include::partial$/operations-reference/alpha-note.adoc[]


== Introduction

A topological sorting of nodes in a graph is an ordering of the nodes in the graph where every node appears only after all the nodes pointing to it have appeared.
For example, for a graph with 4 nodes and these relations: `a->b`, `a->c`, `b->d`, `c->d`, there are two acceptable topological sorts: `a, b, c, d` and `a, c, b, d`.

Topological order of the nodes is defined only for directed acyclic graphs (DAGs). See xref:#topological-sort-cycles[below] for the expected result for graphs with cycles.

[[topological-sort-cycles]]
=== Cycles

Running the algorithm on a graph with cycles will cause the omitting of part of the nodes from the sorting. The omitted nodes are:

1. Nodes that are part of a cycle (including self cycles)

2. Nodes that are dependent on a cycle. It means nodes that are reachable from another node which is part of a cycle

All the other nodes in the graph will be ordered in a valid topological order.

=== Usage

Topological ordering of the nodes is beneficial when you want to guarantee a node will only be processed after its dependencies were processed. This is very useful for dependency related tasks such as scheduling or calculations that derive values from their dependencies.

The algorithm can also be used to determine if the graph contains a cycle or not. If all the nodes in the graph appear in the sorting, there is no cycle in the graph. If some of the nodes are missing from the sorting, there is a cycle. It does not tell which nodes constitute the cycle, but it does give a clue, as described in the xref:#topological-sort-cycles[cycles] section.


== Syntax

include::partial$/algorithms/shared/syntax-intro-named-graph.adoc[]

.Topological Sort syntax per mode
[.tabbed-example]
====
[.include-with-stream]
======
.Run Topological Sort in stream mode on a named graph.
[source, cypher, role=noplay]
----
CALL gds.alpha.topologicalSort.stream(
  graphName: String,
  configuration: Map
) YIELD
  nodeId: Integer
----

include::partial$/algorithms/common-configuration/common-parameters.adoc[]

.Configuration
[opts="header",cols="3,2,3m,2,8"]
|===
| Name          | Type   | Default | Optional | Description
include::partial$/algorithms/common-configuration/common-configuration-jobid-concurrency-entries.adoc[]
|===

.Results
[opts="header"]
|===
| Name          | Type    | Description
| nodeId        | Integer | The ID of the current node in the ordering
====

[NOTE]
====
The current result implementation contains only the node IDs, streamed in a topological order.
====

== Examples

:algorithm-name: Topological Sort
:graph-description: supply chain
:image-file: dependencies.svg
include::partial$/algorithms/shared/examples-intro.adoc[]

.The following Cypher statement will create the example graph in the Neo4j database:
[source, cypher, role=noplay setup-query]
----
CREATE
       (n0:Part {name: 'Cement'}),
       (n1:Part {name: 'Base'}),
       (n2:Part {name: 'Skeleton'}),
       (n3:Part {name: 'Steel'}),
       (n4:Part {name: 'Support'}),
       (n5:Part {name: 'Door'}),
       (n6:Part {name: 'House'}),

       (n0)-[:REQUIRED]->(n1),
       (n1)-[:REQUIRED]->(n2),
       (n3)-[:REQUIRED]->(n4),
       (n4)-[:REQUIRED]->(n2),
       (n2)-[:REQUIRED]->(n5),
       (n5)-[:REQUIRED]->(n6)
----

This graph describes a simplified supply chain of building a house. Each part of the house cannot be ready before its dependencies are ready. For example, we cannot build support before we get the steel, the skeleton is not ready until  both support and base are ready, and the house in the bottom is only ready when all the other things are done.

=== Stream
The stream procedure streams the nodes in the graph ordered by a valid topological order. The nodes can then be processed one by one, guaranteeing that each node is processed only after its dependencies were processed.

For more details on the stream mode in general, see xref:common-usage/running-algos.adoc#running-algos-stream[Stream].

[role=query-example]
--
.The following will run the Topological Sort algorithm in `stream` mode.
[source, cypher, role=noplay]
----
CALL gds.alpha.topologicalSort.stream("construction") YIELD nodeId RETURN gds.util.asNode(nodeId).name
----
We use the utility function asNode to return the name of node instead of its ID to make results more readable.

.Results
[opts="header"]
|===
| gds.util.asNode(nodeId).name
|"Steel"
|"Cement"
|"Support"
|"Base"
|"Skeleton"
|"Door"
|"House"
|===
--
