[appendix]
[[appendix-b]]
= Migration from Graph Data Science library Version 1.x

[abstract]
--
If you have previously used Graph Data Science library version 1.x, you can find the information you will need to migrate to using version 2.x in this section.
--

== Who should read this guide

This documentation is intended for users who are familiar with the Graph Data Science library.
We assume that most of the mentioned operations and concepts can be understood with little explanation.
Thus we are intentionally brief in the examples and comparisons.
Please see the dedicated chapters in this manual for details on all the features in the Graph Data Science library.

== Syntax Changes

In this section we will focus on side-by-side examples of operations using the syntax of versions 1.x and 2.x, respectively.

This section is divided into the following sub-sections:

* <<migration-algos-common, Common Changes>>
* <<migration-graph-projection, Graph Projection>>
* <<migration-graph-listing, Graph Listing>>
* <<migration-graph-drop, Graph Drop>>
* <<migration-memory-estimation, Memory Estimation>>
* <<migration-algorithms, Algorithms>>

include::migration-algos-common.adoc[leveloffset=+2]

include::migration-graph-projection.adoc[leveloffset=+2]

include::migration-graph-listing.adoc[leveloffset=+2]

include::migration-graph-drop.adoc[leveloffset=+2]

include::migration-memory-estimation.adoc[leveloffset=+2]

include::migration-algorithms.adoc[leveloffset=+2]
