[[graph-catalog-node-ops]]
= Node operations

[abstract]
--
This section details the operations available over node-properties stored in projected graphs within the Neo4j Graph Data Science library.
--

The graphs in the Neo4j Graph Data Science Libarary support properties for nodes.
We provide multiple operations to work with the stored node-properties in projected graphs.
Node properties are either created during the graph creation or when using the `mutate` mode of our graph algorithms.

To inspect stored values, the `gds.graph.streamNodeProperties` can be used.
This is useful if we ran multiple algorithms in `mutate` mode and want to retrieve some or all of the results.

To persist the values in a Neo4j database, we can use `gds.graph.writeNodeProperties`.
Similar to streaming node properties, it is also possible to write those back to Neo4j.
This is similar to what the `stream` execution mode does, but allows more fine-grained control over the operations.

We can also remove node properties from a named graph in the catalog.
This is useful to free up main memory or to remove accidentally created node properties.

== Syntax

.Exporting Node Properties syntax per mode
[.tabbed-example]
====

[.include-with-stream]
======
[source, cypher, role=noplay]
----
CALL gds.graph.streamNodeProperties(
    graphName: String,
    nodeProperties: String or List of Strings,
    nodeLabels: String or List of Strings,
    configuration: Map
)
YIELD
    nodeId: Integer,
    nodeProperty: String,
    propertyValue: Integer or Float or List of Integer or List of Float
----

.Parameters
[opts="header",cols="1,3,1,5"]
|===
| Name           | Type                       | Optional | Description
| graphName      | String                     | no       | The name under which the graph is stored in the catalog.
| nodeProperties | String or List of Strings  | no       | The node properties in the graph to stream.
| nodeLabels     | String or List of Strings  | yes      | The node labels to stream the node properties for graph.
| configuration  | Map                        | yes      | Additional parameters to configure streamNodeProperties.
|===

.Configuration
[opts="header",cols="1,1,1,7"]
|===
| Name                   | Type                  | Default | Description
| concurrency            | Integer               | 4       | The number of concurrent threads. Note, this procedure is always running single-threaded.
|===

.Results
[opts="header",cols="2,3,5"]
|===
| Name            | Type                                                 | Description
|nodeId           | Integer                                              | The id of the node.
|nodeProperty     | String                                               | The name of the node property.
.^|propertyValue    a|
* Integer
* Float
* List of Integer
* List of Float  .^| The stored property value.
|===
======

[.include-with-write]
======
[source, cypher, role=noplay]
----
CALL gds.graph.writeNodeProperties(
    graphName: String,
    nodeProperties: String or List of Strings,
    nodeLabels: String or List of Strings,
    configuration: Map
)
YIELD
    writeMillis: Integer,
    propertiesWritten: Integer,
    graphName: String,
    nodeProperties: String or List of String
----

.Parameters
[opts="header",cols="1,3,1,5"]
|===
| Name           | Type                       | Optional | Description
| graphName      | String                     | no       | The name under which the graph is stored in the catalog.
| nodeProperties | String or List of Strings  | no       | The node properties in the graph to write back.
| nodeLabels     | String or List of Strings  | yes      | The node labels to write back their node properties.
| configuration  | Map                        | yes      | Additional parameters to configure writeNodeProperties.
|===

.Configuration
[opts="header",cols="1,1,1,7"]
|===
| Name                   | Type                  | Default           | Description
| concurrency            | Integer               | 4                 | The number of concurrent threads used for running the procedure. Also provides the default value for `writeConcurrency`
| writeConcurrency       | Integer               | 'concurrency'     | The number of concurrent threads used for writing the node properties.
|===

.Results
[opts="header",cols="2,3,5"]
|===
| Name              | Type                     | Description
| writeMillis       | Integer                  | Milliseconds for writing result data back to Neo4j.
| propertiesWritten | Integer                  | Number of properties written.
| graphName         | String                   | The name of a graph stored in the catalog.
| nodeProperties    | String or List of String | The written node properties.
|===
======

[.include-with-remove]
======
[source, cypher, role=noplay]
----
CALL gds.graph.removeNodeProperties(
    graphName: String,
    nodeProperties: String or List of Strings,
    nodeLabels: String or List of Strings,
    configuration: Map
)
YIELD
    propertiesRemoved: Integer,
    graphName: String,
    nodeProperties: String or List of String
----

.Parameters
[opts="header",cols="1,3,1,5"]
|===
| Name           | Type                       | Optional | Description
| graphName      | String                     | no       | The name under which the graph is stored in the catalog.
| nodeProperties | String or List of Strings  | no       | The node properties in the graph to remove.
| nodeLabels     | String or List of Strings  | yes      | The node labels to remove the node properties from.
| configuration  | Map                        | yes      | Additional parameters to configure removeNodeProperties.
|===

.Configuration
[opts="header",cols="1,1,1,7"]
|===
| Name                   | Type                  | Default           | Description
| concurrency            | Integer               | 4                 | The number of concurrent threads. Note, this procedure is always running single-threaded.
|===

.Results
[opts="header",cols="2,3,5"]
|===
| Name              | Type                     | Description
| propertiesRemoved | Integer                  | Number of properties removed.
| graphName         | String                   | The name of a graph stored in the catalog.
| nodeProperties    | String or List of String | The removed node properties.
|===
======
====

// TODO document gds.graph.streamNodeProperty

== Examples

=== Stream

We can stream node properties stored in a named in-memory graph back to the user.
This is useful if we ran multiple algorithms in `mutate` mode and want to retrieve some or all of the results.
This is similar to what the `stream` execution mode does, but allows more fine-grained control over the operations.

==== Multiple Properties

.Stream multiple node properties:
[source, cypher, role=noplay]
----
CALL gds.graph.streamNodeProperties('my-graph', ['componentId', 'pageRank', 'communityId'])
----

The above example requires all given properties to be present on at least one node projection, and the properties will be streamed for all such projections.

The procedure can be configured to stream just the properties for some specific node projections.
In the following example, we ran an algorithm on a sub-graph and subsequently streamed the newly created property.

.Stream node properties of a specific node projection:
[source, cypher, role=noplay]
----
CALL gds.graph.create('my-graph', ['A', 'B'], '*')
CALL gds.wcc.mutate('my-graph', {nodeLabels: ['A'], mutateProperty: 'componentId'})
CALL gds.graph.streamNodeProperties('my-graph', ['componentId'], ['A'])
----

When a list of projections that are not `*` is specified, as in the example above, a different validation and execution is applied.
It is then required that all projections have all of the given properties, and they will be streamed for all of the projections.

If any of the given projections is `'*'`, the procedure behaves like in the first example.

==== Optimization for a single property

// TODO extend example and make clear labels are supported

When streaming multiple node properties, the name of each property is included in the result.
This adds with some overhead, as each property name must be repeated for each node in the result, but is necessary in order to distinguish properties.
For streaming a single node property this is not necessary.
`gds.graph.streamNodeProperty()` streams a single node property from the in-memory graph, and omits the property name.
The result has the format `nodeId`, `propertyValue`, as is familiar from the streaming mode of many algorithm procedures.

.Stream a single node property:
[source, cypher, role=noplay]
----
CALL gds.graph.streamNodeProperty('my-graph', 'componentId')
----

=== Write

To write the properties `'componentId'`, `'pageRank'`, `'communityId'` for all node projections in the graph `'my-graph'` using 8 concurrent threads, use the following query:

.Write multiple node properties to Neo4j:
[source, cypher, role=noplay]
----
CALL gds.graph.writeNodeProperties(
  'my-graph',
  ['componentId', 'pageRank', 'communityId'],
  ['*'],
  {writeConcurrency: 8}
)
----

The above example requires all given properties to be present on at least one node projection, and the properties will be written for all such projections.

The procedure can be configured to write just the properties for some specific node projections.
In the following example, we run an algorithm on a sub-graph and subsequently write the newly created property to Neo4j.

.Write node properties of a specific node projection to Neo4j:
[source, cypher, role=noplay]
----
CALL gds.graph.create('my-graph', ['A', 'B'], '*')
CALL gds.wcc.mutate('my-graph', {nodeLabels: ['A'], mutateProperty: 'componentId'})
CALL gds.graph.writeNodeProperties('my-graph', ['componentId'], ['A'])
----

When a list of projections not including the star projection (`'*'`) is specified, as in the example above, a different validation and execution is applied.
In this case, it is required that all projections have all of the given properties, and they will be written to Neo4j for all of the projections.

If any of the given projections is the star projection, the procedure behaves like in the first example.


=== Remove

.Remove multiple node properties from a named graph:
[source, cypher, role=noplay]
----
CALL gds.graph.removeNodeProperties('my-graph', ['pageRank', 'communityId'])
----

The above example requires all given properties to be present on at least one node projection, and the properties will be removed from all such projections.

The procedure can be configured to remove just the properties for some specific node projections.
In the following example, we ran an algorithm on a sub-graph and subsequently remove the newly created property.

.Remove node properties of a specific node projection:
[source, cypher, role=noplay]
----
CALL gds.graph.create('my-graph', ['A', 'B'], '*')
CALL gds.wcc.mutate('my-graph', {nodeLabels: ['A'], mutateProperty: 'componentId'})
CALL gds.graph.removeNodeProperties('my-graph', ['componentId'], ['A'])
----

When a list of projections that are not `*` is specified, as in the example above, a different validation and execution is applied;
It is then required that all projections have all of the given properties, and they will be removed from all of the projections.

If any of the given projections is `'*'`, the procedure behaves like in the first example.

