[[catalog-graph-write-node-properties]]
= Write node properties to Neo4j

Similar to streaming properties stored in an in-memory graph it is also possible to write those back to Neo4j.
This is similar to what the `write` execution mode does, but allows more fine-grained control over the operations.

The properties to write are typically the `mutateProperty` values that were used when running algorithms.
Properties that were added to the created graph at creation time will often already be present in the Neo4j database.

.Write multiple node properties to Neo4j:
[source,cypher]
----
CALL gds.graph.writeNodeProperties('my-graph', ['componentId', 'pageRank', 'communityId'])
----

The above example requires all given properties to be present on at least one node projection, and the properties will be written for all such projections.

The procedure can be configured to write just the properties for some specific node projections.
In the following example, we ran an algorithm on a sub-graph and subsequently wrote the newly created property to Neo4j.

.Write node properties of a specific node projection to Neo4j:
[source,cypher]
----
CALL gds.graph.create('my-graph', ['A', 'B'], '*')
CALL gds.wcc.mutate('my-graph', {nodeLabels: ['A'], mutateProperty: 'componentId'})
CALL gds.graph.writeNodeProperties('my-graph', ['componentId'], ['A'])
----

When a list of projections that are not `*` is specified, as in the example above, a different validation and execution is applied;
It is then required that all projections have all of the given properties, and they will be written to Neo4j for all of the projections.

If any of the given projections is `'*'`, the procedure behaves like in the first example.
