[[catalog-graph-write-node-properties]]
= Write node properties to Neo4j

Similar to streaming properties stored in an in-memory graph it is also possible to write those back to Neo4j.
This is similar to what the `write` execution mode does, but allows more fine-grained control over the operations.

The properties to write are typically the `mutateProperty` values that were used when running algorithms.
Properties that were added to the created graph at creation time will often already be present in the Neo4j database.


== Syntax

.Write node properties to Neo4j:
[source, cypher, role=noplay]
----
CALL gds.graph.writeNodeProperties(
  graphName: String,
  nodeProperties: List of String,
  nodeLabels: List of String,
  configuration: Map
) YIELD
  graphName: String,
  nodeProperties: List of String,
  writeMillis: Integer,
  propertiesWritten: Integer
----

.Parameters
[opts="header",cols="1,1,1m,1,4"]
|===
| Name           | Type         | Default | Optional | Description
| graphName      | String       | n/a     | no       | The name of a graph stored in the catalog.
| nodeProperties | List of String | n/a     | no       | Names of properties to write.
| nodeLabels     | List of String | ['*']   | yes      | Names of labels to write properties for.
| configuration  | Map          | {}      | yes      | Configuration for algorithm-specifics and/or graph filtering.
|===

.Configuration parameters
[opts="header",cols="1,1,1m,1,4"]
|===
| Name             | Type    | Default                | Optional | Description
| concurrency      | Integer | 4                      | yes      | The number of concurrent threads used for writing the properties to Neo4j.
| writeConcurrency | Integer | value of 'concurrency' | yes      | The number of concurrent threads used for writing the properties to Neo4j. If both `writeConcurrency` and `concurrency` are specified, `writeConcurrency` will be used.
|===


.Results
[opts="header",cols="1m,1,6"]
|===
| Name              | Type         | Description
| graphName         | String       | Name of the graph.
| nodeProperties    | List of String | Names of written properties.
| writeMillis       | Integer      | Milliseconds for writing properties to Neo4j.
| propertiesWritten | Integer      | Number of properties written.
|===


== Examples

To write the properties `'componentId'`, `'pageRank'`, `'communityId'` for all node projections in the graph `'my-graph'` using 8 concurrent threads, use the following query:

.Write multiple node properties to Neo4j:
[source, cypher, role=noplay]
----
CALL gds.graph.writeNodeProperties(
  'my-graph',
  ['componentId', 'pageRank', 'communityId'],
  ['*'],
  {writeConcurrency: 8}
)
----

The above example requires all given properties to be present on at least one node projection, and the properties will be written for all such projections.

The procedure can be configured to write just the properties for some specific node projections.
In the following example, we run an algorithm on a sub-graph and subsequently write the newly created property to Neo4j.

.Write node properties of a specific node projection to Neo4j:
[source, cypher, role=noplay]
----
CALL gds.graph.create('my-graph', ['A', 'B'], '*')
CALL gds.wcc.mutate('my-graph', {nodeLabels: ['A'], mutateProperty: 'componentId'})
CALL gds.graph.writeNodeProperties('my-graph', ['componentId'], ['A'])
----

When a list of projections not including the star projection (`'*'`) is specified, as in the example above, a different validation and execution is applied.
In this case, it is required that all projections have all of the given properties, and they will be written to Neo4j for all of the projections.

If any of the given projections is the star projection, the procedure behaves like in the first example.
