[[catalog-graph-stream-relationship-properties]]
= Stream relationship properties

We can stream relationship properties stored in a named in-memory graph back to the user.
This is useful if we ran multiple algorithms in `mutate` mode and want to retrieve some or all of the results.
This is similar to what the `stream` execution mode does, but allows more fine-grained control over the operations.

.Stream multiple relationship properties:
[source, cypher]
----
CALL gds.graph.streamRelationshipProperties('my-graph', ['similarityScore', 'weight'])
----

The procedure can be configured to stream just the properties for some specific relationship projections.
In the following example, we ran an algorithm on a sub-graph and subsequently streamed the newly created property.

.Stream relationship properties of a specific relationship projection:
[source,cypher]
----
CALL gds.graph.create('my-graph', ['*'], [A', 'B'])
CALL gds.nodeSimiliarity.mutate('my-graph', {relationshipTypes: ['A'], mutateRelationshipType: 'R', mutateProperty: 'similarityScore'})
CALL gds.graph.streamNodeProperties('my-graph', ['similarityScore'], ['R'])
----

When a list of projections that are not `*` is specified, as in the example above, a different validation and execution is applied.
It is then required that all projections have all of the given properties, and they will be streamed for all of the projections.

If any of the given projections is `'*'`, the procedure behaves like in the first example.

When streaming multiple relationship properties, the name of the relationship type and of each property is included in the result.
This adds with some overhead, as each type name and property name must be repeated for each relationship in the result, but is necessary in order to distinguish properties.
For streaming a single relationship property, the property name can be left out.
`gds.graph.streamNodeProperty()` streams a single relationship property from the in-memory graph, and omits the property name.
The result has the format `sourceNodeId`, `targetNodeId`, `relationshipType`, `propertyValue`.

.Stream a single relationship property:
[source, cypher]
----
CALL gds.graph.streamRelationshipProperty('my-graph', 'similarityScore')
----
