[[catalog-graph-export-database]]
= Create Neo4j databases from named graphs

We can create new Neo4j databases from named in-memory graphs stored in the graph catalog.
All nodes, relationships and properties present in an in-memory graph are written to a new Neo4j database.
This includes data that has been projected in `gds.graph.create` and data that has been added by running algorithms in `mutate` mode.
The newly created database will be stored in the Neo4j `databases` directory using a given database name.

The feature is useful in the following, exemplary scenarios:

* Avoid heavy write load on the operational system by exporting the data instead of writing back.
* Create an analytical view of the operational system that can be used as a basis for running algorithms.
* Produce snapshots of analytical results and persistent them for archiving and inspection.
* Share analytical results within the organization.

.Export a named graph to a new database in the Neo4j databases directory:
[source,cypher]
----
CALL gds.graph.export('my-graph', { dbName: 'mydatabase' })
----

The procedure yields information about the number of nodes, relationships and properties written.

.Graph export configuration
[opts="header",cols="1,1,1m,1,4"]
|===
| Name                    | Type    | Default    | Optional  | Description
| dbName                  | String  | none       | No        | Name of the exported Neo4j database.
| writeConcurrency        | Boolean | 4          | yes       | The number of concurrent threads used for writing the database.
| enableDebugLog          | Boolean | false      | yes       | Prints debug information to Neo4j log files.
| batchSize               | Integer | 10000      | yes       | Number of entities processed by one single thread at a time.
| defaultRelationshipType | String  | "\__ALL__" | yes       | Relationship type used for `*` relationship projections.
|===

The new database can be started using link:https://neo4j.com/docs/cypher-manual/current/administration/databases/#administration-databases-start-database[`databases management commands`].


[NOTE]
====
The database must not exist when using the export procedure, it needs to be created manually using the following commands.
====


.After running the procedure, we can start a new database and query the exported graph:
[source,cypher]
----
:use system
CREATE DATABASE mydatabase;
:use mydatabase
MATCH (n) RETURN n;
----
