[[catalog-graph-write-relationship]]
= Write relationships to Neo4j

We can write relationships stored in a named in-memory graph back to Neo4j.
This can be used to write algorithm results (for example from <<algorithms-node-similarity, Node Similarity>>) or relationships that have been aggregated during graph creation.

The relationships to write are specified by a relationship type.
This can either be an element identifier used in a relationship projection during graph construction or the `writeRelationshipType` used in algorithms that create relationships.
Relationships are always written using a single thread.

.Write relationships to Neo4j:
[source, cypher, role=noplay]
----
CALL gds.graph.writeRelationship('my-graph', 'SIMILAR_TO')
----

By default, no relationship properties will be written.
To write relationship properties, these have to be explicitly specified.

.Write relationships and their properties to Neo4j:
[source, cypher, role=noplay]
----
CALL gds.graph.writeRelationship('my-graph', 'SIMILAR_TO', 'similarityScore')
----
