[[catalog-graph-stream-node-properties]]
= Stream node properties

We can stream node properties stored in a named in-memory graph back to the user.
This is useful if we ran multiple algorithms in `mutate` mode and want to retrieve some or all of the results.
This is similar to what the `stream` execution mode does, but allows more fine-grained control over the operations.

.Stream multiple node properties:
[source, cypher]
----
CALL gds.graph.streamNodeProperties('my-graph', ['componentId', 'pageRank', 'communityId'])
----

The above example requires all given properties to be present on at least one node projection, and the properties will be streamed for all such projections.

The procedure can be configured to stream just the properties for some specific node projections.
In the following example, we ran an algorithm on a sub-graph and subsequently streamed the newly created property.

.Stream node properties of a specific node projection:
[source,cypher]
----
CALL gds.graph.create('my-graph', ['A', 'B'], '*')
CALL gds.wcc.mutate('my-graph', {nodeLabels: ['A'], mutateProperty: 'componentId'})
CALL gds.graph.streamNodeProperties('my-graph', ['componentId'], ['A'])
----

When a list of projections that are not `*` is specified, as in the example above, a different validation and execution is applied.
It is then required that all projections have all of the given properties, and they will be streamed for all of the projections.

If any of the given projections is `'*'`, the procedure behaves like in the first example.

When streaming multiple node properties, the name of each property is included in the result.
This adds with some overhead, as each property name must be repeated for each node in the result, but is necessary in order to distinguish properties.
For streaming a single node property this is not necessary.
`gds.graph.streamNodeProperty()` streams a single node property from the in-memory graph, and omits the property name.
The result has the format `nodeId`, `propertyValue`, as is familiar from the streaming mode of many algorithm procedures.

.Stream a single node property:
[source, cypher]
----
CALL gds.graph.streamNodeProperty('my-graph', 'componentId')
----
