= Neo4j Graph Data Science Library

This repository hosts the sources of the Neo4j Graph Data Science (GDS) library.
The GDS library is a plugin for the Neo4j graph database.
The library consists of a number of graph algorithms, exposed as procedures and executed in Neo4j.

== Downloading and installing releases

The latest releases of the Graph Data Science library can always be found at the https://neo4j.com/download-center/[Neo4j Download Center] or the releases page.
To install the plugin in Neo4j place the downloaded JAR file it in the `plugins` directory of your Neo4j database and restart the database.
For further instructions, see our https://neo4j.com/docs/graph-data-science/current/installation/[documentation].

If you are using Neo4j Desktop you can simply add the Graph Data Science library on the plugins page of your project.

.Compatibility matrix
|===
|GDS version | Neo4j version | Java Version

|GDS 1.0.x, 1.1.x
|Neo4j 3.5.9 - 3.5.20

|GDS 1.1.x
|Neo4j 3.5.20
|Java 1.8

|GDS 1.2.x
|Neo4j 4.0.0 – 4.0.6
|Java 11

.3+<.^|GDS 1.3.x
|Neo4j 4.0.0 - 4.0.7
|Java 11
|Neo4j 4.1.0 - 4.1.1
|Java 11

.3+<.^|GDS 1.4.x (alpha)
|Neo4j 4.0.0 - 4.0.7
|Java 11
|Neo4j 4.1.0 - 4.1.1
|Java 11
|===

NOTE: Preview releases are not automatically made available in Neo4j Desktop. They need to be installed manually.

== Building the library

The Neo4j Graph Data Science library uses the build tool `Gradle`.
Gradle is shipped with this repository using the Gradle Wrapper.
This means you can simply run all Gradle commands by running `./gradlew TASK` from the repository root.

Running tests::
To run all tests you can simply run `./gradlew check`

Packaging the library::
To package the library you can run `./gradlew packaging:shadowJar`.
This will create the bundled JAR at `packaging/build/libs/neo4j-graph-data-science-VERSION-standalone.jar`.

Preview of the Documentation::
To generate a preview you can run `./gradlew doc:preview`.
This will build the documentation and make it available under `http://localhost:8001/`.
When you are done run `./gradlew doc:stopPreview` to stop the web server.

== Contributing

Please report any bugs, concerns, or other questions as GitHub issues to this repository.

For more information see the link:CONTRIBUTING.md[contribution guidelines for this project].

== License

The Neo4j Graph Data Science library is licensed under the GNU Public License version 3.0.
All content is copyright © Neo4j Sweden AB.
