plugins {
    id 'buildlogic-gds-java'
}

description = 'Neo4j Graph Data Science :: Compression Common'
group = 'org.neo4j.gds'

dependencies {
    annotationProcessor project(':annotations')

    compileOnly(neo4j.unsafe) { transitive = false }
    compileOnly openGds.jetbrains.annotations
    compileOnly openGds.immutables.value.annotations

    implementation project(':annotations')
    implementation project(':compression-api')
    implementation project(':core-utils')
    implementation project(':collections')
    implementation project(':core-api')
    implementation project(':histogram')
    implementation project(':memory-access')
    implementation project(':memory-info')
    implementation project(':memory-usage')
    implementation openGds.commons.lang3
    implementation openGds.hdrhistogram
    implementation openGds.hppc

    testImplementation project(':test-utils')
}
