= GDS Sessions

NOTE: GDS Sessions are currently in Early Access and not available by default. Contact your account manager to get the feature enabled.

A GDS Session is an on-demand ephemeral compute environment for running GDS workloads.
It is offered as part of Neo4j Aura, a fast, scalable, always-on, fully automated cloud graph platform.

A GDS Session reads data from one of three categories of data sources:

- Neo4j AuraDB
- self-managed Neo4j DBMS
- a non-Neo4j data source

We call the process of populating the session with data a _remote projection_.
Once populated, a GDS Session can run GDS workloads, such as algorithms and machine learning models.
The results from these computations can be written back to the original source, using _remote write-back_ in the case of a Neo4j data source (Aura or self-managed).


== Primary API surfaces

GDS Sessions do not require any installation to a Neo4j DBMS.
Instead, a GDS Session is started on-demand to perform GDS computations.
There are two primary APIs for working with GDS Sessions.

.GDS Python Client
Using the client, it is possible to perform all operations on a GDS Session.
For a comprehensive API overview including examples and tutorials, see link:https://neo4j.com/docs/graph-data-science-client/current/gds-session/[the GDS Python Client manual].

In particular, the GDS Python Client allows you to:

- link:https://neo4j.com/docs/graph-data-science-client/current/gds-session/#_creating_a_gds_session[Create GDS Sessions]
- link:https://neo4j.com/docs/graph-data-science-client/current/gds-session/#_projecting_graphs_into_a_gds_session[Project graphs into GDS sessions]

- link:https://neo4j.com/docs/graph-data-science-client/current/gds-session/#_running_algorithms[Run algorithms and machine learning operations]
- link:https://neo4j.com/docs/graph-data-science-client/current/gds-session/#_remote_write_back[If sourced from a Neo4j DBMS, write back results]
- link:https://neo4j.com/docs/graph-data-science-client/current/gds-session/#_listing_gds_sessions[List sessions]
- link:https://neo4j.com/docs/graph-data-science-client/current/gds-session/#_deleting_a_gds_session[Delete sessions]

A good place to start are the Tutorials:

- link:https://neo4j.com/docs/graph-data-science-client/current/tutorials/gds-sessions/[GDS Sessions for AuraDB]
- link:https://neo4j.com/docs/graph-data-science-client/current/tutorials/gds-sessions-self-managed/[GDS Sessions for Self-Managed Neo4j DB]

.GDS Session Cypher API
This manual covers all aspects of the GDS Session Cypher API.
The Cypher API supports remote projections, calling algorithms and machine learning operations, and remote write back to the AuraDB instance.
It is currently offered only for AuraDB and is used from within a Cypher query context, such as Query in the Aura Console.
This means that the session is created automatically when a remote graph projection runs, and deleted automatically when the graph is dropped.

In the following sections we will focus only on the GDS Session Cypher API.


=== Session lifecycle operations

* Create GDS Sessions connected to an AuraDB instance in the link:https://neo4j.com/docs/aura/auradb/#_plans[Business Critical or Virtual Dedicated Cloud] plan.
* Create GDS Sessions connected to a self-hosted Neo4j DBMS, version `5.24.0` or newer.
* List running sessions in a specific Aura project.
* Delete specific sessions. By default, a session will be cleaned up after 1 hour of inactivity.


=== GDS workloads

* Perform GDS algorithm computationsfootnote:limitations[See <<Limitations>>], including all execution modes.
* Train machine learning modelsfootnote:limitations[].
* Run machine learning prediction pipelinesfootnote:limitations[].


=== Results processing

* Write back results to a Neo4j DBMS.
* Stream back results, to
** the GDS Python Client.
** an Arrow client for the GDS Arrow Server.


== Projecting a graph into a GDS Session

Once you have a GDS Session, you can project a graph into it.
This operation is called _remote projection_ because the data source is not a co-located database, but rather a remote one.

A remote projection is similar to a xref:management-ops/graph-creation/graph-project-cypher-projection.adoc[Cypher projection] and has a similar syntax.
The projection query runs on the database server, but the GDS graph appears in the GDS Session's Graph Catalog.
A key difference is also the name of the aggregating function, which is `gds.graph.project.remote`.

The standard ways to project a graph with GDS plugin (Native projections, Cypher projections, Legacy Cypher projections) are _not_ supported in GDS Sessions.
The projection must be triggered from the data source, which is a Neo4j DBMS or a client of the GDS Arrow Server (see xref:management-ops/graph-creation/graph-project-apache-arrow.adoc[]).


== Writing back data to a Neo4j DBMS

The GDS Session's in-memory graph is projected from data in a Neo4j DBMS, either an AuraDB instance or a self-managed server.
Write-back operations will persist the data back to the same Neo4j DBMS server.
Once all desired results have been written back to the database, the GDS Session can be deleted with no data loss.


== Limitations

* Native projections are not supported, including
** `gds.graph.project`
** `gds.graph.project.estimate`
* Cypher projections are not supported, including
** `gds.graph.project` (the aggregating function)
* Legacy Cypher projections are not supported, including
** `gds.graph.project.cypher`
** `gds.graph.project.cypher.estimate`
* Model Catalog is supported with limitations:
** Trained models can only be used for prediction using the same Session in which they were trained.
After the Session is deleted, all trained models will be lost.
** Model publishing is not supported, including
*** `gds.model.publish`
** Model persistence is not supported, including
*** `gds.model.store`
*** `gds.model.load`
*** `gds.model.delete`
* Topological Link Prediction algorithms are not supported, including
** `gds.alpha.linkprediction.adamicAdar`
** `gds.alpha.linkprediction.commonNeighbors`
** `gds.alpha.linkprediction.preferentialAttachment`
** `gds.alpha.linkprediction.resourceAllocation`
** `gds.alpha.linkprediction.sameCommunity`
** `gds.alpha.linkprediction.totalNeighbors`
* Graph export is not supported, including
** `gds.graph.export`
** `gds.graph.export.csv`
** `gds.graph.export.csv.estimate`
* Backup & Restore is not supported, including
** `gds.backup`
** `gds.restore`
