= Aura Graph Analytics Serverless

NOTE: Aura Graph Analytics Serverless is currently in Early Access and not available by default. Contact your account manager to get the feature enabled.

Aura Graph Analytics Serverless is an on-demand ephemeral compute environment for running GDS workloads.
It is offered as part of Neo4j Aura, a fast, scalable, always-on, fully automated cloud graph platform.
We call each unit of this compute environment a _GDS Session_.

A GDS Session reads data from one of three categories of data sources:

- Neo4j AuraDB
- self-managed Neo4j DBMS
- a non-Neo4j data source

We call the process of populating the session with data a _remote projection_.
Once populated, a GDS Session can run GDS workloads, such as algorithms and machine learning models.
The results from these computations can be written back to the original source, using _remote write-back_ in the case of a Neo4j data source (Aura or self-managed).


== Primary API surfaces

GDS Sessions do not require any installation to a Neo4j DBMS.
Instead, a GDS Session is started on-demand to perform GDS computations.
There are two primary APIs for working with GDS Sessions.

.GDS Python Client
Using the client, it is possible to perform all operations on a GDS Session.
For a comprehensive API overview including examples and tutorials, see link:https://neo4j.com/docs/graph-data-science-client/current/gds-session/[the GDS Python Client manual].

In particular, the GDS Python Client allows you to:

- link:https://neo4j.com/docs/graph-data-science-client/current/gds-session/#_creating_a_gds_session[Create GDS Sessions]
- link:https://neo4j.com/docs/graph-data-science-client/current/gds-session/#_projecting_graphs_into_a_gds_session[Project graphs into GDS sessions]

- link:https://neo4j.com/docs/graph-data-science-client/current/gds-session/#_running_algorithms[Run algorithms and machine learning operations]
- link:https://neo4j.com/docs/graph-data-science-client/current/gds-session/#_remote_write_back[If sourced from a Neo4j DBMS, write back results]
- link:https://neo4j.com/docs/graph-data-science-client/current/gds-session/#_listing_gds_sessions[List sessions]
- link:https://neo4j.com/docs/graph-data-science-client/current/gds-session/#_deleting_a_gds_session[Delete sessions]

A good place to start are the Tutorials:

- link:https://neo4j.com/docs/graph-data-science-client/current/tutorials/gds-sessions/[GDS Sessions for AuraDB]
- link:https://neo4j.com/docs/graph-data-science-client/current/tutorials/gds-sessions-self-managed/[GDS Sessions for Self-Managed Neo4j DB]

.GDS Session Cypher API
This manual covers all aspects of the GDS Session Cypher API.
The Cypher API supports remote projections, calling algorithms and machine learning operations, and remote write back to the AuraDB instance.
It is currently offered only for AuraDB and is used from within a Cypher query context, such as Query in the Aura Console.
This means that the session is created automatically when a remote graph projection runs, and deleted automatically when the graph is dropped.

In the following sections we will focus only on the GDS Session Cypher API, assuming that it is used from an AuraDB instance.


== Session lifecycle and configuration

In the Cypher API, sessions are managed _implicitly_.
That means that there is no operation to create or delete a session.
Instead, a session is created when a remote projection is run, and deleted when the graph is dropped.
Sessions cannot be listed directly, but _graphs_ can be listed using `gds.graph.list()`.


=== Session size

When the graph projection is requested, a mandatory `memory` parameter must be specified, indicating the size of the session.
The size of the session is the maximum amount of memory allocated to the analytical process.
A larger size means faster runtime and an ability to process larger volumes of data, but it will also be more expensive.

Supported values are: `4GB`, `8GB`, `16GB`, `24GB`, `32GB`, `48GB`, `64GB`, `96GB`, `128GB`, `192GB`, `256GB`, `384GB`, and `512GB`.

[NOTE]
Session maximum size can be configured for your Aura organization.
Check with your organization administrator what your maximum size is.


=== AuraDB source instance limitations

The GDS Session Cypher API is available only for AuraDB instances in the Business Critical or Virtual Dedicated Cloud plans.
Depending on which plan is used, different limitations apply.
See link:https://neo4j.com/docs/aura/graph-analytics/#_comparison[Graph analytics in Aura] for a comparison view.


=== Session expiration and deletion

When the graph projection is requested, an optional `ttl` parameter can be configured, which specifies how quickly an inactive session will expire.
The default value for `ttl` is 1 hour and the maximum allowed value is 7 days.
An expired session cannot be used to run workloads, does not cost anything, and will be deleted automatically after 7 days.
It can also be deleted through the Aura Console UI.


== Syntax

The GDS Session Cypher API matches the GDS plugin API as closely as possible.
Thus, most of the content in this manual applies to both products.
In general, expect to be able to use all query examples in this manual with the GDS Session Cypher API, subject to the limitations described in this section.


=== Authentication to Aura API

One key difference is the requirement for the GDS Session Cypher API to authenticate to the Aura API.
This is done by calling the `gds.aura.api.credentials()` function in each Cypher query.
An easy way to do that is to use a leading `WITH` clause in all queries.

The function does not return any value, but registers the credentials in the query context of that query.
The credentials are not persisted anywhere and will be immediately forgotten after the Cypher query has completed.

Due to this requirement, short-form `CALL`-only queries cannot be used.
This is due to a syntactic sugar rule in Cypher.
See link:https://neo4j.com/docs/cypher-manual/current/clauses/call/#call-procedure-yield[the Cypher manual] for additional details.


==== Examples

.Projecting a graph to a GDS Session:
[source, cypher]
----
// you can use any alias
WITH gds.aura.api.credentials() AS credentials
MATCH (n)
OPTIONAL MATCH (n)-->(m)
RETURN gds.graph.project('g', n, m, {}, {memory: '4GB'})
----

.Calling an algorithm in stream mode:
[source, cypher]
----
// you can use any alias
WITH gds.aura.api.credentials() AS c
CALL gds.pageRank.stream('g')
YIELD nodeId, score // must specify YIELD
RETURN *
----


=== Projecting a graph

Projecting a graph to a GDS Session is done using a xref:management-ops/graph-creation/graph-project-cypher-projection.adoc[Cypher projection].
Note here that the additional parameters labeled `Aura Graph Analytics Serverless` apply.


=== Running algorithms

The GDS Session Cypher API supports most algorithms and machine learning operations.
The syntax is the same as for the GDS plugin, but with the additional `WITH gds.aura.api.credentials() AS credentials` clause.


==== Unsupported algorithms

TODO list these here


== Examples

More thorough example with several algorithms and write-back operations.

// === GDS workloads
//
// * Perform GDS algorithm computationsfootnote:limitations[See <<Limitations>>], including all execution modes.
// * Train machine learning modelsfootnote:limitations[].
// * Run machine learning prediction pipelinesfootnote:limitations[].
//
//
// === Results processing
//
// * Write back results to a Neo4j DBMS.
// * Stream back results, to
// ** the GDS Python Client.
// ** an Arrow client for the GDS Arrow Server.
//
//
// == Projecting a graph into a GDS Session
//
// Once you have a GDS Session, you can project a graph into it.
// This operation is called _remote projection_ because the data source is not a co-located database, but rather a remote one.
//
// A remote projection is similar to a xref:management-ops/graph-creation/graph-project-cypher-projection.adoc[Cypher projection] and has a similar syntax.
// The projection query runs on the database server, but the GDS graph appears in the GDS Session's Graph Catalog.
// A key difference is also the name of the aggregating function, which is `gds.graph.project.remote`.
//
// The standard ways to project a graph with GDS plugin (Native projections, Cypher projections, Legacy Cypher projections) are _not_ supported in GDS Sessions.
// The projection must be triggered from the data source, which is a Neo4j DBMS or a client of the GDS Arrow Server (see xref:management-ops/graph-creation/graph-project-apache-arrow.adoc[]).
//
//
// == Writing back data to a Neo4j DBMS
//
// The GDS Session's in-memory graph is projected from data in a Neo4j DBMS, either an AuraDB instance or a self-managed server.
// Write-back operations will persist the data back to the same Neo4j DBMS server.
// Once all desired results have been written back to the database, the GDS Session can be deleted with no data loss.
//
//
// == Limitations
//
// * Native projections are not supported, including
// ** `gds.graph.project`
// ** `gds.graph.project.estimate`
// * Cypher projections are not supported, including
// ** `gds.graph.project` (the aggregating function)
// * Legacy Cypher projections are not supported, including
// ** `gds.graph.project.cypher`
// ** `gds.graph.project.cypher.estimate`
// * Model Catalog is supported with limitations:
// ** Trained models can only be used for prediction using the same Session in which they were trained.
// After the Session is deleted, all trained models will be lost.
// ** Model publishing is not supported, including
// *** `gds.model.publish`
// ** Model persistence is not supported, including
// *** `gds.model.store`
// *** `gds.model.load`
// *** `gds.model.delete`
// * Topological Link Prediction algorithms are not supported, including
// ** `gds.alpha.linkprediction.adamicAdar`
// ** `gds.alpha.linkprediction.commonNeighbors`
// ** `gds.alpha.linkprediction.preferentialAttachment`
// ** `gds.alpha.linkprediction.resourceAllocation`
// ** `gds.alpha.linkprediction.sameCommunity`
// ** `gds.alpha.linkprediction.totalNeighbors`
// * Graph export is not supported, including
// ** `gds.graph.export`
// ** `gds.graph.export.csv`
// ** `gds.graph.export.csv.estimate`
// * Backup & Restore is not supported, including
// ** `gds.backup`
// ** `gds.restore`
