[.enterprise-edition]
[[installation-apache-arrow]]
= Apache Arrow
:description: This chapter explains how to set up Apache Arrow™ in the Neo4j Graph Data Science library.


include::partial$/management-ops/alpha-note.adoc[]

include::partial$/common-usage/not-on-aurads-note.adoc[]

GDS supports importing graphs and exporting properties via https://arrow.apache.org/[Apache Arrow Flight].
This chapter is dedicated to configuring the Arrow Flight Server as part of the Neo4j and GDS installation.
For using Arrow Flight with an Arrow client, please refer to our documentation for xref::graph-project-apache-arrow.adoc[projecting graphs] and xref::graph-catalog-apache-arrow-ops.adoc[streaming properties].

Arrow is bundled with GDS Enterprise Edition which must be xref::installation/neo4j-server.adoc[installed].


== Installation

On a standalone Neo4j Server, Arrow needs to be explicitly enabled and configured.
The Flight Server is disabled by default, to enable it, add the following to your `$NEO4J_HOME/conf/neo4j.conf` file:

----
gds.arrow.enabled=true
----

The following additional settings are available:

[[table-arrow-settings]]
[opts=header,cols="2m,1m,1,1"]
|===
| Name                          | Default           | Optional  | Description
| gds.arrow.listen_address      | localhost:8491    | Yes       | Address the GDS Arrow Flight Server should bind to.
| gds.arrow.abortion_timeout    | 10                | Yes       | The maximum time in minutes to wait for the next command before aborting the import process.
| gds.arrow.batch_size          | 10000             | Yes       | The batch size used for arrow property export.
|===

Note, that any change to the configuration requires a database restart.


== Authentication

Client connections to the Arrow Flight server are authenticated using the https://neo4j.com/docs/operations-manual/current/authentication-authorization/introduction/[Neo4j native auth provider].
Any authenticated user can perform all available Arrow operations, i.e., graph projection and property streaming.
There are no dedicated roles to configure.

To enable authentication, use the following DBMS setting:

----
dbms.security.auth_enabled=true
----


== Encryption

Communication between client and server can optionally be encrypted.
The Arrow Flight server is re-using the https://neo4j.com/docs/operations-manual/current/security/ssl-framework/[Neo4j native SSL framework].
In terms of https://neo4j.com/docs/operations-manual/current/security/ssl-framework/#ssl-configuration[configuration scope], the Arrow Server supports `https` and `bolt`.
If both scopes are configured, the Arrow Server prioritizes the `https` scope.

To enable encryption for `https`, use the following DBMS settings:

----
dbms.ssl.policy.https.enabled=true
dbms.ssl.policy.https.private_key=private.key
dbms.ssl.policy.https.public_certificate=public.crt
----


Flight server encryption can also be deactivated, even if it is configured for Neo4j.
To disable encryption, use the following settings:

----
gds.arrow.encryption.never=true
----

The setting can only used to deactivate encryption for the GDS Flight server.
It cannot be used to deactivate encryption for the Neo4j server.
It cannot be used to activate encryption for the GDS Flight server if the Neo4j server has no encryption configured.

== Monitoring

To return details about the status of the GDS Flight server, GDS provides the `gds.debug.arrow` procedure.

======
.Run the debug procedure.
[source, cypher, role=noplay]
----
CALL gds.debug.arrow()
YIELD
  running: Boolean,
  enabled: Boolean,
  listenAddress: String,
  serverLocation: String,
  batchSize: Integer,
  abortionTimeout: Integer
----

.Results
[opts="header",cols="1,1,6"]
|===
| Name              | Type      | Description
| running           | Boolean   | True, if the Arrow Flight Server is currently running.
| enabled           | Boolean   | True, if the corresponding setting is enabled.
| listenAddress     | String    | Address (host and port) the Arrow Flight Server is bound to.
| serverLocation    | String    | URI where the Flight stream is available. `NULL` is Arrow is not enabled.
| batchSize         | Integer   | The batch size used for arrow property export.
| abortionTimeout   | Duration  | The maximum time to wait for the next command before aborting the import process.
|===
======
