[[neo4j-server]]
= Neo4j Server

On a standalone Neo4j Server, GDS will need to be installed and configured manually.

1. Download `neo4j-graph-data-science-[version].zip` from the https://neo4j.com/download-center/#ngds[Neo4j Download Center]

2. Unzip the archive and move the `neo4j-graph-data-science-[version].jar` file into the `$NEO4J_HOME/plugins` directory.

3. Add the following to your `$NEO4J_HOME/conf/neo4j.conf` file:
+
----
dbms.security.procedures.unrestricted=gds.*
----
This configuration entry is necessary because the GDS library accesses low-level components of Neo4j to maximise performance.
+

4. Check if the procedure allowlist is enabled in the `$NEO4J_HOME/conf/neo4j.conf` file and add the GDS library if necessary:
+
----
dbms.security.procedures.allowlist=gds.*
----
+

5. Restart Neo4j


[[neo4j-server-verify]]
== Verifying installation

To verify your installation, print the version of Graph Data Science by opening Neo4j Browser and running the `gds.version()` function:

[source, cypher, role=noplay]
----
RETURN gds.version();
----

To list all available procedures, run the `gds.list()` procedure:

[source, cypher, role=noplay]
----
CALL gds.list();
----
