[[neo4j-server]]
= Neo4j Server

On a self-managed Neo4j Server you need to install and configure GDS manually.
For both the Neo4j Enterprise Edition and Neo4j Community Edition, you will find the GDS plugin bundled within the Neo4j Server distribution.
The GDS plugin is always compatible with the version of the Neo4j Server distribution with which it is bundled.

The GDS plugin is located in the `products` directory.
To install the GDS plugin in a Neo4j Enterprise Edition or Neo4j Community Edition installation, follow these steps:

[NOTE]
All file paths in the following instructions are relative to the Neo4j installation directory.

. Copy or move the file `neo4j-graph-data-science-[version].jar` from the `products` directory to the `plugins` directory.

. Add the following wildcard match for all GDS procedures to your `conf/neo4j.conf` file:
+
----
dbms.security.procedures.unrestricted=gds.*
----
This configuration entry is necessary because the GDS library accesses low-level components of Neo4j to maximise performance.
+
. Check if the procedure allowlist is enabled in the `conf/neo4j.conf` file, namely if the `dbms.security.procedures.allowlist` option is _not_ commented out with a leading `#` sign.
In this case, add a wildcard match for all GDS procedures to the allowlist:
+
----
dbms.security.procedures.allowlist=gds.*
----
You can find more information on allow listing in the link:https://neo4j.com/docs/operations-manual/current/security/securing-extensions/#allow-listing[Operations Manual].
+

. Start (or restart) the Neo4j Server.