plugins {
    id 'buildlogic-gds-java-plain'
}

description = 'Neo4j Graph Data Science :: Node Embedding Algorithms Procedure Facade API'

group = 'org.neo4j.gds'

dependencies {
    api project(':algorithms-facade-common')

    // this is needed because of `AlgorithmProcessingTimings`
    api project(':algorithms-machinery')

    // this is needed because of `MemoryEstimation`,
    // this module also exposes `org.neo4j.gds.applications.algorithms.machinery.MemoryEstimateResult` => `api`
    api project(':memory-usage')
    api project(':node-embeddings-configs')

    // Because Node2VecBaseConfig needs RandomWalkBaseConfig
    compileOnly project(':path-finding-configs')

    // `BaseConfig` lives here and forbiddenApis fails if it can't find it 🙈
    compileOnly project(':config-api')

    // `ModelConfig` lives here and forbiddenApis fails if it can't find it 🙈
    compileOnly project(':model-catalog-api')

}
