[[graph-generation]]
[.beta]
= Random generation
:description: This section describes how random graphs can be generated in the Neo4j Graph Data Science library.
:page-aliases: management-ops/projections/graph-generation.adoc


In certain use cases it is useful to generate random graphs, for example, for testing or benchmarking purposes.
For that reason the Neo4j Graph Algorithm library comes with a set of built-in graph generators.
The generator stores the resulting graph in the xref:management-ops/graph-catalog-ops.adoc[graph catalog].
That graph can be used as input for any algorithm in the library.

include::partial$/operations-reference/beta-note.adoc[]

[NOTE]
====
It is currently not possible to persist these graphs in Neo4j.
Running an algorithm in write mode on a generated graph will lead to unexpected results.
====

The graph generation is parameterized by three dimensions:

 * node count - the number of nodes in the generated graph
 * average degree - describes the average out-degree of the generated nodes
 * relationship distribution function - the probability distribution method used to connect generated nodes


[[graph-generation-syntax]]
== Syntax
[.include-with-graph-generate]
====
.The following describes the API for running the graph generation procedure
[source, cypher, role=noplay]
----
CALL gds.beta.graph.generate(
    graphName: String,
    nodeCount: Integer,
    averageDegree: Integer,
    configuration: Map
})
YIELD name, nodes, relationships, generateMillis, relationshipSeed, averageDegree, relationshipDistribution, relationshipProperty
----

.Parameters
[opts="header",cols="2m,1,1m,1,5"]
|===
| Name                | Type    | Default | Optional | Description
| graphName           | String  | null    | no       | The name under which the generated graph is stored.
| nodeCount           | Integer | null    | no       | The number of generated nodes.
| averageDegree       | Integer | null    | no       | The average out-degree of generated nodes.
| configuration       | Map     | {}      | yes      | Additional configuration, see below.
|===

.Configuration
[opts="header",cols="3m,1,1m,1,4"]
|===
| Name                      | Type      | Default  | Optional | Description
| relationshipDistribution  | String    | UNIFORM  | yes      | The probability distribution method used to connect generated nodes. For more information see <<graph-generation-distribution, Relationship Distribution>>.
| relationshipSeed          | Integer   | null     | yes      | The seed used for generating relationships.
| relationshipProperty      | Map       | {}       | yes      | Describes the method used to generate a relationship property. By default no relationship property is generated. For more information see <<graph-generation-relationship-property, Relationship Property>>.
| aggregation               | String    | NONE     | yes      | The relationship aggregation method cf. xref:management-ops/graph-creation/graph-project.adoc#relationship-projection-syntax[Relationship Projection].
| orientation               | String    | NATURAL  | yes      | The method of orienting edges. Allowed values are NATURAL, REVERSE and UNDIRECTED.
| allowSelfLoops            | Boolean   | false    | yes      | Whether to allow relationships with identical source and target node.
|===

.Results
[opts="header",cols="3m,1,6"]
|===
| Name                      | Type       | Description
| name                      | String     | The name under which the stored graph was stored.
| nodes                     | Integer    | The number of nodes in the graph.
| relationships             | Integer    | The number of relationships in the graph.
| generateMillis            | Integer    | Milliseconds for generating the graph.
| relationshipSeed          | Integer    | The seed used for generating relationships.
| averageDegree             | Float      | The average out degree of the generated nodes.
| relationshipDistribution  | String     | The probability distribution method used to connect generated nodes.
| relationshipProperty      | String     | The configuration of the generated relationship property.
|===
====

[[graph-generation-distribution]]
== Relationship Distribution

The `relationshipDistribution` parameter controls the statistical method used for the generation of new relationships.
Currently there are three supported methods:

* `UNIFORM` - Distributes the outgoing relationships evenly, i.e., every node has exactly the same out degree (equal to the average degree). The target nodes are selected randomly.
* `RANDOM` - Distributes the outgoing relationships using a normal distribution with an average of `averageDegree` and a standard deviation of `2 * averageDegree`. The target nodes are selected randomly.
* `POWER_LAW` - Distributes the incoming relationships using a power law distribution. The out degree is based on a normal distribution.


[[graph-generation-relationship-property]]
== Relationship Property

The graph generator is capable of generating a relationship property.
This can be controlled using the `relationshipProperty` parameter which accepts the following parameters:

.Configuration
[opts="header",cols="1m,1,1,1,4"]
|===
| Name    | Type      | Default | Optional  | Description
| name    | String    | null    | no        | The name under which the property values are stored.
| type    | String    | null    | no        | The method used to generate property values.
| min     | Float     | 0.0     | yes       | Minimal value of the generated property (only supported by `RANDOM`).
| max     | Float     | 1.0     | yes       | Maximum value of the generated property (only supported by `RANDOM`).
| value   | Float     | null    | yes       | Fixed value assigned to every relationship (only supported by `FIXED`).
|===

Currently, there are two supported methods to generate relationship properties:

* `FIXED` - Assigns a fixed value to every relationship. The `value` parameter must be set.
* `RANDOM` - Assigns a random value between the lower (`min`) and upper (`max`) bound.

[[graph-generation-seed]]
== Relationship Seed

The `relationshipSeed` parameter allows the user to specify the seed used to generate the random graph manually.
When specified, the procedure will produce the same relationships between nodes regardless of whether the generated graph is going to be created as weighted or unweighted.
This can be helpful if one wants to examine the behavior or performance of an algorithm under weight conditions.

[[graph-generation-example]]
== Examples

In the following we will demonstrate the usage of the random graph generation procedure.

[[graph-generation-unweighted]]
=== Generating unweighted graphs

[role=query-example,group=unweighted]
--
.The following will produce a graph with unweighted relationships
[source,cypher,role=noplay]
----
CALL gds.beta.graph.generate('graph',5,2, {relationshipSeed:19})
YIELD name, nodes, relationships, relationshipDistribution
----

.Results
[opts="header"]
|===
| name | nodes |  relationships | relationshipDistribution
|  "graph"| 5     |     10 | "UNIFORM"
|===
--

A new in-memory graph called `graph`  with `5` nodes and `10` relationships has been created and added to the graph catalog.
We can examine its topology  with the `gds.beta.graph.relationships` procedure.

[role=query-example,group=unweighted]
--
.The following will show the produced relationships
[source,cypher,role=noplay]
----
CALL gds.beta.graph.relationships.stream('graph')
YIELD sourceNodeId,targetNodeId
RETURN  sourceNodeId as source, targetNodeId as target
ORDER BY source ASC,target ASC
----

.Results
[opts="header"]
|===
| source  |target
| 0 | 1
| 0 | 2
| 1 | 0
| 1 | 4
| 2 | 1
| 2 | 4
| 3 | 0
| 3 | 1
| 4 | 0
| 4 | 3
|===
--

[[graph-generation-weighted]]
=== Generating weighted graphs

To generated graphs with weighted relationships we must specify the `relationshipProperty` parameter as discussed xref:graph-generation-relationship-property[above].

[role=query-example,group=weighted]
--
.The following will produce a graph with weighted relationships
[source,cypher,role=noplay]
----
CALL gds.beta.graph.generate('weightedGraph',5,2, {relationshipSeed:19,
  relationshipProperty: {type: 'RANDOM', min: 5.0, max: 10.0, name: 'score'}})
YIELD name, nodes, relationships, relationshipDistribution
----

.Results
[opts="header"]
|===
|name|  nodes |  relationships | relationshipDistribution
|  "weightedGraph"| 5     |     10 | "UNIFORM"
|===
--

The produced graph, `weightedGraph`, has a property named `score`  containing a random value between 5.0 and 10.0 for each relationship.
We can use `gds.graph.relationshipProperty.stream` to stream the  relationships of the graph along with their score values.

[role=query-example,group=weighted]
--
.The following will show the produced relationships
[source,cypher,role=noplay]
----
CALL gds.graph.relationshipProperty.stream('weightedGraph','score')
YIELD sourceNodeId, targetNodeId, propertyValue
RETURN  sourceNodeId as source, targetNodeId as target, propertyValue as score
ORDER BY source ASC,target ASC, score
----

.Results
[opts="header"]
|===
| source  |target | score
| 0 | 1 | 6.791408433596591
| 0 | 2 | 8.662453313014902
| 1 | 0 | 6.258381821615686
| 1 | 4 | 9.711806397654765
| 2 | 1 | 9.469695236791349
| 2 | 4 | 6.519823445755963
| 3 | 0 | 8.747179900968224
| 3 | 1 | 7.752117836610726
| 4 | 0 | 8.614858979680758
| 4 | 3 | 5.060444167785128
|===
--

Notice that despite as `graph` and `weightedGraph` have been created with the same `seed` their relationship topology is equivalent.
