[[algorithms-embeddings-fastrp-extended]]
== Extended Algorithm: Using Node Properties

include::../beta-aspect-note.adoc[]

Most real-world graphs contain node properties which store information about the nodes and what they represent.
An embedding algorithm which can process the node properties as features and incorporate them in the embeddings can therefore be advantageous.

The extended FastRP algorithm (FastRPExtended) has the additional configuration parameters `featureProperties` and `propertyDimension`.
Each node property specified in the former is associated with a randomly generated vector of dimension `propertyDimension`.
Each node is then initialized with a vector of size `embeddingDimension` formed by concatenation of two parts:
The first part is formed like in the original algorithm, and the second one is a linear combination of the property vectors, using the property values of the node as weights.
The algorithm then proceeds with the same logic as the original one.
Therefore, the algorithm will output arrays of size `embeddingDimension` just like the original algorithm.
The last `propertyDimension` co-ordinates in the embedding captures information about property values of nearby nodes, and the remaining co-ordinates (`embeddingDimension` - `propertyDimension` of them) captures information about nearby presence of nodes.

As other configuration parameters, `propertyDimension` needs to be tuned for optimal performance.
We suggest keeping the previously selected value for `embeddingDimension` and setting `propertyDimension` to half that value as a starting point for using FastRPExtended.
Other factors that may influence the choice of `propertyDimension` are vaguely the amount of valuable information contained in the node properties, i.e. number of properties and how independent they are, as well as how relevant the properties are to the problem at hand.

.FastRPExtended syntax per mode
[.tabbed-example]
====

[.include-with-stream]
======
.Run FastRPExtended in stream mode on a named graph.
[source, cypher, role=noplay]
----
CALL gds.beta.fastRPExtended.stream(
  graphName: String,
  configuration: Map
) YIELD
  nodeId: Integer,
  embedding: List<Float>
----

include::../common-configuration/common-parameters-named-graph.adoc[]

include::../common-configuration/common-stream-stats-configuration-named-graph.adoc[]

include::specific-configuration-ext.adoc[]

.Results
[opts="header",cols="1m,1,6"]
|===
| Name      | Type         | Description
| nodeId    | Integer      | The Neo4j node ID.
| embedding | List<Float>  | The computed node embedding.
|===
======

[.include-with-stats]
======
.Run FastRPExtended in stats mode on a graph stored in the catalog.
[source, cypher, role=noplay]
----
CALL gds.beta.fastRPExtended.stats(
  graphName: String,
  configuration: Map
)
YIELD
  nodeCount: Integer,
  createMillis: Integer,
  computeMillis: Integer,
  configuration: Map
----

include::../common-configuration/common-parameters-named-graph.adoc[]

include::../common-configuration/common-stream-stats-configuration-named-graph.adoc[]

include::specific-configuration-ext.adoc[]

.Results
[opts="header",cols="1,1,6"]
|===
| Name               | Type                 | Description
| nodeCount          | Integer              | The number of nodes processed.
| createMillis       | Integer              | Milliseconds for loading data.
| computeMillis      | Integer              | Milliseconds for running the algorithm.
| configuration      | Map                  | The configuration used for running the algorithm.
|===
======

[.include-with-mutate]
======
.Run FastRPExtended in mutate mode on a graph stored in the catalog.
[source, cypher, role=noplay]
----
CALL gds.beta.fastRPExtended.mutate(
  graphName: String,
  configuration: Map
)
YIELD
  nodeCount: Integer,
  nodePropertiesWritten: Integer,
  createMillis: Integer,
  computeMillis: Integer,
  mutateMillis: Integer,
  configuration: Map
----

include::../common-configuration/common-parameters-named-graph.adoc[]

include::../common-configuration/common-mutate-configuration-named-graph.adoc[]

include::specific-configuration-ext.adoc[]

.Results
[opts="header",cols="1,1,6"]
|===
| Name                   | Type                 | Description
| nodeCount              | Integer              | The number of nodes processed.
| nodePropertiesWritten  | Integer              | The number of node properties written.
| createMillis           | Integer              | Milliseconds for loading data.
| computeMillis          | Integer              | Milliseconds for running the algorithm.
| mutateMillis           | Integer              | Milliseconds for adding properties to the in-memory graph.
| configuration          | Map                  | The configuration used for running the algorithm.
|===
======

[.include-with-write]
======
.Run FastRPExtended in write mode on a graph stored in the catalog.
[source, cypher, role=noplay]
----
CALL gds.beta.fastRPExtended.write(
  graphName: String,
  configuration: Map
)
YIELD
  nodeCount: Integer,
  nodePropertiesWritten: Integer,
  createMillis: Integer,
  computeMillis: Integer,
  writeMillis: Integer,
  configuration: Map
----

include::../common-configuration/common-parameters-named-graph.adoc[]

include::../common-configuration/common-write-configuration-named-graph.adoc[]

include::specific-configuration-ext.adoc[]

.Results
[opts="header",cols="1,1,6"]
|===
| Name                   | Type                 | Description
| nodeCount              | Integer              | The number of nodes processed.
| nodePropertiesWritten  | Integer              | The number of node properties written.
| createMillis           | Integer              | Milliseconds for loading data.
| computeMillis          | Integer              | Milliseconds for running the algorithm.
| writeMillis            | Integer              | Milliseconds for writing result data back to Neo4j.
| configuration          | Map                  | The configuration used for running the algorithm.
|===
======
====

Memory estimation for FastRPExtended works similarly to FastRP, which we can see in the following example for the stream mode:

[role=query-example]
--
.The following will estimate the memory requirements for FastRPExtended:
[source, cypher, role=noplay]
----
CALL gds.beta.fastRPExtended.stream.estimate('persons', {embeddingDimension: 128, propertyDimension: 64, featureProperties: ['p1', 'p2']})
YIELD nodeCount, relationshipCount, bytesMin, bytesMax, requiredMemory
----

.Results
[opts="header", cols="1,1,1,1,1"]
|===
| nodeCount | relationshipCount | bytesMin | bytesMax | requiredMemory
| 7         | 18                | 11928    | 11928    | "11928 Bytes"
|===
--
