[[algorithms-path-finding]]
= Path finding algorithms

[abstract]
--
This chapter provides explanations and examples for each of the path finding algorithms in the Neo4j Graph Algorithms library.
--

Path finding algorithms help find the shortest path or evaluate the availability and quality of routes.
Neo4j GDS includes the following path finding algorithms, grouped by quality tier:

* Alpha
** <<labs-algorithms-minimum-weight-spanning-tree, Minimum Weight Spanning Tree>> (`algo.spanningTree`)
** <<labs-algorithms-shortest-path, Shortest Path>> (`algo.shortestPath`)
** <<labs-algorithms-single-source-shortest-path, Single Source Shortest Path>> (`algo.shortestPath.deltaStepping`)
** <<labs-algorithm-all-pairs-shortest-path, All Pairs Shortest Path>> (`algo.allShortestPaths`)
** <<labs-algorithms-a_star, A*>> (`algo.shortestPath.astar`)
** <<labs-algorithms-yens-k-shortest-path, Yen’s K-shortest paths>> (`algo.kShortestPaths`)
** <<labs-algorithms-random-walk, Random Walk>> (`algo.randomWalk`)

[WARNING]
====
As of the 3.4.7.0 release, all the Shortest Path procedures assume that they are being executed on undirected graphs.
Therefore, the direction of a relationship can be ignored.

If you are running these algorithms on a graph where the direction is important, you can use the `direction` parameter.
For example, `direction:"INCOMING"` or `direction:"OUTGOING"`.
====

include::labs-minimum-weight-spanning-tree.adoc[leveloffset=+1]

include::labs-shortest-path.adoc[leveloffset=+1]

include::labs-single-shortest-path.adoc[leveloffset=+1]

include::labs-all-pairs-shortest-path.adoc[leveloffset=+1]

include::labs-astar.adoc[leveloffset=+1]

include::labs-yens-k-shortest-paths.adoc[leveloffset=+1]

include::labs-random-walk.adoc[leveloffset=+1]
