[[running-algos]]
= Running algorithms

All algorithms are exposed as Neo4j procedures.
They can be called directly from Cypher using Neo4j Browser, `cypher-shell`, or from your client code using a Neo4j Driver in the language of your choice.

For a detailed guide on the syntax to run algorithms, please see the <<algorithms-syntax, Syntax overview>> section.
In short, there are two main execution modes to consider: `write` and `stream`, which we cover in this chapter.

The execution of any algorithm can be canceled by terminating the Cypher transaction that is executing the procedure call.
For more on how transactions are used, see <<transaction-handling, Transaction Handling>>.


== Write

The `write` mode will write the results of the algorithm computation back to the graph.
This is similar to how standard Cypher writing queries operate.
A statistical summary of the computation is returned as a Cypher result row.
This is the only execution mode that will make any modifications to the Neo4j database.

The written data can be node properties (such as Page Rank scores), new relationships (such as Node Similarity similarities), or relationship properties.
The `write` mode can be very useful for use cases where the algorithm results would be inspected multiple times by separate queries since the computational results are handled entirely by the library.

In order for the results from a `write` mode computation to be used in another algorithm, a new graph must be created from the Neo4j database with the updated graph.


== Stream

The `stream` mode will return the results of the algorithm computation as Cypher result rows.
This is similar to how standard Cypher reading queries operate.

The returned data can be a node ID and a computed value for the node (such as a PageRank score, or WCC componentID), or two node IDs and a computed value for the node pair (such as a Node Similarity similarity score).

If the graph is very large, the result of a `stream` mode computation will also be very large.
Using the `ORDER BY` and `LIMIT` subclauses in the Cypher query could be useful to support 'top N'-style use cases.
