[[common-usage]]
= Common usage

[abstract]
--
This chapter explains the common usage patterns and operations that constitute the core of the Neo4j Graph Data Science library.
--

The GDS library usage pattern is typically split in two phases: development and production.
In the development phase, it is typical to make use of the memory estimation features of the library.
This enables you to successfully configure your system to handle the amount of data to be processed.
There are two kinds of resources to keep in mind: the in-memory graph and the algorithm data structures.

In the production phase, the system would be configured appropriately to successfully run the desired algorithms.
The sequence of operations would normally be to create a graph, run one or more algorithms on it, and consume results.

In this chapter, we will go through these aspects and guide you towards the most useful operations.

This chapter is divided into the following sections:

* <<memory-estimation>>
* <<creating-graphs>>
* <<running-algos>>


include::memory-estimation.adoc[leveloffset=+1]


[[creating-graphs]]
== Creating graphs

== Running algorithms

All algorithms are exposed as Neo4j procedures.
They can be called directly from Cypher using Neo4j Browser, `cypher-shell`, or from your client code using a Neo4j Driver in the language of your choice.

For a detailed guide on the syntax to run algorithms, please see the <<algorithms-syntax, Syntax overview>> section.
In short, there are two main execution modes to consider: `write` and `stream`, which we cover in this chapter.

The execution of any algorithm can be canceled by terminating the Cypher transaction that is executing the procedure call.
For more on how transactions are used, see <<transaction-handling, Transaction Handling>>.


=== Write

The `write` mode will write the results of the algorithm computation back to the graph.
This is similar to how standard Cypher writing queries operate.
A statistical summary of the computation is returned as a Cypher result row.
This is the only execution mode that will make any modifications to the Neo4j database.

The written data can be node properties (such as Page Rank scores), new relationships (such as Node Similarity similarities), or relationship properties.
The `write` mode can be very useful for use cases where the algorithm results would be inspected multiple times by separate queries since the computational results are handled entirely by the library.

In order for the results from a `write` mode computation to be used in another algorithm, a new graph must be created from the Neo4j database with the updated graph.


=== Stream

The `stream` mode will return the results of the algorithm computation as Cypher result rows.
This is similar to how standard Cypher reading queries operate.

The returned data can be a node ID and a computed value for the node (such as a PageRank score, or WCC componentID), or two node IDs and a computed value for the node pair (such as a Node Similarity similarity score).

If the graph is very large, the result of a `stream` mode computation will also be very large.
Using the `ORDER BY` and `LIMIT` subclauses in the Cypher query could be useful to support 'top N'-style use cases.
