[[experimental-algorithms-path-finding]]
= Path finding algorithms

[abstract]
--
This chapter provides explanations and examples for each of the path finding algorithms in the Neo4j Graph Algorithms library.
--

The following path finding algorithms help find the shortest path or evaluate the availability and quality of routes:

* <<experimental-algorithms-minimum-weight-spanning-tree, Minimum Weight Spanning Tree>> (`algo.spanningTree`)
* <<experimental-algorithms-shortest-path, Shortest Path>> (`algo.shortestPath`)
* <<experimental-algorithms-single-source-shortest-path, Single Source Shortest Path>> (`algo.shortestPath`)
* <<experimental-algorithm-all-pairs-shortest-path, All Pairs Shortest Path>> (`algo.allShortestPaths`)
* <<experimental-algorithms-a_star, A*>> (`algo.shortestPath.astar`)
* <<experimental-algorithms-yens-k-shortest-path, Yen’s K-shortest paths>> (`algo.kShortestPaths`)
* <<experimental-algorithms-random-walk, Random Walk>> (`algo.randomWalk`)

[WARNING]
====
As of the 3.4.7.0 release, all the Shortest Path procedures assume that they are being executed on undirected graphs.
Therefore, the direction of a relationship can be ignored.

If you are running these algorithms on a graph where the direction is important, you can use the `direction` parameter.
For example, `direction:"INCOMING"` or `direction:"OUTGOING"`.
====

include::experimental-minimum-weight-spanning-tree.adoc[leveloffset=+1]

include::experimental-shortest-path.adoc[leveloffset=+1]

include::experimental-single-shortest-path.adoc[leveloffset=+1]

include::experimental-all-pairs-shortest-path.adoc[leveloffset=+1]

include::experimental-astar.adoc[leveloffset=+1]

include::experimental-yens-k-shortest-paths.adoc[leveloffset=+1]

include::experimental-random-walk.adoc[leveloffset=+1]
