[[introduction]]
= Introduction

[abstract]
--
This chapter provides a brief introduction of the main concepts in the Neo4j Graph Data Science library.
--

This library provides efficiently implemented, parallel versions of common graph algorithms for Neo4j, exposed as Cypher procedures.


[[introduction-graph-variants]]
== Graph variants

The Graph Data Science library supports the following options when it comes to type of graphs:

Directed::
Relationships have specific direction. Relationships pointing to a node are referred to as _in-links_, respectively relationships originating from a node are called _out-links_.

Undirected::
Relationships are considered bidirectional (for example friendships).

Monopartite::
Graphs with one node type and relationship type are referred to as _monopartite_.

Multi-partite::
Graphs with multiple node types are referred to as _multi-partite_.
Common case are _bi-partite_ graphs where we have two node types.

Weighted::
Weighted graphs have weight value(s) assigned to their relationships or nodes, these values can represent _cost_, _time_, _capacity_ or other _domain-specific property_.

Unweighted::
Unweighted graphs have no weight values assigned to their nodes or relationships.


[[introduction-algorithms]]
== Algorithms

Graph algorithms are used to compute metrics for graphs, nodes, or relationships.

They can provide insights on relevant entities in the graph (centralities, ranking), or inherent structures like communities (community-detection, graph-partitioning, clustering).

Many graph algorithms are iterative approaches that frequently traverse the graph for the computation using random walks, breadth-first or depth-first searches, or pattern matching.

Due to the exponential growth of possible paths with increasing distance, many of the approaches also have high algorithmic complexity.

Fortunately, optimized algorithms exist that utilize certain structures of the graph, memoize already explored parts, and parallelize operations.
Whenever possible, we've applied these optimizations.

The Neo4j Graph Data Science library contains a large number of algorithms, which are detailed in the <<algorithms, Algorithms>> chapter.


[[introduction-catalog]]
== Graph Catalog

In order to run the algorithms as efficiently as possible, the Neo4j Graph Data Science library uses a specialized in-memory graph format to represent the graph data.
It is therefore necessary to load the graph data from the Neo4j database into an in memory graph catalog.
The amount of data loaded can be controlled by so called graph projections, which also allow, for example, filtering on node labels and relationship types, among other options.

For more information see <<management-ops, Graph Management>>.


[[introduction-editions]]
== Editions

The Neo4j Graph Data Science library is available in two editions.

* The open source Community Edition includes all algorithms and features, but is limited to four CPU cores.
* The Neo4j Graph Data Science library Enterprise Edition:
** Can run on an unlimited amount of CPU cores.
** Supports the role-based access control system (RBAC) from Neo4j Enterprise Edition.
** Supports various additional model catalog features
*** Storing unlimited amounts of models in the model catalog
*** <<catalog-model-publish, Publishing a stored model>>
*** <<model-catalog-store-ops, Persisting a stored model to disk>>
** Supports an <<bit-id-map-feature-toggle, optimized in-memory graph implementation>>

For more information see <<system-requirements-cpu, System Requirements - CPU>>.
