[[migration-page-rank]]
= PageRank

.Changes in Configuration
[opts=header,cols="1a,1a"]
|===
|GA                                 | GDS
| direction                         | -
| iterations                        | maxIterations
| tolerance                         | tolerance
| dampingFactor                     | dampingFactor
| concurrency                       | concurrency
| readConcurrency                   | readConcurrency footnote:page-rank-read[Only when using anonymous graph]
| writeConcurrency                  | writeConcurrency footnote:page-rank-write[Only for `write` mode]
| writeProperty                     | writeProperty footnote:page-rank-write[]
| weightProperty                    | relationshipWeightProperty
| write                             | -
| graph                             | -
|===

.Changes in YIELD fields
[opts=header,cols="1a,1a"]
|===
| GA                     | GDS
| loadMillis             | createMillis
| computeMillis          | computeMillis
| writeMillis            | writeMillis
| postProcessingMillis   | postProcessingMillis
| node                   | nodeId footnote:page-rank-stream-yield[Only for `stream` mode]
| score                  | score footnote:page-rank-stream-yield[]
| nodes                  | nodePropertiesWritten footnote:page-rank-write-yield[Only for `write` mode]
| iterations             | ranIterations
| write                  | -
| -                      | configuration footnote:page-rank-gds-config[The configuration used to run the algorithm]
| writeProperty footnote:page-rank-config[Inlined into `configuration`]         | -
| dampingFactor footnote:page-rank-config[]         | -
| tolerance footnote:page-rank-config[]         | -
| weightProperty footnote:page-rank-weight-config[Inlined into `configuration` as `relationshipWeightProperty`]         | -
|===

.PageRank Stream Mode
[opts=header,cols="1a,1a"]
|===
|GA | GDS
2+|Minimalistic stream over named graph
|
[source, cypher]
----
CALL algo.pageRank.stream(null, null, {graph: 'myGraph'})
YIELD nodeId, score
----
|
[source, cypher]
----
CALL gds.pageRank.stream('myGraph')
YIELD nodeId, score
----
2+| Streaming over named graph with iteration limit
|
[source, cypher]
----
CALL algo.pageRank.stream(
  null,
  null,
  {
    graph: 'myGraph',
    iterations: 20
  }
)
----
|
[source, cypher]
----
CALL gds.pageRank.stream(
  'myGraph',
  {
    maxIterations: 20
  }
)
----
2+| Minimalistic streaming over anonymous graph
|
[source, cypher]
----
CALL algo.pageRank.stream(
  'MyLabel',
  'MY_RELATIONSHIP_TYPE'
)
----
|
[source, cypher]
----
CALL gds.pageRank.stream({
  nodeProjection: 'MyLabel',
  relationshipProjection: 'MY_RELATIONSHIP_TYPE'
})
----
2+| Streaming over anonymous graph with `REVERSE` relationship projection
|
[source, cypher]
----
CALL algo.pageRank.stream(
  'MyLabel',
  'MY_RELATIONSHIP_TYPE',
  { direction: 'INCOMING' }
)
----
|
[source, cypher]
----
CALL gds.pageRank.stream({
  nodeProjection: 'MyLabel',
  relationshipProjection: {
    MY_RELATIONSHIP_TYPE: {
      orientation: 'REVERSE'
    }
  }
})
----
2+| Streaming over anonymous graph with relationship weight property, assigning it a default value in case the property doesn't have value
|
[source, cypher]
----
CALL algo.pageRank.stream(
  'MyLabel',
  'MY_RELATIONSHIP_TYPE',
  {
    weightProperty: 'myWeightProperty',
    defaultValue: 1.5
  }
)
----
|
[source, cypher]
----
CALL gds.pageRank.stream({
  nodeProjection: 'MyLabel',
  relationshipProjection: {
    MY_RELATIONSHIP_TYPE: {
      properties: {
        myWeightProperty: {
          defaultValue: 1.5
        }
      }
    }
  }
})
----
|===

.PageRank Write Mode
[opts=header,cols="1a,1a"]
|===
|GA | GDS
2+| Running `write` mode on named graph
|
[source, cypher]
----
CALL algo.pageRank(
  null,
  null,
  {
    graph: 'myGraph',
    writeProperty: 'myWriteProperty',
    write: true
  }
)
YIELD
  nodes,
  loadMillis,
  iterations,
  p1,
  writeProperty
----
|
[source, cypher]
----
CALL gds.pageRank.write(
  'myGraph',
  {
    writeProperty: 'myWriteProperty'
  }
)
YIELD
  nodePropertiesWritten,
  createMillis,
  ranIterations,
  configuration AS conf
RETURN
  nodePropertiesWritten,
  writeMillis,
  ranIterations,
  conf.writeProperty AS writeProperty
----
2+| Memory estimation of the algorithm
|
[source, cypher]
----
CALL algo.memrec(
  'MyLabel',
  'MY_RELATIONSHIP_TYPE',
  'pageRank',
  {
    writeProperty: 'myWriteProperty',
    write: true
  }
)
----
|
[source, cypher]
----
CALL gds.pageRank.write.estimate(
  {
    nodeProjection: 'MyLabel',
    relationshipProjection: 'MY_RELATIONSHIP_TYPE'
  },
  {
    writeProperty: 'myWriteProperty'
  }
)
----
|===