= Dropping parts of the graph
// fIXME move to seperate section
// TODO tabbed or have different sections?
* reasons - freeing up memory, removing mutated algorithms results

We can also remove relationships from a named graph in the catalog.
This is useful to free up main memory or to remove accidentally added relationship types.

We can also remove node properties from a named graph in the catalog.
This is useful to free up main memory or to remove accidentally added node properties.


== Syntax

.Syntax descriptions of the different drop operations over a graph
[.tabbed-example, caption = ]
====
[.include-with-remove-node-property]
======
[source, cypher, role=noplay]
----
CALL gds.graph.nodeProperties.drop(
    graphName: String,
    nodeProperties: String or List of Strings,
    configuration: Map
)
YIELD
    propertiesRemoved: Integer,
    graphName: String,
    nodeProperties: String or List of String
----

.Parameters
[opts="header",cols="1,3,1,5"]
|===
| Name           | Type                       | Optional | Description
| graphName      | String                     | no       | The name under which the graph is stored in the catalog.
| nodeProperties | String or List of Strings  | no       | The node properties in the graph to remove.
| configuration  | Map                        | yes      | Additional parameters to configure removeNodeProperties.
|===

.Configuration
[opts="header",cols="1,1,1,7"]
|===
| Name                   | Type                  | Default           | Description
| concurrency            | Integer               | 4                 | The number of concurrent threads. Note, this procedure is always running single-threaded.
|===

.Results
[opts="header",cols="2,3,5"]
|===
| Name              | Type                     | Description
| propertiesRemoved | Integer                  | Number of properties removed.
| graphName         | String                   | The name of a graph stored in the catalog.
| nodeProperties    | String or List of String | The removed node properties.
|===
======

[.include-with-remove-relationship-type]
======
[source, cypher, role=noplay]
----
CALL gds.graph.relationships.drop(
    graphName: String,
    relationshipType: String
)
YIELD
  graphName: String,
  relationshipType: String,
  deletedRelationships: Integer,
  deletedProperties: Map
----

.Parameters
[opts="header",cols="1,3,1,5"]
|===
| Name             | Type    | Optional | Description
| graphName        | String  | no       | The name under which the graph is stored in the catalog.
| relationshipType | String  | no       | The relationship type in the graph to remove.
|===

.Results
[opts="header",cols="2,3,5"]
|===
| Name                 | Type       | Description
| graphName            | String     | The name of a graph stored in the catalog.
| relationshipType     | String     | The type of the removed relationships.
| deletedRelationships | Integer    | Number of removed relationships from the in-memory graph.
| deletedProperties    | Integer    | Map where the key is the name of the relationship property, and the value is the number of removed properties under that name.
|===
======
====

== Examples

In order to demonstrate the GDS capabilities over node properties, we are going to create a small social network graph in Neo4j and project it into our graph catalog.

.The following Cypher statement will create the example graph in the Neo4j database:
[source, cypher, role=noplay setup-query]
----
CREATE
  (florentin:Person { name: 'Florentin', age: 16 }),
  (adam:Person { name: 'Adam', age: 18 }),
  (veselin:Person { name: 'Veselin', age: 20 }),
  (hobbit:Book { name: 'The Hobbit', numberOfPages: 310 }),
  (florentin)-[:KNOWS { since: 2010 }]->(adam),
  (florentin)-[:KNOWS { since: 2018 }]->(veselin),
  (adam)-[:READ]->(hobbit)
----

.Project the small social network graph:
[source, cypher, role=noplay graph-project-query]
----
CALL gds.graph.project(
  'socialGraph',
  {
    Person: {properties: "age"},
    Book: {}
  },
  ['KNOWS', 'READ']
)
----

.Compute the Degree Centrality in our social graph:
[source, cypher, role=noplay graph-project-query]
----
CALL gds.degree.mutate('socialGraph', {mutateProperty: 'score'})
----

[[catalog-graph-remove-node-properties-example]]
=== Remove node properties


[role=query-example]
--
.Remove the `score` property from all projected nodes in the `socialGraph`:
[source, cypher, role=noplay]
----
CALL gds.graph.nodeProperties.drop('socialGraph', ['score'])
YIELD propertiesRemoved
----

.Results
[opts="header"]
|===
| propertiesRemoved
| 4
|===
--

[NOTE]
--
The above example requires all given properties to be present on _at least one_ projected node label.
--

[[catalog-graph-delete-rel-type]]
=== Delete relationships of a given type

We can delete all relationships of a given type from a named graph in the catalog.
This is useful to free up main memory or to remove accidentally added relationship types.

[NOTE]
====
Deleting relationships of a given type is only possible if it is not the last relationship type present in the graph.
If we still want to delete these relationships we need to xref:graph-drop.adoc[drop the graph] instead.
====

[role=query-example]
--
.Delete all relationships of type `SIMILAR` from a named graph:
[source, cypher, role=noplay]
----
CALL gds.graph.relationships.drop(
  'socialGraph',                    // <1>
  'READ'                           // <2>
)
YIELD
  graphName, relationshipType, deletedRelationships, deletedProperties
----
<1> The name of the projected graph.
<2> The relationship type we want to delete from the projected graph.

.Results
[opts="header"]
|===
| graphName     | relationshipType | deletedRelationships | deletedProperties
| "socialGraph" | "READ"        | 1                   | {}
|===
--
