[.enterprise-edition]
[[model-catalog-store-ops]]
= Storing models on disk

[.alpha-symbol]
[.tier-note]
The model store feature is in the alpha tier.

The model catalog exists as long as the Neo4j instance is running.
When Neo4j is restarted, models are no longer available in the catalog and need to be trained again.
This can be prevented by storing a model on disk.

The location of the stored models can be configured via the configuration parameter `gds.model.store_location` in the `neo4j.conf`.
The location must be a directory and writable by the Neo4j process.


[NOTE]
====
The `gds.model.store_location` parameter must be configured for this feature.
====

[.alpha]
[[catalog-model-store]]
== Storing models from the catalog on disk

[role=query-example, no-result=true]
--
.Store a model on disk:
[source, cypher, role=noplay]
----
CALL gds.alpha.model.store('my-model')
YIELD
  modelName,
  storeMillis
----
--

.Results
* `modelName`: The name of the stored model.
* `storeMillis`: The number of milliseconds it took to store the model.


*Trained models that can be stored*

* <<algorithms-embeddings-graph-sage,GraphSAGE model>>
* <<algorithms-ml-nodeclassification,Node Classification model>>

[.alpha]
[[catalog-model-load]]
== Loading models from disk

GDS will discover available models from the configured store location upon database startup.
During discovery, only model metadata is loaded, not the actual model data.
In order to use a stored model, it has to be explicitly loaded.

[role=query-example, no-result=true]
--
.Store a model on disk:
[source, cypher, role=noplay]
----
CALL gds.alpha.model.load('my-model')
YIELD
  modelName,
  loadMillis
----
--

.Results
* `modelName`: The name of the stored model.
* `loadMillis`: The number of milliseconds it took to load the model.

If the model is already loaded, nothing happens.
To verify if a model is loaded, we can use the <<catalog-model-list,`gds.beta.model.list`>> procedure.
The procedure returns flags to indicate if the model is stored and if the model is loaded into memory.

[.alpha]
[[catalog-model-delete]]
== Deleting models from disk

To remove a stored model from disk, it has to be deleted.
This is different from dropping a model.
Dropping a model will remove it from the in-memory model catalog, but not from disk.
Deleting a model will remove it from disk, but keep it in the in-memory model catalog if it was already loaded.

[role=query-example, no-result=true]
--
.Store a model on disk:
[source, cypher, role=noplay]
----
CALL gds.alpha.model.delete('my-model')
YIELD
  modelName,
  deleteMillis
----
--

.Results
* `modelName`: The name of the stored model.
* `deleteMillis`: The number of milliseconds it took to delete the model.
