[[model-catalog-store-ops]]
[.alpha]
= Storing models on disk

The model catalog exists as long as the Neo4j instance is running.
When Neo4j is restarted, models are no longer available in the catalog and need to be trained again.
This can be prevented by storing a model on disk.

The location of the stored models can be configured via the configuration parameter `gds.model.store_location` in the `neo4j.conf`.
The location must be a directory and writable by the Neo4j process.


[NOTE]
====
The `gds.model.store_location` parameter must be configured for this feature.
====

[[catalog-model-store]]
== Storing models from the catalog on disk

.Store a model on disk:
[source,cypher]
----
CALL gds.alpha.model.store('my-model')
YIELD
  modelName,
  storeMillis
----

.Results
* `modelName`: The name of the stored model
* `storeMillis`: the number of milliseconds it took to store the model.


[[catalog-model-load]]
== Loading models from disk

GDS will discover available models from the configured store location upon startup of the database.
Only metadata is loaded for stored models, not the actual model data.
In order to use a stored model, it has to be loaded.

.Store a model on disk:
[source,cypher]
----
CALL gds.alpha.model.load('my-model')
YIELD
  modelName,
  loadMillis
----

.Results
* `modelName`: The name of the stored model
* `loadMillis`: the number of milliseconds it took to load the model.

If the model is already loaded, nothing happens.
To check if a model is loaded, we can use the <<catalog-model-list,`gds.beta.model.list`>> procedure.

[[catalog-model-delete]]
== Deleting models from disk

To remove a stored model from the disk, it has to be deleted.
This is different from dropping a model.
Dropping a model will remove it from the in-memory model catalog, but not from disk.
Deleting a model will remove it from disk, but keep it in the in-memory model catalog if it was already loaded.

.Store a model on disk:
[source,cypher]
----
CALL gds.alpha.model.delete('my-model')
YIELD
  modelName,
  deleteMillis
----

.Results
* `modelName`: The name of the stored model
* `deleteMillis`: the number of milliseconds it took to delete the model.
