[[python-client-getting-started]]
= Getting started

The design philosophy of the Python client is to mimic the GDS Cypher API in Python code.
The Python client will translate the Python code written by the user to a corresponding Cypher query which it will then run on the Neo4j server using a Neo4j Python driver connection.

The Python client attempts to be as pythonic as possible to maximize convenience for users accustomed to and experienced with Python environments.
As such standard Python and pandas types are used as much as possible.
However, to be consistent with the Cypher surface the general return value of calling a method corresponding to a Cypher procedure will be in the form of a table (a pandas `DataFrame` in Python).
Read more about this in xref:python-client/getting-started.adoc#python-client-getting-started-mapping[Mapping between Cypher and Python].

The root component of the Python client is the `GraphDataScience` object.
Once instantiated it forms the entrypoint to interacting with the GDS library.
That includes projecting graphs, running algorithms, and defining and using machine learning pipelines in GDS.
As a convention we recommend always calling the instantiated `GraphDataScience` object `gds` as using it will then most resemble using the Cypher API directly.


== Import and setup

The simplest way to instantiate the `GraphDataScience` object is from a Neo4j server URI and corresponding credentials:

[source,python]
----
from graphdatascience import GraphDataScience

# Use Neo4j URI and credentials according to your setup
gds = GraphDataScience("bolt://localhost:7687", auth=None)

print(gds.version())
----

.Results:
[source]
----
"2.0.0-alpha01"
----

Alternatively, for use cases where direct access and control of the Neo4j driver is required, one can use the method `GraphDataScience.from_neo4j_driver` for instantiating the gds object.

If we don't want to use the default database of our DBMS, we can specify which one to use:

[source,python]
----
gds.set_database("my-db")
----

To check if the GDS server library we're running against is licensed we can make the following call:

[source,python]
----
using_enterprise = gds.is_licensed()
----

[NOTE]
====
The client library is designed so that most methods are inferred under the hood as you type them via a string building scheme and overloading the magic `\\__getattr__` method.
Therefore most methods, such as `pageRank`, will not appear when calling `dir(gds)`.
Similarly, IDEs and language servers will not be able to detect these automatically inferred methods, meaning that the auto-completion support they provide will be limited.

Rest assured however that despite the lack of this type of discoverability the inferred methods, such as `gds.pageRank.stream`, will still be called correctly.
====


=== AuraDS

If you are connecting the client to an https://neo4j.com/cloud/graph-data-science/[AuraDS instance], you can get recommended non-default configuration settings of the Python Driver applied automatically.
To achieve this, set the constructor argument `aura_ds=True`:

[source, python]
----
from graphdatascience import GraphDataScience

# Configures the driver with AuraDS-recommended settings
gds = GraphDataScience(
    "neo4j+s://my-aura-ds.databases.neo4j.io:7687",
    auth=("neo4j", "my-password"),
    aura_ds=True
)
----


== Minimal example

In the following example we illustrate the Python client to run a Cypher query, project a graph into GDS, run an algorithm and inspect the result via the client-side graph object.

[source,python]
----
from graphdatascience import GraphDataScience

# We follow the convention to name our `GraphDataScience` object `gds`
gds = GraphDataScience("bolt://my-server.neo4j.io:7687", auth=("neo4j", "my-password"))

# Create a minimal example graph
gds.run_cypher(
  """
  CREATE
  (m: City {name: "Malmö"}),
  (l: City {name: "London"}),
  (s: City {name: "San Mateo"}),
  (m)-[:FLY_TO]->(l),
  (l)-[:FLY_TO]->(m),
  (l)-[:FLY_TO]->(s),
  (s)-[:FLY_TO]->(l)
  """
)

# Project the graph into the GDS Graph Catalog
# We call the object representing the projected graph `G_office`
G_office, _ = gds.graph.project("neo4j-offices", "City", "FLY_TO")

# Run the mutate mode of the PageRank algorithm
_ = gds.pageRank.mutate(G_office, tolerance=0.5, mutateProperty="rank")

# We can inspect the node properties of our projected graph directly
# via the graph object and see that indeed the new property exists
print(G_office.node_properties("City"))
----

.Results:
[source]
----
["rank"]
----


== Close open connections

Similarly to how the Neo4j Python driver supports closing all open connections to the DBMS, you can call `close` on the `GraphDataScience` object to the same effect:

[source,python]
----
# Close any open connections in the underlying Neo4j driver's connection pool
gds.close()
----

`close` is also called automatically when the `GraphDataScience` object is deleted.


[[python-client-getting-started-mapping]]
== Mapping between Cypher and Python

There are some general principles for how the Cypher API maps to the Python client API:

* Method calls corresponding to Cypher procedures (preceded by `CALL` in the docs) return:
+
--
* A table as a pandas `DataFrame`, if the procedure returns several rows (eg. stream mode algorithm calls).
* A row as a pandas `Series`, if the procedure returns exactly one row (eg. stats mode algorithm calls).
--
+
Some notable exceptions to this are:

** Procedures instantiating xref:python-client/graph-object.adoc[graph objects] and xref:python-client/model-object.adoc[model objects] have two return values: a graph or model object, and a row of metadata (typically a pandas `Series`) from the underlying procedure call.
** Any methods on xref:python-client/pipelines.adoc[pipeline], xref:python-client/graph-object.adoc[graph] or xref:python-client/model-object.adoc[model] objects (native to the Python client) mapping to Cypher procedures.
** `gds.version()` which returns a string.
* Method calls corresponding to Cypher functions (preceded by `RETURN` in the docs) will simply return the value the function returns.
* The Python client also contains specific functionality for inspecting graphs from the xref:management-ops/graph-catalog-ops.adoc[GDS Graph Catalog], using a client-side xref:python-client/graph-object.adoc[graph object].
Similarly, models from the xref:model-catalog/index.adoc[GDS Model Catalog] can be inspected using a client-side xref:python-client/model-object.adoc[model object].
* Cypher functions and procedures of GDS that take references to graphs and/or models as strings for input typically instead take xref:python-client/graph-object.adoc[graph objects] and/or xref:python-client/model-object.adoc[model objects] as input in the Python client API.
* To configure and use xref:machine-learning/machine-learning.adoc[machine learning pipelines] in GDS, specific xref:python-client/pipelines.adoc[pipeline objects] are used in the Python client.
