[[python-client-pipelines]]
= Machine learning pipelines

The Python client has special support for xref:machine-learning/linkprediction-pipelines/link-prediction.adoc[Link prediction pipelines] and xref:machine-learning/node-property-prediction/nodeclassification-pipelines/node-classification.adoc[Node classification pipelines].
The GDS pipelines are represented as pipeline objects.

The Python method calls to _create_ the pipelines match their Cypher counterparts exactly.
However, the rest of the pipeline functionality is deferred to methods on the pipeline objects themselves.
Once created, the `TrainingPipeline` can be passed as arguments to methods in the Python client, such as the xref:pipeline-catalog/pipeline-catalog.adoc[pipeline catalog operations].
Additionally, the `TrainingPipeline` has convenience methods allowing for inspection of the pipeline represented without explicitly involving the pipeline catalog.

include::partial$/pythonclient/python-client-gds-object.adoc[]


== Node classification

This section outlines how to use the Python client to build, configure and train a xref:machine-learning/node-property-prediction/nodeclassification-pipelines/node-classification.adoc[node classification pipeline], as well as how to use the model that training produces for predictions.


=== Pipeline

The creation of the node classification pipeline is very similar to xref:machine-learning/node-property-prediction/nodeclassification-pipelines/config.adoc#nodeclassification-creating-a-pipeline[how it's done in Cypher].
To create a new node classification pipeline one would make the following call:

[source,python]
----
pipe, res = gds.beta.pipeline.nodeClassification.create("my-pipe")
----

where `pipe` is a pipeline object, and `res` is a pandas `Series` containing metadata from the underlying procedure call.

To then go on to build, configure and train the pipeline we would call methods directly on the node classification pipeline object.
Below is a description of the methods on such objects:

.Node classification pipeline methods
[opts="header",cols="2m,2m,2m,3"]
|===
| Name                  | Arguments                     | Return type             | Description
| addNodeProperty       | procedure_name: str, +
                            config: **kwargs            | Series                  | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/config.adoc#nodeclassification-pipelines-adding-node-properties[Add an algorithm that produces a node property to the pipeline, with optional algorithm-specific configuration].
| selectFeatures        | node_properties: +
                            Union[str, list[str]]       | Series                  | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/config.adoc#nodeclassification-pipelines-adding-features[Select node properties to be used as features].
| configureSplit        | config: **kwargs              | Series                  | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/config.adoc#nodeclassification-pipelines-configure-splits[Configure the train-test dataset split].
| addLogisticRegression | parameter_space: +
                            dict[str, any]              | Series                  | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/config.adoc#nodeclassification-pipelines-adding-model-candidates[Add a logistic regression model configuration to train as a candidate in the model selection phase]. footnote:range[Ranges can also be given as length two `Tuple`s. I.e. `(x, y)` is the same as `{range: [x, y]}`.]
| addRandomForest       | parameter_space: +
                            dict[str, any]              | Series                  | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/config.adoc#nodeclassification-pipelines-adding-model-candidates[Add a random forest model configuration to train as a candidate in the model selection phase]. footnote:range[]
| addMLP                | parameter_space: +
                            dict[str, any]              | Series                  | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/config.adoc#nodeclassification-pipelines-adding-model-candidates[Add an MLP model configuration to train as a candidate in the model selection phase]. footnote:range[]
| configureAutoTuning   | config: **kwargs
                                                        | Series                  | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/config.adoc#nodeclassification-pipelines-configure-auto-tuning[Configure the auto-tuning].
| train                 | G: Graph, +
                            config: **kwargs            | NCPredictionPipeline, +
                                                             Series          | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/training.adoc[Train the pipeline on the given input graph using given keyword arguments].
| train_estimate        | G: Graph, +
                            config: **kwargs            | Series                  | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/training.adoc#nodeclassification-pipelines-examples-train-memory-estimation[Estimate training the pipeline on the given input graph using given keyword arguments].
| node_property_steps   | -                             | DataFrame               | Returns the node property steps of the pipeline.
| feature_properties    | -                             | Series                  | Returns a list of the selected feature properties for the pipeline.
| split_config          | -                             | Series                  | Returns the configuration set up for train-test splitting of the dataset.
| parameter_space       | -                             | Series                  | Returns the model parameter space set up for model selection when training.
| auto_tuning_config    | -                             | Series                  | Returns the configuration set up for auto-tuning.
| name                  | -                             | str                     | The name of the pipeline as it appears in the pipeline catalog.
| type                  | -                             | str                     | The type of pipeline.
| creation_time         | -                             | neo4j.time.Datetime     | Time when the pipeline was created.
| drop                  | failIfMissing: Optional[bool] | Series                  | xref:pipeline-catalog/drop.adoc[Removes the pipeline] from the GDS Pipeline Catalog.
| exists                | -                             | bool                    | `True` if the model exists in the GDS Pipeline Catalog, `False` otherwise.
|===

There are two main differences when comparing the methods above that map to procedures of the Cypher API:

* As the Python methods are called on the pipeline object, one does not need to provide a name when calling them.
* Configuration parameters in the Cypher calls are represented by named keyword arguments in the Python method calls.

Another difference is that the `train` Python call takes a xref:python-client/graph-object.adoc[graph object] instead of a graph name, and returns a `NCModel` xref:python-client/model-object.adoc[model object] that we can run predictions with as well as a pandas `Series` with the metadata from the training.

Please consult the xref:machine-learning/node-property-prediction/nodeclassification-pipelines/node-classification.adoc[node classification Cypher documentation] for information about what kind of input the methods expect.


[[python-client-pipelines-nodeclassification-pipe-example]]
==== Example

Below is a small example of how one could configure and train a very basic node classification pipeline.
Note that we don't configure splits explicitly, but rather use the default.
We suppose that the graph `G` we train on has a node property "my-class" which will be the target of our classification training.

[source,python]
----
pipe, _ = gds.beta.pipeline.nodeClassification.create("my-pipe")

# Add Degree centrality as a property step producing "rank" node properties
pipe.addNodeProperty("degree", mutateProperty="rank")

# Select our "rank" property as a feature for the model training
pipe.selectFeatures("rank")

# Verify that the features to be used in model training are what we expect
steps = pipe.feature_properties()
assert len(steps) == 1
assert steps[0]["feature"] == "rank"

# Configure the model training to do cross-validation over logistic regression
pipe.addLogisticRegression(tolerance=(0.01, 0.001))
pipe.addLogisticRegression(penalty=1.0)

# Train the pipeline targeting node property "my-class" as label and "ACCURACY" as only metric
trained_pipe_model, res = pipe.train(G, modelName="my-model", targetProperty="my-class", metrics=["ACCURACY"])
assert res["trainMillis"] >= 0
----

A model referred to as "my-model" in the xref:model-catalog/index.adoc[GDS Model Catalog] is produced.
In the next section we will go over how to use that model to make predictions.


=== Model

As we saw in the previous section, node classification models are created when training a node classification pipeline.
In addition to inheriting the methods common to all xref:python-client/model-object.adoc[model objects], node classification models have the following methods:

.Node classification model methods
[opts="header",cols="8m,6m,4m,13"]
|===
| Name                    | Arguments        | Return type | Description
| predict_mutate          | G: Graph, +
                            config: **kwargs | Series      | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/predict.adoc#nodeclassification-pipelines-examples-mutate[Predict classes for nodes of the input graph and mutate graph with predictions].
| predict_mutate_estimate | G: Graph, +
                            config: **kwargs | Series      | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/predict.adoc#nodeclassification-pipelines-examples-predict-memory-estimation[Estimate predicting classes for nodes of the input graph and mutating graph with predictions].
| predict_stream          | G: Graph, +
                            config: **kwargs | DataFrame   | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/predict.adoc#node-classification-pipelines-predict-examples-stream[Predict classes for nodes of the input graph and stream the results].
| predict_stream_estimate | G: Graph, +
                            config: **kwargs | Series      | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/predict.adoc#nodeclassification-pipelines-examples-predict-memory-estimation[Estimate predicting classes for nodes of the input graph and streaming the results].
| predict_write           | G: Graph, +
                            config: **kwargs | Series      | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/predict.adoc#nodeclassification-pipelines-examples-write[Predict classes for nodes of the input graph and write results back to the database].

| predict_write_estimate  | G: Graph, +
                            config: **kwargs | Series      | xref:machine-learning/node-property-prediction/nodeclassification-pipelines/predict.adoc#nodeclassification-pipelines-examples-predict-memory-estimation[Estimate predicting classes for nodes of the input graph and writing the results back to the database].
| metrics                 | -                | Series      | Returns values for the metrics specified when training, for this particular model.
|===

One can note that the predict methods are indeed very similar to xref:machine-learning/node-property-prediction/nodeclassification-pipelines/predict.adoc[their Cypher counterparts].
The three main differences are that:

* They take a xref:python-client/graph-object.adoc[graph object] instead of a graph name.
* They have Python keyword arguments representing the keys of the configuration map.
* One does not have to provide a "modelName" since the xref:python-client/model-object.adoc[model object] used itself have this information.


==== Example (continued)

We now continue the xref:python-client/pipelines.adoc#python-client-pipelines-nodeclassification-pipe-example[example above] using the node classification model `trained_pipe_model` we trained there.
Suppose that we have a new graph `H` that we want to run predictions on.

[source,python]
----
# Make sure our model performed well enough on the test set
metrics = trained_pipe_model.metrics()
assert metrics["ACCURACY"]["test"] >= 0.85

# Predict on `H` and stream the results with a specific concurrency of 8
result = trained_pipe_model.predict_stream(H, concurrency=8)
assert len(results) == H.node_count()
----


== Link prediction

This section outlines how to use the Python client to build, configure and train a xref:machine-learning/linkprediction-pipelines/link-prediction.adoc[link prediction pipeline], as well as how to use the model that training produces for predictions.


=== Pipeline

The creation of the link prediction pipeline is very similar to xref:machine-learning/linkprediction-pipelines/config.adoc#linkprediction-creating-a-pipeline[how it's done in Cypher].
To create a new link prediction pipeline one would make the following call:


[source,python]
----
pipe, res = gds.beta.pipeline.linkPrediction.create("my-pipe")
----

where `pipe` is a pipeline object, and `res` is a pandas `Series` containing metadata from the underlying procedure call.

To then go on to build, configure and train the pipeline we would call methods directly on the link prediction pipeline object.
Below is a description of the methods on such objects:

.Link prediction pipeline methods
[opts="header",cols="2m,2m,2m,3"]
|===
| Name                  | Arguments                     | Return type         | Description
| addNodeProperty       | procedure_name: str, +
                        config: **kwargs                | Series              | xref:machine-learning/linkprediction-pipelines/config.adoc#linkprediction-adding-node-properties[Add an algorithm that produces a node property to the pipeline, with optional algorithm-specific configuration].
| addFeature            | feature_type: str, +
                        config: **kwargs                | Series              | xref:machine-learning/linkprediction-pipelines/config.adoc#linkprediction-adding-features[Add a link feature for model training based on node properties and a feature combiner].
| configureSplit        | config: **kwargs              | Series              | xref:machine-learning/linkprediction-pipelines/config.adoc#linkprediction-configure-splits[Configure the feature-train-test dataset split].
| addLogisticRegression | parameter_space: +
                          dict[str, any]                | Series              | xref:machine-learning/linkprediction-pipelines/config.adoc#linkprediction-adding-model-candidates[Add a logistic regression model configuration to train as a candidate in the model selection phase]. footnote:range[Ranges can also be given as length two `Tuple`s. I.e. `(x, y)` is the same as `{range: [x, y]}`.]
| addRandomForest       | parameter_space: +
                          dict[str, any]                | Series              | xref:machine-learning/linkprediction-pipelines/config.adoc#linkprediction-adding-model-candidates[Add a random forest model configuration to train as a candidate in the model selection phase]. footnote:range[]
| addMLP                | parameter_space: +
                          dict[str, any]                | Series              | xref:machine-learning/linkprediction-pipelines/config.adoc#linkprediction-adding-model-candidates[Add an MLP model configuration to train as a candidate in the model selection phase]. footnote:range[]
| configureAutoTuning   | config: **kwargs
                                                        | Series              | xref:machine-learning/linkprediction-pipelines/config.adoc#linkprediction-configure-auto-tuning[Configure the auto-tuning].
| train                 | G: Graph, +
config: **kwargs        | LPPredictionPipeline, +
                                                  Series               | xref:machine-learning/linkprediction-pipelines/training.adoc[Train the model on the given input graph using given keyword arguments].
| train_estimate        | G: Graph, +
                        config: **kwargs                | Series              | xref:machine-learning/linkprediction-pipelines/training.adoc#linkprediction-pipeline-examples-train-estimate[Estimate training the pipeline on the given input graph using given keyword arguments].
| node_property_steps   | -                             | DataFrame           | Returns the node property steps of the pipeline.
| feature_steps         | -                             | DataFrame           | Returns a list of the selected feature steps for the pipeline.
| split_config          | -                             | Series              | Returns the configuration set up for feature-train-test splitting of the dataset.
| parameter_space       | -                             | Series              | Returns the model parameter space set up for model selection when training.
| auto_tuning_config    | -                             | Series              | Returns the configuration set up for auto-tuning.
| name                  | -                             | str                 | The name of the pipeline as it appears in the pipeline catalog.
| type                  | -                             | str                 | The type of pipeline.
| creation_time         | -                             | neo4j.time.Datetime | Time when the pipeline was created.
| drop                  | failIfMissing: Optional[bool] | Series                  | xref:pipeline-catalog/drop.adoc[Removes the pipeline] from the GDS Pipeline Catalog.
| exists                | -                             | bool                | `True` if the model exists in the GDS Pipeline Catalog, `False` otherwise.
|===

There are two main differences when comparing the methods above that map to procedures of the Cypher API:

* As the Python methods are called on the pipeline object, one does not need to provide a name when calling them.
* Configuration parameters in the Cypher calls are represented by named keyword arguments in the Python method calls.

Another difference is that the `train` Python call takes a xref:python-client/graph-object.adoc[graph object] instead of a graph name, and returns a `LPModel` xref:python-client/model-object.adoc[model object] that we can run predictions with as well as a pandas `Series` with the metadata from the training.

Please consult the xref:machine-learning/linkprediction-pipelines/link-prediction.adoc[link prediction Cypher documentation] for information about what kind of input the methods expect.


[[python-client-pipelines-linkprediction-pipe-example]]
==== Example

Below is a small example of how one could configure and train a very basic link prediction pipeline.
Note that we don't configure training parameters explicitly, but rather use the default.
Suppose we have a graph `G` that we want to train our pipeline on.

[source,python]
----
pipe, _ = gds.beta.pipeline.linkPrediction.create("my-pipe")

# Add FastRP as a property step producing "embedding" node properties
pipe.addNodeProperty("fastRP", embeddingDimension=128, mutateProperty="embedding")

# Combine our "embedding" node properties with Hadamard to create link features for training
pipe.addFeature("hadamard", nodeProperties=["embedding"])

# Verify that the features to be used in model training are what we expect
steps = pipe.feature_steps()
assert len(steps) == 1
assert steps[0]["name"] == "HADAMARD"

# Specify the fractions we want for our dataset split
pipe.configureSplit(trainFraction=0.2, testFraction=0.1)

# Add a random forest model with tuning over `maxDepth`
pipe.addRandomForest(maxDepth=(2, 20))

# Train the pipeline and produce a model named "my-model"
trained_pipe_model, res = pipe.train(G, modelName="my-model")
assert res["trainMillis"] >= 0
----

A model referred to as "my-model" in the xref:model-catalog/index.adoc[GDS Model Catalog] is produced.
In the next section we will go over how to use that model to make predictions.


=== Model

As we saw in the previous section, link prediction models are created when training a link prediction pipeline.
In addition to inheriting the methods common to all xref:python-client/model-object.adoc[model objects], link prediction models have the following methods:

.Link prediction model methods
[opts="header",cols="8m,6m,4m,13"]
|===
| Name                    | Arguments        | Return type | Description
| predict_mutate          | G: Graph, +
                            config: **kwargs | Series      | xref:machine-learning/linkprediction-pipelines/predict.adoc#algorithms-link-prediction-pipelines-predict-examples-mutate[Predict links between non-neighboring nodes of the input graph and mutate graph with predictions].
| predict_mutate_estimate | G: Graph, +
                            config: **kwargs | Series      | xref:machine-learning/linkprediction-pipelines/predict.adoc#algorithms-link-prediction-pipelines-predict-examples-estimate[Estimate predicting links between non-neighboring nodes of the input graph and mutating graph with predictions].
| predict_stream          | G: Graph, +
                            config: **kwargs | DataFrame   | xref:machine-learning/linkprediction-pipelines/predict.adoc#algorithms-link-prediction-pipelines-predict-examples-stream[Predict links between non-neighboring nodes of the input graph and stream the results].
| predict_stream_estimate | G: Graph, +
                            config: **kwargs | Series      | xref:machine-learning/linkprediction-pipelines/predict.adoc#algorithms-link-prediction-pipelines-predict-examples-estimate[Estimate predicting links between non-neighboring nodes of the input graph and streaming the results].
| metrics                 | -                | Series      | Returns values for the metrics used when training, for this particular model.
|===

One can note that the predict methods are indeed very similar to xref:machine-learning/linkprediction-pipelines/predict.adoc[their Cypher counterparts].
The three main differences are that:

* They take a xref:python-client/graph-object.adoc[graph object] instead of a graph name.
* They have Python keyword arguments representing the keys of the configuration map.
* One does not have to provide a "modelName" since the xref:python-client/model-object.adoc[model object] used itself have this information.


==== Example (continued)

We now continue the xref:python-client/pipelines.adoc#python-client-pipelines-linkprediction-pipe-example[example above] using the link prediction model `trained_pipe_model` we trained there.
Suppose that we have a new graph `H` that we want to run predictions on.

[source,python]
----
# Make sure our model performed well enough on the test set
metrics = trained_pipe_model.metrics()
assert metrics["AUCPR"]["test"] >= 0.85

# Predict on `H` and mutate it with the relationship predictions
results = trained_pipe_model.predict_mutate(H, topN=5, mutateRelationshipType="PRED_REL")
assert result["relationshipsWritten"] == 5 * 2  # Undirected relationships
----


== Node regression

This section outlines how to use the Python client to build, configure and train a xref:machine-learning/node-property-prediction/noderegression-pipelines/node-regression.adoc[node regression pipeline], as well as how to use the model that training produces for predictions.


=== Pipeline

The creation of the node regression pipeline is very similar to xref:machine-learning/node-property-prediction/noderegression-pipelines/config.adoc#noderegression-creating-a-pipeline[how it's done in Cypher].
To create a new node regression pipeline one would make the following call:

[source,python]
----
pipe, res = gds.alpha.pipeline.nodeRegression.create("my-pipe")
----

where `pipe` is a pipeline object, and `res` is a pandas `Series` containing metadata from the underlying procedure call.

To then go on to build, configure and train the pipeline we would call methods directly on the node regression pipeline object.
Below is a description of the methods on such objects:

.Node regression pipeline methods
[opts="header",cols="2m,2m,2m,3"]
|===
| Name                  | Arguments                     | Return type             | Description
| addNodeProperty       | procedure_name: str, +
config: **kwargs        | Series                        | xref:machine-learning/node-property-prediction/noderegression-pipelines/config.adoc#noderegression-pipelines-adding-node-properties[Add an algorithm that produces a node property to the pipeline, with optional algorithm-specific configuration].
| selectFeatures        | node_properties: +
Union[str, list[str]]   | Series                        | xref:machine-learning/node-property-prediction/noderegression-pipelines/config.adoc#noderegression-pipelines-adding-features[Select node properties to be used as features].
| configureSplit        | config: **kwargs              | Series                  | xref:machine-learning/node-property-prediction/noderegression-pipelines/config.adoc#noderegression-pipelines-configure-splits[Configure the train-test dataset split].
| addLinearRegression   | parameter_space: +
dict[str, any]          | Series                        | xref:machine-learning/node-property-prediction/noderegression-pipelines/config.adoc#noderegression-pipelines-adding-model-candidates[Add a linear regression model configuration to train as a candidate in the model selection phase]. footnote:range[Ranges can also be given as length two `Tuple`s. I.e. `(x, y)` is the same as `{range: [x, y]}`.]
| addRandomForest       | parameter_space: +
dict[str, any]          | Series                        | xref:machine-learning/node-property-prediction/noderegression-pipelines/config.adoc#noderegression-pipelines-adding-model-candidates[Add a random forest model configuration to train as a candidate in the model selection phase]. footnote:range[]
| configureAutoTuning   | config: **kwargs              | Series                  | xref:machine-learning/node-property-prediction/noderegression-pipelines/config.adoc#noderegression-pipelines-configure-auto-tuning[Configure the auto-tuning].
| train                 | G: Graph, +
config: **kwargs        | NCPredictionPipeline, +
Series          | xref:machine-learning/node-property-prediction/noderegression-pipelines/training.adoc[Train the pipeline on the given input graph using given keyword arguments].
| node_property_steps   | -                             | DataFrame               | Returns the node property steps of the pipeline.
| feature_properties    | -                             | Series                  | Returns a list of the selected feature properties for the pipeline.
| split_config          | -                             | Series                  | Returns the configuration set up for train-test splitting of the dataset.
| parameter_space       | -                             | Series                  | Returns the model parameter space set up for model selection when training.
| auto_tuning_config    | -                             | Series                  | Returns the configuration set up for auto-tuning.
| name                  | -                             | str                     | The name of the pipeline as it appears in the pipeline catalog.
| type                  | -                             | str                     | The type of pipeline.
| creation_time         | -                             | neo4j.time.Datetime     | Time when the pipeline was created.
| drop                  | failIfMissing: Optional[bool] | Series                  | xref:pipeline-catalog/drop.adoc[Removes the pipeline] from the GDS Pipeline Catalog.
| exists                | -                             | bool                    | `True` if the model exists in the GDS Pipeline Catalog, `False` otherwise.
|===

There are two main differences when comparing the methods above that map to procedures of the Cypher API:

* As the Python methods are called on the pipeline object, one does not need to provide a name when calling them.
* Configuration parameters in the Cypher calls are represented by named keyword arguments in the Python method calls.

Another difference is that the `train` Python call takes a xref:python-client/graph-object.adoc[graph object] instead of a graph name, and returns a `NRModel` xref:python-client/model-object.adoc[model object] that we can run predictions with as well as a pandas `Series` with the metadata from the training.

Please consult the xref:machine-learning/node-property-prediction/noderegression-pipelines/node-regression.adoc[node regression Cypher documentation] for information about what kind of input the methods expect.


[[python-client-pipelines-noderegression-pipe-example]]
==== Example

Below is a small example of how one could configure and train a very basic node regression pipeline.
Note that we don't configure splits explicitly, but rather use the default.
We suppose that the graph `G` we train on has a node property "my-target" which will be the target of our regression training.

[source,python]
----
pipe, _ = gds.alpha.pipeline.nodeRegression.create("my-pipe")

# Add Degree centrality as a property step producing "rank" node properties
pipe.addNodeProperty("degree", mutateProperty="rank")

# Select our "rank" property as a feature for the model training
pipe.selectFeatures("rank")

# Verify that the features to be used in model training are what we expect
steps = pipe.feature_properties()
assert len(steps) == 1
assert steps[0]["feature"] == "rank"

# Configure the model training to do cross-validation over linear regression
pipe.addLinearRegression(tolerance=(0.01, 0.001))
pipe.addLinearRegression(penalty=1.0)

# Train the pipeline targeting node property "my-target" as label and "MEAN_SQUARED_ERROR" as only metric
trained_pipe_model, res = pipe.train(G, modelName="my-model", targetProperty="my-target", metrics=["MEAN_SQUARED_ERROR"])
assert res["trainMillis"] >= 0
----

A model referred to as "my-model" in the xref:model-catalog/index.adoc[GDS Model Catalog] is produced.
In the next section we will go over how to use that model to make predictions.


=== Model

As we saw in the previous section, node regression models are created when training a node regression pipeline.
In addition to inheriting the methods common to all xref:python-client/model-object.adoc[model objects], node regression models have the following methods:

.Node regression model methods
[opts="header",cols="8m,6m,4m,13"]
|===
| Name                    | Arguments        | Return type | Description
| predict_mutate          | G: Graph, +
config: **kwargs | Series      | xref:machine-learning/node-property-prediction/noderegression-pipelines/predict.adoc#noderegression-pipelines-predict-examples-mutate[Predict property values for nodes of the input graph and mutate graph with predictions].
| predict_stream          | G: Graph, +
config: **kwargs | DataFrame   | xref:machine-learning/node-property-prediction/noderegression-pipelines/predict.adoc#noderegression-pipelines-predict-examples-stream[Predict property values for nodes of the input graph and stream the results].
| metrics                 | -                | Series      | Returns values for the metrics specified when training, for this particular model.
|===

One can note that the predict methods are indeed very similar to xref:machine-learning/node-property-prediction/noderegression-pipelines/predict.adoc[their Cypher counterparts].
The three main differences are that:

* They take a xref:python-client/graph-object.adoc[graph object] instead of a graph name.
* They have Python keyword arguments representing the keys of the configuration map.
* One does not have to provide a "modelName" since the xref:python-client/model-object.adoc[model object] used itself have this information.


==== Example (continued)

We now continue the xref:python-client/pipelines.adoc#python-client-pipelines-noderegression-pipe-example[example above] using the node regression model `trained_pipe_model` we trained there.
Suppose that we have a new graph `H` that we want to run predictions on.

[source,python]
----
# Make sure our model performed well enough on the test set
metrics = trained_pipe_model.metrics()
assert metrics["MEAN_SQUARED_ERROR"]["test"] <= 20.0

# Predict on `H` and stream the results with a specific concurrency of 8
result = trained_pipe_model.predict_stream(H, concurrency=8)
assert len(results) == H.node_count()
----


== The pipeline catalog

The primary way to use pipeline objects is for training models.
Additionally, pipeline objects can be used as input to xref:pipeline-catalog/pipeline-catalog.adoc[GDS Pipeline Catalog operations].
For instance, supposing we have a pipeline object `pipe`, we could:

[source,python]
----
catalog_contains_pipe = gds.beta.pipeline.exists(pipe)

gds.beta.model.drop(pipe)  # same as pipe.drop()
----

A pipeline object that has already been created and is present in the pipeline catalog can be retrieved calling the `get` method with its name:

[source,python]
----
pipeline = gds.pipeline.get("node_pipeline")
----

[NOTE]
====
The `get` method does not use any tier prefix because it is not associated to any tier. It only exists in the client and does not have a corresponding Cypher procedure.
====
