[[fastpath]]
[.preview]
= FastPath
:description: This section describes the FastPath path embedding algorithm in Neo4j Graph Data Science, available in Aura Graph Analytics.
:entity: node
:result: embedding
:algorithm: FastPath

include::partial$/product-limitations/only-in-serverless.adoc[]

:heterogeneous-nodes:
:heterogeneous-rels:
:node-properties:
include::partial$/algorithms/shared/algorithm-traits.adoc[]


[[algorithms-fastpath-intro]]
== Introduction

FastPath is a light-weight _path embedding_ algorithm for temporal graphs.
It computes vector embeddings from event sequences, which can be used in machine learning tasks such as customer journey analysis.
It is an adaptation of xref:./fastrp.adoc#algorithms-embeddings-fastrp-introduction[FastRP], sharing its qualities in dimensionality reduction.

Embeddings computed by FastPath are invariant to absolute timestamps, relying instead on event timings relative to a given observation time of their path.
This allows for accurate comparison of paths occurring at different points in time.

Embeddings are computed as a sum of individual event contributions, with more significance assigned to more recent events.
Each path is considered independently, which allows for computing embeddings in batches or incrementally, staying compatible with those computed before.

=== Input
An event sequence consists of a _base node_ with which the embedding will be associated, and one or more _event nodes_ tied to the base node.
The input graph may contain an arbitrary number of such event sequences.

There are two supported xref:fastpath-considerations-graph-schema[graph schemas] that encode the event sequences.

=== Event elapsed time
The _observation time_ for an event sequence is given as a property of the _base node_, or as a parameter applied to all event sequences.

_Event times_ are defined by a property of the _event node_, or by the node's position in the event sequence, counted as the number of hops past the first event.

Event _elapsed_ times are then defined as the _observation time_ subtracted by the _event time_.
Only events occurring _before_ the observation time (i.e. with an event time strictly lower than the observation time) will contribute to resulting embeddings.

=== Event information
An event's contribution to the resulting embedding depends on the event _elapsed_ time, as well as information tied to the event node.
This information can be a combination of three things

* categorical _properties_
* relationships to _context nodes_
* floating point _feature vectors_

Events having both similar _elapsed_ times and similar information will have similar contributions to the resulting embeddings of their respective paths.
If either the _elapsed_ time or information differs significantly, their contributions will on average be orthogonal.

What constitutes a significant difference in elapsed time depends on the xref:fastpath-considerations-grid[grid settings] and xref:fastpath-considerations-smoothing[time smoothing].

NOTE: FastPath requires the link:https://neo4j.com/docs/aura/graph-analytics/#aura-gds-serverless[feature] enabled for your Neo4j Aura project.

[[algorithms-fastpath-considerations]]
== Considerations


[[fastpath-considerations-graph-schema]]
=== Graph schema and relationship configuration

The algorithm supports two different schemas for connecting base nodes to event nodes.

1. To use the first schema configuration you provide a `firstRelationshipType` and a `nextRelationshipType`; `eventNodeTimeProperty` is optional.
With this configuration each base and event node is assumed to be part of a path of the pattern:
`(:baseNodeLabel)-[:firstRelationshipType]-(:eventNodeLabel)-[:nextRelationshipType]-...-[:nextRelationshipType]->(:eventNodeLabel)`
image:fastpath-pics/fastpath-schema.svg[]
2. To use the second schema configuration, you provide only a `eventNodeTimeProperty`.
It is then assumed that each base node has outgoing relationships to each of its event nodes:
`(:baseNodeLabel)-[:]->(:eventNodeLabel)`

image::fastpath-pics/fastpath-schema-2.svg[width=400]

Optionally, the schema can also contain a node label called `contextNodeLabel`, see xref:#fastpath-considerations-event-features[Event input features] below.


[[fastpath-considerations-timestamps]]
=== Defining event timestamps

There are two ways of specifying timestamps for event nodes.
The first way is to provide a `eventNodeTimeProperty`, in which case each event node must hold a property of that name representing a timestamp.

If however, a `nextRelationshipType` is provided, `eventNodeTimeProperty` does not have to be provided.
In that case, time stamps are generated in an intuitive way depicted in the picture below.

image:fastpath-pics/fastpath-timestamps.svg[Timestamp generation]

The length of the `nextRelationshipType` path to an event defines its timestamp.
The first event node in a base node's event chain, which is connected via a `firstRelationshipType` relationship from the base node, will have timestamp 0.
The next event node, accessed via a `nextRelationshipType` relationship from the first event node, will have timestamp 1, and so on.

You can still provide a `eventNodeTimeProperty` even if `nextRelationshipType` is used.
In that case, `nextRelationshipType` is not used to infer timestamps, but rather to determine which base node an event node belongs to.


[[fastpath-considerations-event-features]]
=== Event input features

An event's feature representation can be impacted by three different input sources.
They are independent of each other and can be used both together and separately.
The event feature vector is a sum over all input sources that are enabled.

1. To enable the _Context nodes_ input source you provide a `contextNodeLabel`.
In this case it is assumed that there may be outgoing relationships from event nodes to context nodes, i.e., the pattern: +
`(:eventNodeLabel)-[:]->(:contextNodeLabel)`
2. To enable the _Event feature vector properties_ input source you provide `eventNodeFeatureVectorProperty`.
This should be the name of a vector property present on all event nodes.
3. To enable the _Categorical event properties_ input source you provide `eventNodeCategoricalProperties`.
This should be the name of a property that holds integers representing categories or lists of such integers.
The property must be present on all event nodes.


[[fastpath-considerations-grid]]
=== Grid of random vectors

Event contributions to final embeddings are sourced from randomly generated vectors arranged in a grid.
The first dimension of this grid is time, containing a number of columns equal to `numTimeAnchors`, evenly distributed from 0 to `lookbackHorizon`.
Secondly, each categorical event property, each context node, and each position of the event feature space is assigned its own row in the grid.

Each cell in the grid is then assigned a randomly generated vector of size `dimension`.

An event's contribution to the final embedding is then an aggregation of vectors from rows matching the event information, and columns in the vicinity of the event _elapsed_ time. How many columns are considered is dependent on the `smoothingWindow`.


[[fastpath-considerations-smoothing]]
=== Time smoothing

If `smoothingRate` is large, only a small amount of smoothing is applied and events that are even a small time apart (enough to be closest to different grid points) will generally have very different embeddings.

If `smoothingWindow` is 0, the effect is similar to having a large `smoothingRate`.
On the other hand, if `smoothingWindow` is large in relation to `numTimeAnchors`, and simultaneously `smoothingRate` is small, identical events will have similar embeddings even when their timestamps differ a lot.


== Tuning parameters

In general, tuning parameters is very dependent on the specific dataset.


=== Embedding dimension

The `embeddingDimension` parameter controls the output dimension of the embeddings.
A larger dimension captures more information but increases memory and computation time.
A smaller dimension is faster but may encode the input features and event history insufficiently.


=== Time grid

`numTimeAnchors` defines the number of points in the time grid; the elapsed time from an event to the output time is rounded to this grid.
If set to `1`, timestamps of events have no effect.
`lookbackHorizon` is the maximum age of events, relative to the output time, that are considered for the embedding; older events are discarded.


=== Smoothing

`smoothingRate` controls how fast expected similarity of events decays as their time-distance increases.
`smoothingWindow` widens the aggregation window to up to `2*smoothingWindow + 1` grid times.
A large `smoothingWindow` combined with a small `smoothingRate` makes identical events similar even when their timestamps differ a lot.


=== Decay

`decayRate` controls the speed of decay of the influence of older events on the base node embedding.
A value of `0.0` means all relevant events contribute equally; larger values weigh more recent events more heavily.


[[algorithms-fastpath-syntax]]
== Syntax

This section covers the syntax used to execute the {algorithm} algorithm.

.FastPath syntax per mode
[.tabbed-example, caption = ]
====

[.include-with-stream]
======
.Run FastPath in stream mode on a named graph.
[source, cypher, role=noplay]
----
CALL gds.fastPath.stream(
  graphName: String,
  configuration: Map
) YIELD
  nodeId: Integer,
  embedding: Vector of FLOAT32
----

include::partial$/algorithms/common-configuration/common-parameters.adoc[]

.Configuration
[opts="header",cols="3,2,3m,2,8"]
|===
| Name          | Type   | Default | Optional | Description
include::partial$/machine-learning/node-embeddings/fastpath/specific-configuration.adoc[]
|===

.Results
[opts="header",cols="1m,1,6"]
|===
| Name      | Type                        | Description
| nodeId    | Integer                     | The Neo4j node ID.
| embedding | Vector of FLOAT32           | The computed FastPath node embedding
|===
======

[.include-with-mutate]
======
.Run FastPath in mutate mode on a graph stored in the catalog.
[source, cypher, role=noplay]
----
CALL gds.fastPath.mutate(
  graphName: String,
  configuration: Map
)
YIELD
  nodeCount: Integer,
  nodePropertiesWritten: Integer,
  preProcessingMillis: Integer,
  computeMillis: Integer,
  mutateMillis: Integer,
  configuration: Map
----

include::partial$/algorithms/common-configuration/common-parameters.adoc[]

.Configuration
[opts="header",cols="3,2,3m,2,8"]
|===
| Name          | Type   | Default | Optional | Description
include::partial$/machine-learning/node-embeddings/fastpath/specific-configuration.adoc[]
| mutateProperty | String | n/a     | no       | The node property in the in-memory graph to which the embedding is written.
|===

.Results
[opts="header",cols="1,1,6"]
|===
| Name                  | Type    | Description
| nodeCount             | Integer | The number of nodes processed.
| nodePropertiesWritten | Integer | The number of node properties written.
| preProcessingMillis   | Integer | Milliseconds for preprocessing data.
| computeMillis         | Integer | Milliseconds for running the algorithm.
| mutateMillis          | Integer | Milliseconds for writing result data back to the projected graph.
| configuration         | Map     | The configuration used for running the algorithm.
|===
======

[.include-with-write]
======
.Run FastPath in write mode on a graph stored in the catalog.
[source, cypher, role=noplay]
----
CALL gds.fastPath.write(
  graphName: String,
  configuration: Map
)
YIELD
  nodeCount: Integer,
  nodePropertiesWritten: Integer,
  preProcessingMillis: Integer,
  computeMillis: Integer,
  writeMillis: Integer,
  configuration: Map
----

include::partial$/algorithms/common-configuration/common-parameters.adoc[]

.Configuration
[opts="header",cols="3,2,3m,2,8"]
|===
| Name              | Type    | Default                | Optional | Description
include::partial$/machine-learning/node-embeddings/fastpath/specific-configuration.adoc[]
| writeProperty     | String  | n/a                    | no       | The node property in the Neo4j database to which the embedding is written
| concurrency       | Integer | 4                      | yes      | The number of concurrent threads used for running the algorithm.
| writeConcurrency  | Integer | value of 'concurrency' | yes      | The number of concurrent threads used for writing the result to Neo4j.
|===

.Results
[opts="header",cols="1,1,6"]
|===
| Name                  | Type    | Description
| nodeCount             | Integer | The number of nodes processed.
| nodePropertiesWritten | Integer | The number of node properties written.
| preProcessingMillis   | Integer | Milliseconds for preprocessing data.
| computeMillis         | Integer | Milliseconds for running the algorithm.
| writeMillis           | Integer | Milliseconds for writing result data back to Neo4j.
| configuration         | Map     | The configuration used for running the algorithm.
|===
======
====


[[algorithms-fastpath-examples]]
== Examples

include::partial$/algorithms/shared/examples-named-native-note.adoc[]

:algorithm-name: {algorithm}

In this example we use a small graph of medical patient records.
`Patient` nodes are the base nodes and carry an `observation_time` property.
`Encounter` nodes are the event nodes and carry an `emb` feature vector and a `days` time property.
`HAS_ENCOUNTER` relationships connect each patient to their encounters.

Because FastPath is only available in Aura Graph Analytics, the graph must be projected into a GDS Session.
This is done by passing the `memory` parameter (and optionally `sessionId`) to xref:management-ops/graph-creation/graph-project-cypher-projection.adoc[`gds.graph.project`], which creates a GDS Session for the projected graph.

.Database setup
[source, cypher, role=noplay setup-query]
----
CREATE
  (p0:Patient {observation_time: 100}),
  (p1:Patient {observation_time: 200}),
  (e0:Encounter {emb: [0.1, 0.2, 0.3], days: 10}),
  (e1:Encounter {emb: [0.4, 0.5, 0.6], days: 50}),
  (e2:Encounter {emb: [0.7, 0.8, 0.9], days: 80}),
  (p0)-[:HAS_ENCOUNTER]->(e0),
  (p0)-[:HAS_ENCOUNTER]->(e1),
  (p1)-[:HAS_ENCOUNTER]->(e2)
----

.Graph projection into a GDS Session
[source, cypher, role=noplay graph-project-query]
----
MATCH (source:Patient)
OPTIONAL MATCH (source)-[r:HAS_ENCOUNTER]->(target:Encounter)
RETURN gds.graph.project(
  'patients',
  source,
  target,
  {
    sourceNodeLabels: ['Patient'],
    sourceNodeProperties: source { .observation_time },
    targetNodeLabels: ['Encounter'],
    targetNodeProperties: target { .emb, .days },
    relationshipType: 'HAS_ENCOUNTER'
  },
  { memory: '2GB' }
)
----

=== Stream mode

.Stream node embeddings
[source, cypher, role=query-example]
----
CALL gds.fastPath.stream('patients', {
  baseNodeLabel: 'Patient',
  eventNodeLabel: 'Encounter',
  eventNodeFeatureVectorProperty: 'emb',
  baseNodeObservationTimeProperty: 'observation_time',
  eventNodeTimeProperty: 'days',
  embeddingDimension: 32, // in reality, a higher value is recommended
  numTimeAnchors: 30,
  lookbackHorizon: 3650,
  smoothingRate: 0.9,
  smoothingWindow: 2,
  decayRate: 0.0
}) YIELD nodeId, embedding
RETURN nodeId, embedding
----

The stream procedure returns one row per base node.

=== Mutate mode

.Mutate node embeddings into the in-memory graph
[source, cypher, role=query-example]
----
CALL gds.fastPath.mutate('patients', {
  baseNodeLabel: 'Patient',
  eventNodeLabel: 'Encounter',
  eventNodeFeatureVectorProperty: 'emb',
  baseNodeObservationTimeProperty: 'observation_time',
  eventNodeTimeProperty: 'days',
  embeddingDimension: 32, // in reality, a higher value is recommended
  numTimeAnchors: 30,
  lookbackHorizon: 3650,
  mutateProperty: 'fastPathEmbedding'
}) YIELD nodeCount, nodePropertiesWritten, preProcessingMillis, computeMillis, mutateMillis
RETURN nodeCount, nodePropertiesWritten, preProcessingMillis, computeMillis, mutateMillis
----

=== Write mode

.Write node embeddings back to Neo4j
[source, cypher, role=query-example]
----
CALL gds.fastPath.write('patients', {
  baseNodeLabel: 'Patient',
  eventNodeLabel: 'Encounter',
  eventNodeFeatureVectorProperty: 'emb',
  baseNodeObservationTimeProperty: 'observation_time',
  eventNodeTimeProperty: 'days',
  embeddingDimension: 32, // in reality, a higher value is recommended
  numTimeAnchors: 30,
  lookbackHorizon: 3650,
  writeProperty: 'fastPathEmbedding'
}) YIELD nodeCount, nodePropertiesWritten, preProcessingMillis, computeMillis, writeMillis
RETURN nodeCount, nodePropertiesWritten, preProcessingMillis, computeMillis, writeMillis
----

The `fastPathEmbedding` property is written back to Neo4j as a native vector property and can be indexed with a vector index for downstream similarity search.


[[algorithms-fastpath-theory]]
== How the algorithm works

The following sections provide more detailed information about FastPath for those interested in the inner workings of the algorithm.

The breakdown of the algorithm into steps below is conceptual.
It does not reflect the actual implementation details such as the order of loops, data structures and more.
We describe how to compute the FastPath embedding for a base node `b` which has output time `t~o~`.
The output time is computed according to one of the chosen parameters `observationTime` or `baseNodeObservationTimeProperty`.
An arbitrary event which belongs to `b` is denoted by `e`, and its time stamp is assumed to be `t~e~`.
At the time `t~o~`, at which we wish to compute the embedding of `b`, the _elapsed time_ of `e` is +
`t~el~ = t~o~ - t~e~`,
that is, the amount of time between the timestamp of the event and the output time of the corresponding base node.

Note that events may belong to multiple base nodes which have different output times.
This implies that some computations involving an event have to be recomputed for each of its associated base nodes, but these computations are independent of each other.

. *Preprocess* +
Pre-process the input into a graph with base nodes, event nodes and optionally context nodes.
Base and event nodes are connected and so are events and context nodes.
If time stamps are not given for events, time stamps are generated by traversing xref:#fastpath-considerations-graph-schema[event chains] per base node.
. *Filter relevant events* +
Out of the events that belong to the base node `b`, any event which has elapsed time exceeding `lookbackHorizon`, or any event which occurred at time `t~o~` or later, is removed.
The remaining relevant events for `b` are called `E(b)`.
. *Create grid* +
Create a grid over time, subsequently referred to as the grid.
. *Generate random vectors* +
Sparse random vectors are generated independently per _input source_ below, if they are selected. +
For each time in the grid and input source, generate vectors as follows:
a. _Event feature vector properties_: a vector `r~i,t~` is generated for each dimension `i` of the input event feature vectors image:fastpath-pics/thegrid.svg[TheGrid,350,350,role=right,text-center]
b. _Context nodes_: for each context node `c`, generate `r~c,t~`
c. _Categorical event properties_: for each categorical node property `prop` and for each value `v` of that property, initialize a random vector `r~prop,v,t~`. +
If the property value for any event is a list of categories `[v~1~, v~2~, ...]`, and `v` is any of these values, we initialize a random vector `r~prop,v`.
. *Compute event node pre-embeddings* +
The pre-embedding for an event `e` at time `t` is denoted by `x~e,t~` and initialized to all zeros.
For all input sources below that apply, weighted sums of random vectors generated in step 4 are added to `x~e,t~`:
a. _Event feature vector properties_: +
`x~e,t~ += ∑~i~ r~i,t~ * inp~i~` +
where `inp` is the input vector of `e` and `i` ranges over the dimensions of `inp`.
b. _Context nodes_: +
`x~e,t~ += ∑~c~ r~c,t~` +
where `c` ranges over all neighbors of the event `e`.
c. _Categorical event properties_: +
`x~e,t~ += ∑~prop~ r~prop,e.prop,t~` +
where `prop` ranges over all selected categorical event properties. +
Or when `e.prop` is a list:
`x~e,t~ = ∑~prop~ ∑~v{sp}in{sp}e.prop~ r~prop,v,t~`
. *Compute event embeddings* +
image:fastpath-pics/thegrid_computation.svg[Image2,450,450] +
We compute an embedding for `e` using its earlier derived pre-embeddings at different times.
We find the time `t~cl~` in the grid which is the closest to the elapsed time `t~el~ = t~o~ - t~e~`.
Then adding up to `smoothingWindow` points in the grid on both sides of `t~cl~`, we obtain a window `W~e~` of relevant grid times for the event.
In the picture, `smoothingWindow = 1` and `t~cl~=t~4~`, therefore `W~e~ = {t~3~,t~4~,t~5~}`.
For each `t` in `W~e~` we set the weight of the grid point `t` to be, +
`w(t) = exp(-|t - t~el~| * smoothingRate ) / Z~e~`, +
where `Z~e~` is the constant that ensures `∑~t{sp}in{sp}W_e~ w(t) = 1`. +
The embedding of the event at output time `t~o~` is then +
`emb(e|t~o~) = ∑~t{sp}in{sp}W_e~ w(t) * x~e,t~`. +
This constructs time-smoothed embeddings by taking an average of a grid of pre-embeddings, or basis vectors.
The purpose of the time-smoothing mechanism is to ensure that embeddings change continuously with respect to changes in elapsed time, all other factors being equal.
. *Compute base node embeddings* +
The embedding for `b` is finally given by +
`emb(_b_) = ∑~e{sp}in{sp}E(b)~ w~b,e~ * emb(e)` +
where +
`w~b,e~ = exp(-decayRate * (t~o~ - t~e~))` and `E(b)` was defined in step 2.

The figure below gives an overview of what influences event embeddings and how they flow to the embedding of a base node, based on the output time and elapsed times.

image::fastpath-pics/base-event.svg[]

[[algorithms-fastpath-pipelines]]
== Pipelines

[NOTE]
====
FastPath is *not* supported as a node property step in training pipelines (Node Classification,
Node Regression, or Link Prediction). It can only be run as a standalone algorithm
(`gds.fastPath.stream` / `mutate` / `write`).
====
