[.enterprise-edition]
[[cluster]]
= GDS with Neo4j Causal Cluster

[abstract]
--
This section describes how the Neo4j Graph Data Science library can be used in a Neo4j Causal Cluster deployment.
--

It is possible to run GDS as part of Neo4j Causal Cluster deployment.
Since GDS performs large computations with the full resources of the system it is not suitable to run as part of the cluster's core.
We make use of a _Read Replica_ instance to deploy the GDS library and process analytical workloads.
Calls to GDS `write` procedures are internally directed to the cluster `LEADER` instance via _server-side routing_.

[NOTE]
====
GDS on Clusters works on **Neo4j 4.3+**.
There is no intention to support earlier versions of the database.
====


== Deployment

* The cluster must contain at least one _Read Replica_ instance
** single _Core member_ and a _Read Replica_ is a valid scenario.
** GDS workloads are not load-balanced if there are more than one _Read Replica_ instances.
* Cluster should be configured to use _server-side routing_.
* GDS plugin deployed on the _Read Replica_.
** A valid GDS Enterprise Edition license must be installed and configured on the _Read Replica_.
** The driver connection to operated GDS should be made using the `bolt://` protocol, or _server-policy routed_ to the _Read Replica_ instance.

For more information on setting up, configuring and managing a Neo4j Causal Clustering, please refer to https://neo4j.com/docs/operations-manual/current/clustering/[the documentation].

== GDS Configuration

The following optional https://neo4j.com/docs/operations-manual/current/configuration/dynamic-settings/[dynamic settings] can be used to control transaction size.

[opts="header"]
|===
| Property                  | Default Value
| `gds.cluster.tx.min.size` | 10000
| `gds.cluster.tx.max.size` | 100000
|===

The batch size for writing node properties is computed using both values along with the configured concurrency and total node count.
The batch size for writing relationship is using the lower value of the two settings.
There are some procedures that support batch size configuration which takes precedence if present in procedure call parameters.
