[[python-client-algorithms]]
= Running algorithms

include::python-client-gds-object.adoc[]

Running most algorithms with the Python client is structurally similar to using the Cypher API:

include::python-client-syntax.adoc[]

Here we can note a few key differences:

* Instead of a graph name string as first argument, we have a <<python-client-graph-object, graph object>> as first positional argument.
* Instead of a configuration map, we have named keyword arguments.

The result of running a procedure is always returned as a `list[dict[str, any]]`, similar to using the Python driver itself.

For example, to run the WCC and FastRP algorithms on a graph `G`, we could do the following:

[source,python]
----
G = gds.graph.project(...)

wcc_res = gds.wcc.mutate(
    G,                          #  Graph object
    threshold=0.8,              #  Configuration parameters
    mutateProperty="wcc"
)
assert wcc_res[0]["componentCount"] > 0

fastrp_res = gds.fastRP.write(
    G,                          #  Graph object
    featureProperties=["wcc"],  #  Configuration parameters
    embeddingDimension=256,
    propertyRatio=0.3,
    writeProperty="embedding"
)
assert fastrp_res[0]["nodePropertiesWritten"] == G.node_count()
----

Some algorithms deviate from the standard syntactic structure.
We describe how to use them in the Python client in the sections below.


== Algorithms that require node matching

Some algorithms take (database) node ids as inputs.
These node ids must be matched directly from the Neo4j database.
This is straight-forward when working in Cypher.
In the Python client there is a convenience method `gds.find_node_id` to retrieve a node id based on node labels and property key-value pairs.

For example, to find a source and target node of a graph `G` with cities to run <<algorithms-dijkstra-source-target>> on, we could do the following:

[source,python]
----
source_id = gds.find_node_id(["City"], {"name": "New York"})
target_id = gds.find_node_id(["City"], {"name": "Philadelphia"})

res = gds.shortestPath.dijkstra.stream(G, sourceNode=source_id, targetNode=target_id)
assert res[0]["totalCost"] == 100
----

`gds.find_node_id` takes a list of node labels and a dictionary of node property key-value pairs.
The nodes found are those that have all labels specified and fully match all property key-value pairs given.
Note that exactly one node per method call must be matched, otherwise an error will be raised.

=== Cypher mapping

The Python call:

[source,python]
----
gds.find_node_id(["A", "B"], {"p1": 1, "p2": "foo"})
----

is exactly equivalent to the Cypher statement:

[source,cypher]
----
MATCH (n:A:B {p1: 1, p2: 'foo'})
RETURN id(n) AS id
----

To do more advanced matching beyond the capabilities of `find_node_id()` we recommend using Cypher's `MATCH` via `gds.run_cypher`.


== Topological link prediction

The methods for doing <<algorithms-linkprediction>> are a bit different.
Just like in the GDS procedure API they do not take a graph as an argument, but rather two node references as positional arguments.
And they simply return the similarity score of the prediction just made as a float - not a list of dictionaries.

For example, to run the Adamic Adar algorithm, we can use the following:

[source,python]
----
node1 = gds.find_node_id(["User"], {"name": "Mats"})
node2 = gds.find_node_id(["User"], {"name": "Adam"})

score = gds.alpha.linkprediction.adamicAdar(node1, node2)
assert score >= 0
----
