[[python-client-installation]]
= Installation

To install the latest deployed version of the Python client, run:

[source,bash]
----
pip install graphdatascience
----

[[python-client-system-requirements]]
== System requirements

The GDS Python client depends on Python, the Neo4j Python Driver, and a server-side installation of the GDS library (see <<installation>>).
The Python client supports the following versions of the other three components:

[opts=header]
|===
| Python Client | GDS version  | Python version | Neo4j Python Driver version
.4+<.^| `0.1.0`
.4+<.^| `2.0`
.4+<.^| `3.6+`
| `4.1`
| `4.2`
| `4.3`
| `4.4`
|===


== Versioning

To make things easy for users of the Python client, our aim is that running `pip install --upgrade graphdatascience` should give you a version of the client that supports all <<supported-neo4j-versions, currently supported GDS library versions>>, starting with 2.0.

The Python client follows https://semver.org/[semantic versioning].

Python client versions do not map identically to versions of the GDS library.
Eg. Python client version X.0 must not necessarily be compatible with GDS library version X.0.
Instead, the Python client may be released independently and one has to consult <<python-client-system-requirements>> above to figure out whether one's client version is compatible with the GDS library on the server.