[[graph-catalog-ops]]
= Graph Catalog

Graph algorithms run on a graph data model which is a _projection_ of the Neo4j property graph data model.
A graph projection can be seen as a view over the stored graph, containing only analytical relevant, potentially aggregated, topological and property information.
Graph projections are stored entirely in-memory using compressed data structures optimized for topology and property lookup operations.

The graph catalog is a concept within the GDS library that allows managing multiple graph projections by name.
Using that name, a graph can be used in multiple times in the analytical workflow.
Named graphs can be created using either the <<label-relationship-type-projection, Store projection>> or the <<cypher-projection, Cypher projection>>.
After usage, named graphs can be removed from the catalog to free up main memory.

The graph catalog exists as long as the Neo4j instance is running.
When Neo4j is restarted, graphs stored in the catalog are lost and need to be re-created.

This chapter explains the available graph catalog operations.

[[table-proc]]
[opts=header,cols="1m,1m"]
|===
| Name                                              | Description
| <<catalog-graph-create, gds.graph.create>>        | Creates a graph in the catalog using a <<label-relationship-type-projection, Store projection>>.
| <<catalog-graph-create, gds.graph.create.cypher>> | Creates a graph in the catalog using a <<cypher-projection, Cypher projection>>.
| <<catalog-graph-list, gds.graph.list>>            | Prints information about a single graph or all graphs that are currently stored in the catalog.
| <<catalog-graph-drop, gds.graph.drop>>            | Removes a single graph from the catalog.
|===

[NOTE]
----
Creating, using, listing, and dropping named graphs are user-related management operations.
Graphs created by a different Neo4j user are not accessible at any time.
----


[[catalog-graph-create]]
== Creating graphs in the catalog

A projected graph can be stored in the catalog under a user-defined name.
Using that name, the graph can be referred to by any algorithm in the library.
This allows us to run multiple algorithms without creating the graph on each algorithm run.

There are two options of projecting a graph from the Neo4j database into main memory:

* <<label-relationship-type-projection>>
** Provides the best performance by reading from the Neo4j store files.
   Recommended to be used during the production phase.
* <<cypher-projection>>
** The more flexible, expressive approach with lesser focus on performance.
   Recommended to be used during the development phase.

In this section, we will give brief examples on how to create a graph using both options.
For detailed about information about the configuration of each projection, we prefer to the specific sections.

In the following two examples we want to create a graph projection that contains `Person` nodes and `LIKES` relationships.

.Create a graph using the Store projection:
[source,cypher]
----
CALL gds.graph.create(
    'my-store-graph',
    'Label',
    'REL_TYPE'
)
YIELD graphName, nodeCount, relationshipCount, createMillis;
----

.Create a graph using the Cypher projection:
[source,cypher]
----
CALL gds.graph.create.cypher(
    'my-cypher-graph',
    'MATCH (n:Person) RETURN id(n) AS id',
    'MATCH (a:Person)-[:LIKES]->(b:Person) RETURN id(a) AS source, id(b) AS target'
)
YIELD graphName, nodeCount, relationshipCount, createMillis;
----

After creating the graphs in the catalog, we can refer to them in algorithms by using their name.

.Run Page Rank on one of our created graphs:
[source,cypher]
----
CALL gds.algo.pageRank.stream('my-store-graph') YIELD nodeId, score;
----


[[catalog-graph-list]]
== Listing graphs in the catalog

Once we have created graphs in the catalog, we can list information about either all of them or a single graph using its name.

.List information about all graphs in the catalog:
[source,cypher]
----
CALL gds.graph.list()
YIELD graphName, nodeCount, relationshipCount;
----

.List information about a specific graph in the catalog:
[source,cypher]
----
CALL gds.graph.list('my-cypher-graph')
YIELD graphName, nodeQuery, relationshipQuery, nodeCount, relationshipCount;
----

The information contains basic statistics about the graph, e.g., the node and relationship count.
The procedure can also compute information about degree distributions, i.e., the number of relationships per node.
By default, the distribution values are not computed.

.List information about the degree distribution of a specific graph:
[source,cypher]
----
CALL gds.graph.list('my-cypher-graph')
YIELD graphName, degreeDistribution;
----


[[catalog-graph-drop]]
== Removing graphs from the catalog

Once we've finished using the named graph we can remove it from the catalog to free up memory.

.Remove a graph from the catalog:
[source,cypher]
----
CALL gds.graph.drop('my-store-graph') YIELD graphName;
----


