[[graph-catalog-ops]]
= Graph Catalog

Graph algorithms run on a graph data model which is a _projection_ of the Neo4j property graph data model.
A graph projection can be seen as a view over the stored graph, containing only analytical relevant, potentially aggregated, topological and property information.
Graph projections are stored entirely in-memory using compressed data structures optimized for topology and property lookup operations.

The graph catalog is a concept within the GDS library that allows managing multiple graph projections by name.
Using that name, a created graph can be used many times in the analytical workflow.
Named graphs can be created using either a <<native-projection, Native projection>> or a <<cypher-projection, Cypher projection>>.
After usage, named graphs can be removed from the catalog to free up main memory.

Graphs can also be created when running an algorithm without placing them in the catalog.
We refer to such graphs as <<anonymous-graph, Anonymous graphs>>.

[NOTE]
====
The graph catalog exists as long as the Neo4j instance is running.
When Neo4j is restarted, graphs stored in the catalog are lost and need to be re-created.
====

This chapter explains the available graph catalog operations.

[[table-proc]]
[opts=header,cols="1m,1"]
|===
| Name                                                                   | Description
| <<catalog-graph-create, gds.graph.create>>                             | Creates a graph in the catalog using a <<native-projection, Native projection>>.
| <<catalog-graph-create, gds.graph.create.cypher>>                      | Creates a graph in the catalog using a <<cypher-projection, Cypher projection>>.
| <<catalog-graph-list, gds.graph.list>>                                 | Prints information about graphs that are currently stored in the catalog.
| <<catalog-graph-exists, gds.graph.exists>>                             | Checks if a named graph is stored in the catalog.
| <<catalog-graph-drop, gds.graph.drop>>                                 | Removes a named graph from the catalog.
| <<catalog-graph-write-node-properties, gds.graph.writeNodeProperties>> | Writes node properties stored in a named graph to Neo4j.
| <<catalog-graph-write-relationship, gds.graph.writeRelationship>>      | Writes relationships stored in a named graph to Neo4j.
|===

[NOTE]
====
Creating, using, listing, and dropping named graphs are management operations bound to a Neo4j user.
Graphs created by a different Neo4j user are not accessible at any time.
====


[[catalog-graph-create]]
== Creating graphs in the catalog

A projected graph can be stored in the catalog under a user-defined name.
Using that name, the graph can be referred to by any algorithm in the library.
This allows multiple algorithms to use the same graph without having to re-create it on each algorithm run.

There are two variants of projecting a graph from the Neo4j database into main memory:

* <<native-projection, Native projection>>
** Provides the best performance by reading from the Neo4j store files.
   Recommended to be used during both the development and the production phase.
* <<cypher-projection, Cypher projection>>
** The more flexible, expressive approach with lesser focus on performance.
   Recommended to be primarily used during the development phase.

In this section, we will give brief examples on how to create a graph using either variant.
For detailed information about the configuration of each variant, we refer to the dedicated sections.

In the following two examples we show how to create a graph called `my-native-graph` that contains `Person` nodes and `LIKES` relationships.

.Create a graph using a native projection:
[source,cypher]
----
CALL gds.graph.create(
    'my-native-graph',
    'Person',
    'LIKES'
)
YIELD graphName, nodeCount, relationshipCount, createMillis;
----

We can also use Cypher to select the nodes and relationships to be projected into the in-memory graph.

.Create a graph using a Cypher projection:
[source,cypher]
----
CALL gds.graph.create.cypher(
    'my-cypher-graph',
    'MATCH (n:Person) RETURN id(n) AS id',
    'MATCH (a:Person)-[:LIKES]->(b:Person) RETURN id(a) AS source, id(b) AS target'
)
YIELD graphName, nodeCount, relationshipCount, createMillis;
----

After creating the graphs in the catalog, we can refer to them in algorithms by using their name.

.Run Page Rank on one of our created graphs:
[source,cypher]
----
CALL gds.algo.pageRank.stream('my-native-graph') YIELD nodeId, score;
----


[[catalog-graph-list]]
== Listing graphs in the catalog

Once we have created graphs in the catalog, we can list information about either all of them or a single graph using its name.

.List information about all graphs in the catalog:
[source,cypher]
----
CALL gds.graph.list()
YIELD graphName, nodeCount, relationshipCount;
----

.List information about a named graph in the catalog:
[source,cypher]
----
CALL gds.graph.list('my-cypher-graph')
YIELD graphName, nodeQuery, relationshipQuery, nodeCount, relationshipCount, creationTime, modificationTime;
----

The information contains basic statistics about the graph, e.g., the node and relationship count.
The result field `creationTime` indicates when the graph was created in memory.
The result field `modificationTime` indicates when the graph was updated by an algorithm running in `mutate` mode.
The procedure can also compute information about degree distributions, i.e., the number of relationships per node.
To skip computing the distribution values, use the `YIELD` subclause and omit the `degreeDistribution` column.

.List information about the degree distribution of a specific graph:
[source,cypher]
----
CALL gds.graph.list('my-cypher-graph')
YIELD graphName, degreeDistribution;
----


[[catalog-graph-exists]]
== Check if a graph exists in the catalog

We can check if a graph is stored in the catalog by looking up its name.

.Check if a graph exists in the catalog:
[source,cypher]
----
CALL gds.graph.exists('my-store-graph') YIELD exists;
----


[[catalog-graph-write-node-properties]]
== Write node properties to Neo4j

We can write node properties stored in a named in-memory graph back to Neo4j.
This is useful if we ran multiple algorithms in `mutate` mode and want to write back some or all of the results.
This is similar to what the `write` execution mode does, but allows more fine-grained control over the operations.

The properties to write are typically the `writeProperty` values that were used when running algorithms.
Properties that were added to the created graph at creation time will often already be present in the Neo4j database.

.Write multiple node properties to Neo4j:
[source,cypher]
----
CALL gds.graph.writeNodeProperties('my-graph', ['componentId', 'pageRank', 'communityId'])
----


[[catalog-graph-write-relationship]]
== Write relationships to Neo4j

We can write relationships stored in a named in-memory graph back to Neo4j.
This can be used to write algorithm results (for example from <<algorithms-node-similarity, Node Similarity>>) or relationships that have been aggregated during graph creation.

The relationships to write are specified by a relationship type.
This can either be an element identifier used in a relationship projection during graph construction or the `writeRelationshipType` used in algorithms that create relationships.

.Write relationships to Neo4j:
[source,cypher]
----
CALL gds.graph.writeRelationship('my-graph', 'SIMILAR_TO')
----

By default, no relationship properties will be written.
To write relationship properties, these have to be explicitly specified.

.Write relationships and their properties to Neo4j:
[source,cypher]
----
CALL gds.graph.writeRelationship('my-graph', 'SIMILAR_TO', 'similarityScore')
----


[[catalog-graph-drop]]
== Removing graphs from the catalog

Once we have finished using the named graph we can remove it from the catalog to free up memory.

.Remove a graph from the catalog:
[source,cypher]
----
CALL gds.graph.drop('my-store-graph') YIELD graphName;
----
