[[graph-catalog-ops]]
= Graph Catalog

Graph algorithms run on a graph data model which is a _projection_ of the Neo4j property graph data model.
A graph projection can be seen as a view over the stored graph, containing only the selected relevant topological and property information.
Graph projections are stored entirely in-memory using compressed data structures optimized for topology and property lookup operations.
The standard approach to create a graph is detailed in <<label-relationship-type-projection, Label and relationship-type projection>>.
It is also possible to use Cypher queries to project a more customised view of your graph.
The Cypher projection (see <<cypher-projection, Cypher projection>>) is more flexible but does not provide the same level of performance during graph creation.

Depending on the size of the projection, it can take some time to initialize the underlying data structures.
If such a large graph is used multiple times in the analytical workflow, it can be stored in the graph catalog.
Graphs from the graph catalog can then later be referenced by name when running algorithms.
Named graphs can be created using either the standard approach or Cypher queries.
After usage, named graphs can be removed from the catalog to free up main memory.

* <<label-relationship-type-projection>>
* <<named-graph>>
* <<cypher-projection>>

include::label-relationship-type-projection.adoc[leveloffset=+1]

include::cypher-projection.adoc[tag=overview,leveloffset=+1]

include::named-graph.adoc[leveloffset=+1]
