[[implicit-projection]]
= Implicit projection

[abstract]
--
This chapter explains how to create an unnamed graph for a single algorithm execution.
--

The typical workflow when using GDS is to create a graph and store it in the catalog.
This is useful to minimize reads from Neo4j and to run an algorithm with various settings or several algorithms on the same graph.

However if you want to quickly run a single algorithm and it can be convenient to use _implicit projection_.
The syntax is similar to the ordinary syntax for `gds.graph.create`.
However, the `nodeProjection` and `relationshipProjection` arguments are named and placed in the configuration map of the algorithm:

.Implicit native projection syntax
[source, cypher]
----
CALL gds.<algo>.<mode>(
  {
    nodeProjection: <nodeProj>,
    relationshipProjection: <relProj>,
    nodeProperties: <nodeProps>,
    relationshipProperties: <relProps>
    // algorithm and other create configuration
  }
)
----

The above syntax can be an alternative to the calls below:
[source, cypher]
----
CALL gds.graph.create(
  {
    'new-graph-name',
    <nodeProj>,
    <relProj>,
    {
      nodeProperties: <nodeProps>,
      relationshipProperties: <relProps>
      // other create configuration
    }
  }
);
CALL gds.<algo>.<mode>(
  'new-graph-name',
  {
    // algorithm configuration
  }
);
CALL gds.graph.drop('new-graph-name');
----

Similarly for Cypher projection, the explicit creation with `gds.graph.create.cypher` can be inlined in an algorithm call using the keys `nodeQuery` and `relationshipQuery`.

.Implicit cypher projection syntax
[source, cypher]
----
CALL gds.<algo>.<mode>({
  nodeQuery: <nodeQ>,
  relationshipQuery: <relQ>,
  // algorithm and other create configuration
})
----
