[[graph-catalog-ops]]
= Graph management
:description: This section details the graph catalog operations available to manage graphs within the Neo4j Graph Data Science library.

A _graph_ in GDS is an in-memory structure containing _nodes_ connected by _relationships_. Both nodes and relationships can hold numerical attributes (_properties_).
Graphs are stored using compressed data structures optimized for topology and property lookup operations.

Each graph has a name that can be used as a reference for management operations, or in analytical workflows that require the same graph to be processed several times. These references are stored in the _graph catalog_.


[NOTE]
====
The graph catalog exists as long as the Neo4j instance is running.
When Neo4j is restarted, graphs stored in the catalog are lost.
See xref:management-ops/backup-restore.adoc[] to learn how to persist your graph projections.
====

:sectnums!:

== Catalog operations

You can xref:management-ops/graph-creation/index.adoc[create] a graph in multiple ways, depending on whether the source data is in a Neo4j database, an external source, an existing GDS graph, or random data.

Once it has been created, a reference to the graph is stored in the graph catalog.
You can xref:management-ops/inspecting-the-graph-catalog.adoc[get information on graphs] to verify that the graph has been successfully created, and to retrieve a list of all the graphs in memory.

At any point, you can xref:graph-catalog-export-ops.adoc[export] a graph to a Neo4j database or to a CSV file.
You can also xref:management-ops/inspecting-the-graph-catalog.adoc[drop] a graph from the catalog when it is not longer useful.

// TODO [nvitucci] maybe not here
// TODO - reuse image from common usage but greying out the other components

== Graph operations

=== Read

The properties stored in the nodes and relationships of a graph can be retrieved using the `stream` methods on xref:graph-catalog-node-ops.adoc#catalog-graph-examples-stream[nodes properties] and xref:graph-catalog-relationship-ops.adoc#_stream[relationship properties] respectively. In the Enterprise Edition, similar operations can be performed more efficiently using xref:graph-catalog-apache-arrow-ops.adoc[Apache Arrow].

For complex use cases where an expressive query language is needed, you can run xref:management-ops/create-cypher-db.adoc[Cypher queries] on a graph.

=== Update

In-memory graphs are usually updated by algorithms running in `mutate` mode, which add new properties to nodes or relationships.

Besides, you can xref:graph-catalog-node-ops.adoc#catalog-graph-mutate-node-label-example[update node labels] and xref:graph-catalog-relationship-ops.adoc#catalog-graph-relationship-to-undirected-example[convert relationships] from directed to undirected. You can also _remove_ xref:graph-catalog-node-ops.adoc#catalog-graph-remove-node-properties-example[node properties] and xref:graph-catalog-relationship-ops.adoc#catalog-graph-delete-rel-type[relationships of a given type].

=== Write

In addition to exporting a whole graph, you can write xref:graph-catalog-node-ops.adoc#catalog-graph-write-node-properties-example[node properties], xref:graph-catalog-node-ops.adoc#catalog-graph-write-node-label-example[node labels], and xref:graph-catalog-relationship-ops.adoc#catalog-graph-write-relationship-example[relationships] back to Neo4j.

== Administration

=== Backup and restore

You can backup a graph so that it can be restored after dropping it by mistake, or after a database restart. See the xref:management-ops/backup-restore.adoc[] section for examples.

=== Access control

Catalog operations on named graphs are bound to a specific database user.
Graphs projected by a different database user are not accessible at any time, except for xref:management-ops/administration.adoc[administrator users].
