[[algorithms-dijkstra]]
= Dijkstra
:entity: source-target pair
:result: path
:algorithm: Dijkstra

[abstract]
--
This section describes the Dijkstra Shortest Path algorithms in the Neo4j Graph Data Science library.
--


[[algorithms-dijkstra-intro]]
== Introduction

The Dijkstra Shortest Path algorithm computes the shortest path between nodes.
The algorithm supports weighted graphs with positive relationship weights.
Dijkstra's algorithm can be configured in two ways:

. Find the shortest path between a source and a target node.
. Find the shortest paths between a single source node and all nodes reachable from that node.

The GDS implementation is based on the http://www-m3.ma.tum.de/twiki/pub/MN0506/WebHome/dijkstra.pdf[original description] and uses a binary heap as priority queue.
The implementation is also used for the <<algorithms-astar, A*>> and <<algorithms-yens, Yen's>> algorithms.
The algorithm implementation is executed using a single thread.
Altering the concurrency configuration has no effect.

See the following pages for further documentation:

* <<algorithms-dijkstra-source-target, Dijkstra Source-Target>>
* <<algorithms-dijkstra-single-source, Dijkstra Single-Source>>

include::dijkstra-source-target.adoc[leveloffset=+1]

include::dijkstra-single-source.adoc[leveloffset=+1]