plugins {
    id 'buildlogic-gds-java'
}

description = 'Neo4j Graph Data Science :: Subgraph Filtering'

group = 'org.neo4j.gds'

dependencies {
    annotationProcessor project(':annotations')

    compileOnly openGds.jetbrains.annotations
    compileOnly openGds.scala.library

    implementation project(':annotations')
    implementation project(':config-api')
    implementation project(':core')
    implementation project(':logging')
    implementation project(':graph-schema-api')
    implementation project(':memory-usage')
    implementation project(':progress-tracking')
    implementation project(':string-formatting')
    implementation project(':termination')

    implementation(openGds.opencypher.ccparser) {
        transitive = false
    }
    implementation(openGds.opencypher.astfactory) {
        transitive = false
    }

    testAnnotationProcessor project(':annotations')

    testImplementation openGds.jqwik
    testImplementation openGds.qaladatagen

    testImplementation project(':gdl-junit-extension')
    testImplementation project(':test-utils')
}
