[[algorithms-ml-models]]
= Machine Learning Models

[abstract]
--
This chapter provides explanations and examples for the supervised machine learning models in the Neo4j Graph Data Science library.
--

The machine learning procedures in Neo4j GDS allow you to make predictions about your graph by training supervised machine learning models.
These procedures can take node properties in your graph as inputs.
The node properties may be pre-existing in your database, or the results of graph algorithms or embeddings.
The process of splitting your data and building models is automated.
Only the best performing model according to the selected metric is retained.
Models can then be accessed via the <<model-catalog-ops, Model Catalog>> and used to make predictions about your graph.

The Neo4j GDS library includes the following machine learning models, grouped by quality tier:

* Alpha
** <<algorithms-ml-nodeclassification, Node Classification>>
** <<algorithms-ml-linkprediction, Link Prediction>>

include::alpha/nodeclassification/nodeclassification.adoc[leveloffset=+1]

include::alpha/linkprediction/linkprediction.adoc[leveloffset=+1]
