[[algorithms-syntax]]
= Syntax overview

The general algorithm syntax comes in two variants:

* Named graph variant
** The graph to operate over will be read from the graph catalog.
* Anonymous graph variant
** The graph to operate over will be created and deleted as part of the algorithm execution.

Each syntax variant additionally provides different execution modes.
There are three supported execution modes:

* `stream`
** Returns the result of the algorithm as a stream of records.
* `write`
** Writes the results of the algorithm to the Neo4j database and returns a single record of summary statistics.
* `stats`
** Returns a single record of summary statistics, but does not write to the Neo4j database.

Finally, an execution mode may be <<memory-estimation, estimated>> by appending the command with `estimate`.

[NOTE]
Only the production-quality tier guarantees availability of all execution modes.

Including all of the above mentioned elements leads to the following syntax outlines:

.Syntax composition for the named graph variant:
[source]
----
CALL gds[.<tier>].<algorithm>.<execution-mode>[.<estimate>](
  graphName: String,
  configuration: Map
)
----

.Syntax composition for the anonymous graph variant:
[source]
----
CALL gds[.<tier>].<algorithm>.<execution-mode>[.<estimate>](
  configuration: Map
)
----

The detailed sections in this chapter include concrete syntax overviews and examples.
