[[algorithms-pregel-api]]
= Pregel API

[abstract]
--
This chapter provides explanations and examples for using the Pregel API in the Neo4j Graph Data Science library.
--

[[algorithms-pregel-api-intro]]
== Introduction

Pregel is a vertex-centric computation model to define your own algorithms via a user-defined _compute_ function.
Node values can be updated within the compute function and represent the algorithm result.
The input graph contains default node values or node values from a graph projection.

The compute function is executed in multiple iterations, also called _super-steps_.
In each super-step the compute function is executed for each node in the graph.
Within that function, a node can receive messages from its neighbor nodes.
Based on the received messages and its currently stored value, a node can compute a new value.
A node can also send messages to all of its neighbors which are received in the next super-step.
The algorithm terminates after a fixed number of super-steps or if no messages are being sent between nodes.

A Pregel computation is executed in parallel.
Each thread executes the compute function for a batch of nodes.

For more information about Pregel, have a look at https://kowshik.github.io/JPregel/pregel_paper.pdf.

To implement your own Pregel algorithm, the Graph Data Science library provides a Java API, which is described below.

For an example on how to expose a custom Pregel computation via a Neo4j procedure, have a look at the https://github.com/neo-technology/graph-analytics/tree/master/public/examples/PregelK1Coloring[K1-Coloring example].


== Pregel API
.Initializing Pregel
[source, java]
----
package org.neo4j.graphalgo.beta.pregel;

public final class Pregel {
    // constructing an instance of Pregel
    public static Pregel withDefaultNodeValues(
        final Graph graph,
        final PregelConfig config,
        final PregelComputation computation,
        final int batchSize,
        final ExecutorService executor,
        final AllocationTracker tracker
    ) {...}

    // running the Pregel instance to get node values as result
    public HugeDoubleArray run(final int maxIterations) {...}
}
----

To build a PregelConfig you can use the `ImmutablePregelConfig.builder()`.

.Pregel Config
[opts="header",cols="1,1,1,6"]
|===
| Name                      | Type      | Default Value | Description
| initialNodeValue          | Double    | -1            | Initial value of the node in the Pregel context.
| isAsynchronous            | Boolean   | false         | Flag indicating if messages can be sent and received in the same super-step.
| relationshipWeightProperty| String    | null          | Name of the relationship property that represents weight.
| concurrency               | Integer   | 4             | Concurrency used when executing the Pregel computation.
|===

To implement your own algorithm, you need to implement the `PregelComputation` interface.

.The Pregel computation
[source, java]
----
@FunctionalInterface
public interface PregelComputation {
    // specifying the algorithm logic.
    void compute(PregelContext context, long nodeId, Queue<Double> messages);
    // how relationship weights should be applied on the message
    default double applyRelationshipWeight(double nodeValue, double relationshipWeight) { return nodeValue; }
}
----

The compute function takes a context, the node id for which the method is being executed for, and the messages that were sent to that node.
Using the context and the node id, one can access the current super-step, read and update the node value, send messages or vote to halt the computation.

.The Pregel context
[source, java]
----
public final class PregelContext {
    // nodes voting to halt will be inactive and accept no new messages
    public void voteToHalt(long nodeId) {...};
    // if its the first iteration
    public boolean isInitialSuperStep() {...};
    // get the number of the current iteration
    public int getSuperstep() {...};
    public double getNodeValue(long nodeId) {...};
    public void setNodeValue(long nodeId, double value) {...};
    // sending a message to the neighbours of a node
    public void sendMessages(long nodeId, double message) {...};
    public int getDegree(long nodeId) {...};
    // get the inital node value given by the PregelConfig
    public double getInitialNodeValue() {...};
}
----


[[algorithms-pregel-api-example]]
== Example

.The following provides an example of Pregel computation:
[source, java]
----
import org.neo4j.graphalgo.beta.pregel.PregelComputation;
import org.neo4j.graphalgo.beta.pregel.PregelContext;

import java.util.Queue;

public class ConnectedComponentsPregel implements PregelComputation {

   @Override
   public void compute(PregelContext context, long nodeId, Queue<Double> messages) {
        // get the current componentId for the node from the context
        // if we are on the first iteration, the value is the default value from the PregelConfig
        // which we do not use
        double oldComponentId = context.getNodeValue(nodeId);
        double newComponentId = oldComponentId;
        if (context.isInitialSuperStep()) {
            // In the first round, we use use the nodeId as component instead of the default -1
            newComponentId = nodeId;
        // need to check if there are any messages for this node
        } else if (messages != null && !messages.isEmpty()){
                // the componentId is updated to the smallest componentId of its neighbors including itself
                Double nextComponentId;
                while ((nextComponentId = messages.poll()) != null) {
                    if (nextComponentId.longValue() < newComponentId) {
                        newComponentId = nextComponentId.longValue();
                    }
                }
        }

        // update the node's componentId, both in the context and notify neighbors
        if (newComponentId != oldComponentId) {
            context.setNodeValue(nodeId, newComponentId);
            // send the new componentId to neighbors so that they also can be updated
            context.sendMessages(nodeId, newComponentId);
        }
   }
}
----

.The following runs Pregel, using `ConnectedComponentsPregel`
[source, java]
----
import org.neo4j.graphalgo.core.utils.paged.HugeDoubleArray;
import org.neo4j.graphalgo.core.concurrency.Pools;
import org.neo4j.graphalgo.core.utils.paged.AllocationTracker;
import org.neo4j.graphalgo.config.AlgoBaseConfig;

import org.neo4j.graphalgo.beta.pregel.ImmutablePregelConfig;
import org.neo4j.graphalgo.beta.pregel.Pregel;
import org.neo4j.graphalgo.beta.pregel.PregelConfig;
import org.neo4j.graphalgo.beta.generator.RandomGraphGenerator;


public class PregelExample {
    public static void main(String[] args) {
        int batchSize = 10;
        int maxIterations = 10;

        PregelConfig config = ImmutablePregelConfig.builder()
            .isAsynchronous(true)
            .build();

        // generate a random graph with 100 nodes and average degree 10
        HugeGraph graph = RandomGraphGenerator.builder()
            .nodeCount(100)
            .averageDegree(10)
            .relationshipDistribution(RelationshipDistribution.POWER_LAW)
            .allocationTracker(AllocationTracker.EMPTY)
            .build()
            .generate();

        Pregel pregelJob = Pregel.withDefaultNodeValues(
            graph,
            config,
            new ConnectedComponentsPregel(),
            batchSize,
            // run on the default GDS ExecutorService
            Pools.DEFAULT,
            // disable memory allocation tracking
            AllocationTracker.EMPTY
        );

        // the index in the nodeValues array is the nodeId from the graph
        HugeDoubleArray nodeValues = pregelJob.run(maxIterations);
        System.out.println(nodeValues.toString());
    }
}
----