[[algorithms-syntax]]
= Syntax overview

The general algorithm syntax comes in two variants:

* Named graph variant
** The graph to operate over will be read from the graph catalog.
* Anonymous graph variant
** The graph to operate over will be created and deleted as part of the algorithm execution.

Each syntax variant additionally provides different execution modes.
There are three supported execution modes:

* `stream`
** Returns the result of the algorithm as a stream of records.
* `write`
** Writes the results of the algorithm to the Neo4j database and returns a single record of summary statistics.
* `stats`
** Returns a single record of summary statistics, but does not write to the Neo4j database.

Finally, an execution mode may be <<memory-estimation, estimated>> by appending the command with `estimate`.

[NOTE]
Only the production-quality tier guarantees availability of all execution modes and estimation procedures.

Including all of the above mentioned elements leads to the following syntax outlines:

.Syntax composition for the named graph variant:
[source]
----
CALL gds[.<tier>].<algorithm>.<execution-mode>[.<estimate>](
  graphName: String,
  configuration: Map
)
----

.Syntax composition for the anonymous graph variant:
[source]
----
CALL gds[.<tier>].<algorithm>.<execution-mode>[.<estimate>](
  configuration: Map
)
----

The detailed sections in this chapter include concrete syntax overviews and examples.


[[algorithms-syntax-configuration-options]]
== Configuration options

All algorithms allow adjustment of their runtime characteristics through a set of configuration parameters.
Some of these parameters are algorithm specific, however, many of them are shared between the algorithms and execution modes.

[NOTE]
To learn more about algorithm specific parameters and to find out if an algorithm supports a certain parameter, please consult the algorithm specific documentation page.

.List of the most commonly accepted configuration parameters
concurrency - Integer::
Controls the parallelism with which the algorithm is executed.
By default this value is set to 4.
For more details on the concurrency settings and limitations please see <<system-requirements-cpu>> of the System Requirements.

relationshipTypes - String[]::
If the graph, on which the algorithm is run, was created with multiple relationship type projections, this parameter can be used to select only a subset of the projected types.
The algorithm will then only consider relationships with the selected types.

nodeWeightProperty - String::
In algorithms that support node weights this parameter defines the node property that contains the weights.

relationshipWeightProperty - String::
In algorithms that support relationship weights this parameter defines the relationship property that contains the weights.

maxIterations - Integer::
For iterative algorithms this parameter controls the maximum number of iterations.

tolerance - Float::
Many iterative algorithms accept the tolerance parameter.
It controls the minimum delta between two iterations.
If the delta is less than the tolerance value, the algorithm is considered converged and stops.

seedProperty - String::
Some algorithms can be calculated incrementally.
This means that results from a previous execution can be taken into account, even though the graph has changed.
The `seedProperty` parameter defines the node property that contains the seed value.
Seeding can speed up computation and write times.

writeProperty - String::
In `write` mode this parameter sets the name of the node or relationship property to which results are written.
If the property already exists, existing values will be overwritten.

writeConcurrency - Integer::
In `write` mode this parameter controls the parallelism of write operations.
The Default is `concurrency`
