[[algorithms-pregel-api]]
= Pregel API

[abstract]
--
This chapter provides explanations and examples for using the Pregel API in the Neo4j Graph Data Science library.
--

[[algorithms-pregel-api-intro]]
== Introduction

Pregel is a vertex-centric computation model to define your own algorithms via a `compute` function.
The computation model executes the algorithm in several iterations, also called `super-steps` in Pregel terminology.
Each node executes the same user-defined function, which process a list of messages and sends messages to its neighbours.
Currently, messages of type `double` are only allowed.
// TODO: on the slide it also states all nodes have to "vote to halt" but our implementation only checks for messages
The algorithms terminates if no messages where send in the last iteration.

For more information about Pregel, have a look at https://kowshik.github.io/JPregel/pregel_paper.pdf.


== Pregel Architecture
// TODO: does this concurrency allow arbitrary values? (enterprise feature?)
.Initializing Pregel
[source, java]
----
public static Pregel withDefaultNodeValues(
    final Graph graph,
    final PregelConfig config,
    final PregelComputation computation,
    final int batchSize,
    final int concurrency,
    final ExecutorService executor,
    final AllocationTracker tracker) {...}
----

To build PregelConfig you can use the `ImmutablePregelConfig.builder()`.

.Pregel Config
[opts="header",cols="1,1,1,6"]
|===
| Name                      | Type      | Default Value | Description
| intialNodeValue           | Double    | -1            | The initial value of the node in the pregel context.
| isAsynchronous            | Boolean   | false         | Flag indicating if multiple super-steps can be executed in parallel // TODO: validate
| relationshipWeightProperty| String    | null          | The name of the relationship property that represents weight.
|===

For implementing your own algorithm, you need implement the `PregelComputation` interface.

.The Pregel Computation
[source, java]
----
@FunctionalInterface
public interface PregelComputation {
    // specifying the algorithm logic.
    void compute(PregelContext context, long nodeId, Queue<Double> messages);
    // how relationship weights should be applied on the message
    default double applyRelationshipWeight(double nodeValue, double relationshipWeight) { return nodeValue; }
}
----



.The PregelContext
[source, java]
----
public final class PregelContext {
    // nodes voting to halt will be inactive and accept no new messages
    public void voteToHalt(long nodeId) {...};
    // if its the first iteration
    public boolean isInitialSuperStep() {...};
    // get the number of the current iteration
    public int getSuperstep() {...};
    public double getNodeValue(long nodeId) {...};
    public void setNodeValue(long nodeId, double value) {...};
    // sending a message to the neighbours of a node
    public void sendMessages(long nodeId, double message) {...};
    public int getDegree(long nodeId) {...};
    // get the inital node value given by the PregelConfig
    public double getInitialNodeValue() {...};
}
----



[[algorithms-pregel-api-example]]
== Example

.The following provides an example of Pregel computation:
[source, java]
----
import org.neo4j.graphalgo.beta.pregel.PregelComputation;
import org.neo4j.graphalgo.beta.pregel.PregelContext;

import java.util.Queue;

public class ConnectedComponentsPregel implements PregelComputation {

   @Override
   public void compute(PregelContext context, long nodeId, Queue<Double> messages) {
        double oldComponentId = context.getNodeValue(nodeId);
        double newComponentId = oldComponentId;
        if (context.isInitialSuperStep()) {
            // In the first round, every node uses its own id as the component id
            newComponentId = nodeId;
        } else if (messages != null && !messages.isEmpty()){
                Double nextComponentId;
                while ((nextComponentId = messages.poll()) != null) {
                    if (nextComponentId.longValue() < newComponentId) {
                        newComponentId = nextComponentId.longValue();
                    }
                }
        }

        if (newComponentId != oldComponentId) {
            context.setNodeValue(nodeId, newComponentId);
            context.sendMessages(nodeId, newComponentId);
        }
   }
}
----

.The following runs Pregel, using `ConnectedComponentsPregel`
[source, java]
----
import org.neo4j.graphalgo.core.utils.paged.HugeDoubleArray;
import org.neo4j.graphalgo.core.concurrency.Pools;
import org.neo4j.graphalgo.core.utils.paged.AllocationTracker;
import org.neo4j.graphalgo.config.AlgoBaseConfig;

import org.neo4j.graphalgo.beta.pregel.ImmutablePregelConfig;
import org.neo4j.graphalgo.beta.pregel.Pregel;
import org.neo4j.graphalgo.beta.pregel.PregelConfig;
import org.neo4j.graphalgo.beta.generator.RandomGraphGenerator;


public class PregelExample {
    public static void main() {
        int batchSize = 10;
        int maxIterations = 10;

        PregelConfig config = ImmutablePregelConfig.builder()
            .isAsynchronous(true)
            .build();

        Pregel pregelJob = Pregel.withDefaultNodeValues(
            RandomGraphGenerator.generate(10, 100),
            config,
            new ConnectedComponentsPregel(),
            batchSize,
            AlgoBaseConfig.DEFAULT_CONCURRENCY,
            Pools.DEFAULT,
            AllocationTracker.EMPTY
        );

        HugeDoubleArray nodeValues = pregelJob.run(maxIterations);
    }
}
----