[[algorithms-pregel-api]]
= Pregel API

[abstract]
--
This chapter provides explanations and examples for using the Pregel API in the Neo4j Graph Data Science library.
--

[[algorithms-pregel-api-intro]]
== Introduction

Pregel is a vertex-centric computation model to define your own algorithms via a `compute` function.
This is exposed through the Graph Data Science library as a Java API that enables you to implement your own algorithms.
//TODO: link to some other docs
The computation model executes the algorithm in several iterations, also called `super-steps` in Pregel terminology.
Each node executes the same user-defined function, which process a list of messages and sends messages to its neighbours.
Currently, messages of type `double` are only allowed.
Moreover, all pregel jobs, which run in their own thread, share a so called PregelContext in which the data for the current node is stored.
The algorithms terminates if no messages where send in the last iteration.

For more information about Pregel, have a look at https://kowshik.github.io/JPregel/pregel_paper.pdf.


== Pregel Architecture
// TODO: does this concurrency allow arbitrary values? (enterprise feature?)
.Initializing Pregel
[source, java]
----
package org.neo4j.graphalgo.beta.pregel;

public final class Pregel {
    // constructing an instance of Pregel
    public static Pregel withDefaultNodeValues(
        final Graph graph,
        final PregelConfig config,
        final PregelComputation computation,
        final int batchSize,
        final ExecutorService executor,
        final AllocationTracker tracker
    ) {...}

    // running the Pregel instance to get node values as result
    public HugeDoubleArray run(final int maxIterations) {...}
}
----

To build PregelConfig you can use the `ImmutablePregelConfig.builder()`.

.Pregel Config
[opts="header",cols="1,1,1,6"]
|===
| Name                      | Type      | Default Value | Description
| intialNodeValue           | Double    | -1            | The initial value of the node in the pregel context.
| isAsynchronous            | Boolean   | false         | Flag indicating if multiple super-steps can be executed in parallel
| relationshipWeightProperty| String    | null          | The name of the relationship property that represents weight.
| concurrency               | Integer   | 4             | The concurrency used when executing the pregel computation.
|===

For implementing your own algorithm, you need implement the `PregelComputation` interface.

.The Pregel Computation
[source, java]
----
@FunctionalInterface
public interface PregelComputation {
    // specifying the algorithm logic.
    void compute(PregelContext context, long nodeId, Queue<Double> messages);
    // how relationship weights should be applied on the message
    default double applyRelationshipWeight(double nodeValue, double relationshipWeight) { return nodeValue; }
}
----


The compute method of the Pregel class expects an instance of PregelContext.
In addition of being a holding the data for the current node, the PregelContext provides communication via messages as well as managing the iterations and halting.

.The PregelContext
[source, java]
----
public final class PregelContext {
    // nodes voting to halt will be inactive and accept no new messages
    public void voteToHalt(long nodeId) {...};
    // if its the first iteration
    public boolean isInitialSuperStep() {...};
    // get the number of the current iteration
    public int getSuperstep() {...};
    public double getNodeValue(long nodeId) {...};
    public void setNodeValue(long nodeId, double value) {...};
    // sending a message to the neighbours of a node
    public void sendMessages(long nodeId, double message) {...};
    public int getDegree(long nodeId) {...};
    // get the inital node value given by the PregelConfig
    public double getInitialNodeValue() {...};
}
----


[[algorithms-pregel-api-example]]
== Example

.The following provides an example of Pregel computation:
[source, java]
----
import org.neo4j.graphalgo.beta.pregel.PregelComputation;
import org.neo4j.graphalgo.beta.pregel.PregelContext;

import java.util.Queue;

public class ConnectedComponentsPregel implements PregelComputation {

   @Override
   public void compute(PregelContext context, long nodeId, Queue<Double> messages) {
        // get the current componentId for the node from the context
        // if we are on the first iteration, the value is the default value from the PregelConfig
        // which we do not use
        double oldComponentId = context.getNodeValue(nodeId);
        double newComponentId = oldComponentId;
        if (context.isInitialSuperStep()) {
            // In the first round, we use use the nodeId as component instead of the default -1
            newComponentId = nodeId;
        // need to check if there are any messages for this node
        } else if (messages != null && !messages.isEmpty()){
                // the componentId is updated to the smallest componentId of its neighbors including itself
                Double nextComponentId;
                while ((nextComponentId = messages.poll()) != null) {
                    if (nextComponentId.longValue() < newComponentId) {
                        newComponentId = nextComponentId.longValue();
                    }
                }
        }

        // update the node's componentId, both in the context and notify neighbors
        if (newComponentId != oldComponentId) {
            context.setNodeValue(nodeId, newComponentId);
            // send the new componentId to neighbors so that they also can be updated
            context.sendMessages(nodeId, newComponentId);
        }
   }
}
----

.The following runs Pregel, using `ConnectedComponentsPregel`
[source, java]
----
import org.neo4j.graphalgo.core.utils.paged.HugeDoubleArray;
import org.neo4j.graphalgo.core.concurrency.Pools;
import org.neo4j.graphalgo.core.utils.paged.AllocationTracker;
import org.neo4j.graphalgo.config.AlgoBaseConfig;

import org.neo4j.graphalgo.beta.pregel.ImmutablePregelConfig;
import org.neo4j.graphalgo.beta.pregel.Pregel;
import org.neo4j.graphalgo.beta.pregel.PregelConfig;
import org.neo4j.graphalgo.beta.generator.RandomGraphGenerator;


public class PregelExample {
    public static void main(String[] args) {
        int batchSize = 10;
        int maxIterations = 10;

        PregelConfig config = ImmutablePregelConfig.builder()
            .isAsynchronous(true)
            .build();

        Pregel pregelJob = Pregel.withDefaultNodeValues(
            // generate a random graph with 100 nodes and average degree 10
            RandomGraphGenerator.generate(100, 10),
            config,
            new ConnectedComponentsPregel(),
            batchSize,
            // run on the default GDS ExecutorService
            Pools.DEFAULT,
            // disable memory allocation tracking
            AllocationTracker.EMPTY
        );

        // the index in the nodeValues array is the nodeId from the graph
        HugeDoubleArray nodeValues = pregelJob.run(maxIterations);
        System.out.println(nodeValues.toString());
    }
}
----