[[algorithms-wcc]]
= Weakly Connected Components

[abstract]
--
This section describes the Weakly Connected Components (WCC) algorithm in the Neo4j Graph Data Science library.
--

This topic includes:

* <<algorithms-wcc-intro, Introduction>>
* <<algorithms-wcc-syntax, Syntax>>
* <<algorithms-wcc-examples, Examples>>
** <<algorithms-wcc-examples-unweighted, Unweighted>>
** <<algorithms-wcc-examples-weighted, Weighted>>
** <<algorithms-wcc-examples-seeding, Seeded components>>


[[algorithms-wcc-intro]]
== Introduction

The WCC algorithm finds sets of connected nodes in an undirected graph, where all nodes in the same set form a connected component.
WCC is often used early in an analysis to understand the structure of a graph.

WCC has previously been known as Union Find or Connected Components in this User Guide.

// TODO: something about use cases

For more information on this algorithm, see:

* http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.28.8405["An efficient domain-independent algorithm for detecting approximately duplicate database records"^].
* One study uses WCC to work out how well connected the network is, and then to see whether the connectivity remains if 'hub' or 'authority' nodes are moved from the graph: https://link.springer.com/article/10.1007%2Fs10115-003-0128-3["Characterizing and Mining Citation Graph of Computer Science Literature"^]

[NOTE]
====
Running this algorithm requires sufficient memory availability.
Before running this algorithm, we recommend that you read <<memory-estimation>>.
====


[[algorithms-wcc-syntax]]
== Syntax


== Write mode

.Run WCC in write mode on a graph stored in the catalog.
[source, cypher]
----
CALL gds.wcc.write(
  graphName: String,
  configuration: Map
)
YIELD
  // general write return columns
  componentCount: Integer,
  componentDistribution: Map
----

include::common-parameters-named-graph.adoc[]

include::common-configuration-named-graph.adoc[]

.Run WCC in write mode on an anonymous graph.
[source, cypher]
----
CALL gds.wcc.write(configuration: Map)
YIELD
  // general write return columns
  componentCount: Integer,
  componentDistribution: Map
----

include::common-parameters-anonymous-graph.adoc[]

include::common-configuration-anonymous-graph.adoc[]

.Algorithm specific configuration
[opts="header",cols="1,1,1m,1,4"]
|===
| Name                       | Type    | Default | Optional  | Description
| relationshipWeightProperty | String  | null    | yes       | The relationship property that contains the weight. If `null`, the graph is treated as unweighted. Must be numeric.
| defaultValue               | Float   | null    | yes       | The default value of the relationship weight in case it is missing or invalid.
| seedProperty               | String  | n/a     | yes       | Used to set the initial component for a node. The property value needs to be a number.
| threshold                  | Float   | null    | yes       | The value of the weight above which the relationship is considered in the computation.
| consecutiveIds             | Boolean | false   | yes       | Flag to decide whether component identifiers are mapped into a consecutive id space (requires additional memory).
|===

.Results
[opts="header",cols="1,1,6"]
|===
| Name                          | Type    | Description
| createMillis                  | Integer | Milliseconds for loading data.
| computeMillis                 | Integer | Milliseconds for running the algorithm.
| writeMillis                   | Integer | Milliseconds for writing result data back.
| postProcessingMillis          | Integer | Milliseconds for computing component count and distribution statistics.
| nodePropertiesWritten         | Integer | The number of node properties written.
| relationshipPropertiesWritten | Integer | The number of relationship properties written.
| componentCount                | Integer | The number of computed components.
| componentDistribution         | Map     | Map containing min, max, mean as well as p50, p75, p90, p95, p99 and p999 percentile values of component sizes.
| configuration                 | Map     | The configuration used for running the algorithm.
|===


[[algorithms-wcc-syntax-stream]]
== Stream mode

.Run WCC in stream mode on a graph stored in the catalog.
[source, cypher]
----
CALL gds.wcc.stream(
  graphName: String,
  configuration: Map
)
YIELD
  nodeId: Integer,
  componentId: Integer
----

include::common-parameters-named-graph.adoc[]

include::common-configuration-named-graph.adoc[]

.Run WCC in stream mode on an anonymous graph.
[source, cypher]
----
CALL gds.wcc.stream(configuration: Map)
YIELD
  nodeId: Integer,
  componentId: Integer
----

include::common-parameters-anonymous-graph.adoc[]

include::common-configuration-anonymous-graph.adoc[]

.Algorithm specific configuration
[opts="header",cols="1,1,1m,1,4"]
|===
| Name                       | Type    | Default | Optional | Description
| relationshipWeightProperty | String  | null    | yes      | The relationship property that contains the weight. If `null`, the graph is treated as unweighted. Must be numeric.
| defaultValue               | Float   | null    | yes      | The default value of the relationship weight in case it is missing or invalid.
| seedProperty               | String  | n/a     | yes      | Used to set the initial component for a node. The property value needs to be a number.
| threshold                  | Float   | null    | yes      | The value of the weight above which the relationship is considered in the computation.
| consecutiveIds             | Boolean | false   | yes      | Flag to decide whether component identifiers are mapped into a consecutive id space (requires additional memory).
|===

.Results
[opts="header",cols="1,1,6"]
|===
| Name        | Type    | Description
| nodeId      | Integer | The Neo4j node ID.
| componentId | Integer | The component ID.
|===


[[algorithms-wcc-examples]]
== Examples

Consider the graph created by the following Cypher statement:

[source, cypher, role=setup-query]
----
CREATE (nAlice:User {name: 'Alice'})
CREATE (nBridget:User {name: 'Bridget'})
CREATE (nCharles:User {name: 'Charles'})
CREATE (nDoug:User {name: 'Doug'})
CREATE (nMark:User {name: 'Mark'})
CREATE (nMichael:User {name: 'Michael'})

CREATE (nAlice)-[:LINK {weight: 0.5}]->(nBridget)
CREATE (nAlice)-[:LINK {weight: 4}]->(nCharles)
CREATE (nMark)-[:LINK {weight: 1.1}]->(nDoug)
CREATE (nMark)-[:LINK {weight: 2}]->(nMichael);
----

This graph has two connected components, each with three nodes.
The relationships that connect the nodes in each component have a property `weight` which determines the strength of the relationship.
In the following examples we will demonstrate using the Weakly Connected Components algorithm on this graph.

We can load this graph into the in-memory catalog.

[NOTE]
====
In the examples below we will use named graphs and standard projections as the norm.
However, <<cypher-projection, Cypher projection>> and anonymous graphs could also be used.
====

.The following statement will create the graph and store it in the graph catalog.
[source, cypher, role=setup-query]
----
CALL gds.graph.create(
    'myGraph',
    'User',
    'LINK',
    {
        relationshipProperties: 'weight'
    }
)
----

In the following examples we will demonstrate using the WCC algorithm on this graph.


[[algorithms-wcc-examples-unweighted]]
=== Unweighted

[role=query-example]
--
.The following will run the algorithm and stream results:
[source, cypher]
----
CALL gds.wcc.stream('myGraph')
YIELD nodeId, componentId
RETURN gds.util.asNode(nodeId).name AS name, componentId ORDER BY componentId, name
----

.Results
[opts="header",cols="1m,1m"]
|===
| name      | componentId
| "Alice"   | 0
| "Bridget" | 0
| "Charles" | 0
| "Doug"    | 3
| "Mark"    | 3
| "Michael" | 3
|===
--

To instead write the component ID to a node property in the Neo4j graph, use this query:

[role=query-example]
--
.The following will run the algorithm and write back results:
[source, cypher]
----
CALL gds.wcc.write('myGraph', { writeProperty: 'componentId' })
YIELD nodePropertiesWritten, componentCount;
----

.Results
[opts="header",cols="1m,1m"]
|===
| nodePropertiesWritten | componentCount
| 6                     | 2
|===
--

As we can see from the results, the nodes connected to one another are calculated by the algorithm as belonging to the same connected component.


[[algorithms-wcc-examples-weighted]]
=== Weighted

By configuring the algorithm to use a weight we can increase granularity in the way the algorithm calculates component assignment.
We do this by specifying the property key with the `relationshipWeightProperty` configuration parameter.
Additionally, we can specify a threshold for the weight value.
Then, only weights greater than the threshold value will be considered by the algorithm.
We do this by specifying the threshold value with the `threshold` configuration parameter.

If a relationship does not have a weight property, a default weight is used.
The default is zero, and can be configured to another value using the `defaultValue` configuration parameter.

[role=query-example]
--
.The following will run the algorithm and stream results:
[source, cypher]
----
CALL gds.wcc.stream('myGraph', { relationshipWeightProperty: 'weight', threshold: 1.0 })
YIELD nodeId, componentId
RETURN gds.util.asNode(nodeId).name AS Name, componentId AS ComponentId ORDER BY ComponentId, Name
----

.Results
[opts="header",cols="1m,1m"]
|===
| Name      | ComponentId
| "Alice"   | 0
| "Charles" | 0
| "Bridget" | 1
| "Doug"    | 3
| "Mark"    | 3
| "Michael" | 3
|===
--

[role=query-example]
--
.The following will run the algorithm and write back results:
[source, cypher]
----
CALL gds.wcc.write('myGraph', {
    writeProperty: 'componentId',
    relationshipWeightProperty: 'weight',
    threshold: 1.0
})
YIELD nodePropertiesWritten, componentCount;
----

.Results
[opts="header",cols="1m,1m"]
|===
| nodePropertiesWritten | componentCount
| 6                     | 3
|===
--

As we can see from the results, the node named 'Bridget' is now in its own component, due to its relationship weight being less than the configured threshold and thus ignored.


[[algorithms-wcc-examples-seeding]]
=== Seeded components

It is possible to define preliminary component IDs for nodes using the `seedProperty` configuration parameter.
This is helpful if we want to retain components from a previous run and it is known that no components have been split by removing relationships.
The property value needs to be a number.

The algorithm first checks if there is a seeded component ID assigned to the node.
If there is one, that component ID is used.
Otherwise, a new unique component ID is assigned to the node.

Once every node belongs to a component, the algorithm merges components of connected nodes.
When components are merged, the resulting component is always the one with the lower component ID.

[NOTE]
====
The algorithm assumes that nodes with the same seed value do in fact belong to the same component.
If any two nodes in different components have the same seed, behavior is undefined.
It is then recommended to run WCC without seeds.
====

To show this in practice, we will run the algorithm, then add another node to our graph, then run the algorithm again with the `seedProperty` configuration parameter.
We will use the weighted variant of WCC.

[role=query-example]
--
.The following will run the algorithm and write back results:
[source, cypher]
----
CALL gds.wcc.write('myGraph', {
    writeProperty: 'componentId',
    relationshipWeightProperty: 'weight',
    threshold: 1.0
})
YIELD nodePropertiesWritten, componentCount;
----

.Results
[opts="header",cols="1m,1m"]
|===
| nodePropertiesWritten | componentCount
| 6                     | 3
|===
--

[role=query-example]
--
.The following will create a new node in the Neo4j graph, with no component ID:
[source, cypher]
----
MATCH (b:User {name: 'Bridget'})
CREATE (b)-[:LINK {weight: 2.0}]->(new:User {name: 'Mats'})
----

.Results
[cols="1"]
|===
|No data returned.
|===
--

Note, that we can not use our already created graph as it does not contain the component id.
We will therefore create a second graph that contains the previously computed component id.

[role=query-example-no-result]
--
.The following will create a new graph containing the previously computed component id:
[source, cypher]
----
CALL gds.graph.create(
    'myGraph-seeded',
    'User',
    'LINK',
    {
        nodeProperties: 'componentId',
        relationshipProperties: 'weight'
    }
)
----
--

[role=query-example]
--
.The following will run the algorithm and stream results:
[source, cypher]
----
CALL gds.wcc.stream('myGraph-seeded', {
    seedProperty: 'componentId',
    relationshipWeightProperty: 'weight',
    threshold: 1.0
})
YIELD nodeId, componentId
RETURN gds.util.asNode(nodeId).name AS name, componentId ORDER BY componentId, name
----

.Results
[opts="header",cols="1m,1m"]
|===
| name      | componentId
| "Alice"   | 0
| "Charles" | 0
| "Bridget" | 1
| "Mats"    | 1
| "Doug"    | 3
| "Mark"    | 3
| "Michael" | 3
|===
--

[role=query-example]
--
.The following will run the algorithm and write back results:
[source, cypher]
----
CALL gds.wcc.write('myGraph-seeded', {
    seedProperty: 'componentId',
    writeProperty: 'componentId',
    relationshipWeightProperty: 'weight',
    threshold: 1.0
})
YIELD nodePropertiesWritten, componentCount;
----

.Results
[opts="header",cols="1m,1m"]
|===
| nodePropertiesWritten | componentCount
| 1                     | 3
|===
--

[NOTE]
====
If the `seedProperty` configuration parameter has the same value as `writeProperty`, the algorithm only writes properties for nodes where the component ID has changed.
If they differ, the algorithm writes properties for all nodes.
====
