[.beta]
[[catalog-model-drop]]
= Removing models

include::partial$/operations-reference/beta-note.adoc[]

If we no longer need a trained model and want to free up memory, we can remove the model from the catalog.


== Syntax

[.model-drop-syntax]
--
.Remove a model from the catalog:
[source, cypher, role=noplay]
----
CALL gds.beta.model.drop(modelName: String, failIfMissing: Boolean)
YIELD
    modelInfo: Map,
    trainConfig: Map,
    graphSchema: Map,
    loaded: Boolean,
    stored: Boolean,
    creationTime: DateTime,
    shared: Boolean
----

.Parameters
[opts="header",cols="1,1,1m,1,4"]
|===
| Name          | Type      | Default | Optional | Description
| modelName     | String    | n/a     | no       | The name of a model stored in the catalog.
| failIfMissing | Boolean   | true    | yes      | By default, the library will raise an error when trying to remove a non-existing model. When set to `false`, the procedure returns an empty result.
|===

include::partial$/machine-learning/model-catalog/shared/model-info-result.adoc[]
--


== Example

In this section we are going to demonstrate the usage of `gds.beta.model.drop`.
Assume we trained a model by running `train` on one of our xref:machine-learning/machine-learning.adoc[Machine learning algorithms].

[role=query-example]
--
.Remove a model from the catalog:
[source, cypher, role=noplay]
----
CALL gds.beta.model.drop('my-model')
YIELD modelInfo, loaded, shared, stored
RETURN modelInfo.modelName AS modelName, loaded, shared, stored
----

.Results
[opts="header",cols="1m,1m,1m,1m"]
|===
| modelName   | loaded  | shared | stored
| "my-model"  |  true   | false  | false
|===
--

In this example, the removed `my-model` was of the imaginary type `some-model-type`.
The model was loaded in-memory, but neither stored on disk nor published.

NOTE: If the model name does not exist, an error will be raised.
