[[catalog-model-drop]]
= Dropping models

If we no longer need a trained model and want to free up memory, we can drop the model from the catalog.


== Syntax

[.model-drop-syntax]
--
.Drop a model from the catalog:
[source, cypher, role=noplay]
----
CALL gds.model.drop(modelName: String, failIfMissing: Boolean)
YIELD
    modelInfo: Map,
    trainConfig: Map,
    graphSchema: Map,
    loaded: Boolean,
    stored: Boolean,
    creationTime: DateTime,
    published: Boolean
----

.Parameters
[opts="header",cols="1,1,1m,1,4"]
|===
| Name          | Type      | Default | Optional | Description
| modelName     | String    | n/a     | no       | Name of a model stored in the catalog.
| failIfMissing | Boolean   | true    | yes      | Whether an error should be raised when the model does not exist. When set to `false`, the procedure returns an empty result if the model does not exist.
|===

include::partial$/machine-learning/model-catalog/shared/model-info-result.adoc[]
--


== Example

In this section we are going to demonstrate the usage of `gds.model.drop`.
Assume we trained a model by running `train` on one of our xref:machine-learning/machine-learning.adoc[Machine learning algorithms].

[role=query-example]
--
.Drop a model from the catalog:
[source, cypher, role=noplay]
----
CALL gds.model.drop('my-model')
YIELD modelInfo, loaded, published, stored
RETURN modelInfo.modelName AS modelName, loaded, published, stored
----

.Results
[opts="header",cols="1m,1m,1m,1m"]
|===
| modelName   | loaded  | published | stored
| "my-model"  |  true   | false     | false
|===
--

In this example, the dropped model `my-model` loaded in-memory, but neither stored on disk nor published.
