[.enterprise-edition]
[[catalog-model-publish]]
= Publishing models

By default, a trained model is visible only to the user that created it.
Making a model accessible to other users can be achieved by publishing it.


== Syntax

[.model-publish-syntax]
--
.Publish a model from the catalog:
[source, cypher, role=noplay]
----
CALL gds.model.publish(modelName: String)
YIELD
    modelName: String,
    modelType: String,
    modelInfo: Map,
    creationTime: DateTime,
    trainConfig: Map,
    graphSchema: Map,
    loaded: Boolean,
    stored: Boolean,
    published: Boolean
----

.Parameters
[opts="header",cols="1,1,1m,1,4"]
|===
| Name          | Type   | Default | Optional | Description
| modelName     | String | n/a     | no       | The name of a model stored in the catalog.
|===


include::partial$/machine-learning/model-catalog/shared/model-info-result.adoc[]
--


== Examples

In this section we will illustrate how to publish a model.
A pre-requisite for this operation is that a model has already been trained and registered in the model catalog.
We will assume here that two models named `my-model1` and `my-model2` have already been trained and exist in the model catalog.
Our initial state can be inspected by listing all models in the catalog:

[role=query-example]
--
.Listing information about all models:
[source, cypher, role=noplay]
----
CALL gds.model.list()
YIELD modelName, modelType, modelInfo, loaded, stored, published
----

.Results
[opts="header",cols="1m,1m,1m,1m,1m,1m"]
|===
| modelName   | modelType            | modelInfo                       | loaded | stored | published
| "my-model1" | "example-model-type" | {exampleModelInfo="exampleValue"} | true   | false  | false
| "my-model2" | "example-model-type" | {number=42}                     | true   | false  | false
|===
--


=== Publishing a model

All we need to do is to run the procedure and specify the name of the model we want to publish.

[role=query-example]
--
.Publishing a trained model:
[source, cypher, role=noplay]
----
CALL gds.model.publish('my-model1')
YIELD modelName, modelType, modelInfo, loaded, stored, published
----

.Results
[opts="header"]
|===
| modelName          | modelType            | modelInfo                       | loaded | stored | published
| "my-model1_public" | "example-model-type" | {exampleModelInfo="exampleValue"} | true   | false  | true
|===
--

We can see that the model name is modified with the `_public` suffix.
When we now list the models in the catalog we can see that the published model has changed.

[role=query-example]
--
.Listing all models, including the published model:
[source, cypher, role=noplay]
----
CALL gds.model.list()
YIELD modelName, modelType, modelInfo, loaded, stored, published
RETURN modelName, modelType, modelInfo, loaded, stored, published
  ORDER BY modelName
----

.Results
[opts="header"]
|===
| modelName          | modelType            | modelInfo                       | loaded | stored | published
| "my-model1_public" | "example-model-type" | {exampleModelInfo="exampleValue"} | true   | false  | true
| "my-model2"        | "example-model-type" | {number=42}                     | true   | false  | false

|===
--

The published model is now accessible to all users.
