[.enterprise-edition.alpha]
[[model-catalog-store-ops]]
= Storing models on disk

include::partial$/operations-reference/alpha-note.adoc[]

The model catalog exists as long as the Neo4j instance is running.
When Neo4j is restarted, models are no longer available in the catalog and need to be trained again.
This can be prevented by storing a model on disk.

The location of the stored models can be configured via the configuration parameter `gds.model.store_location` in the `neo4j.conf`.
The location must be a directory and writable by the Neo4j process.

[NOTE]
====
The `gds.model.store_location` parameter must be configured for this feature.
====

[.alpha]
[[catalog-model-store]]
== Storing models from the catalog on disk

*Models that can be stored*

* xref:machine-learning/node-embeddings/graph-sage.adoc[GraphSAGE model]
* xref:machine-learning/node-property-prediction/nodeclassification-pipelines/node-classification.adoc[Node Classification model]
* xref:machine-learning/linkprediction-pipelines/link-prediction.adoc[Link Prediction model]

For xref:machine-learning/node-property-prediction/nodeclassification-pipelines/node-classification.adoc[Node Classification] and xref:machine-learning/linkprediction-pipelines/link-prediction.adoc[Link Prediction], storing a model is only supported for a subset of xref:machine-learning/training-methods/index.adoc[trainer-methods].
The trainer method of a model can be inspected in the `modelInfo` under `bestParameters`.

Currently, we only support xref:machine-learning/training-methods/logistic-regression.adoc[Logistic Regression]
and xref:machine-learning/training-methods/mlp.adoc[MLP].


=== Syntax

[.model-store-syntax]
--
.Remove a model from the catalog:
[source, cypher, role=noplay]
----
CALL gds.alpha.model.store(
    modelName: String,
    failIfUnsupported: Boolean
)
YIELD
    modelName: String,
    storeMillis: Integer
----

.Parameters
[opts="header",cols="1,1,1m,1,4"]
|===
| Name                      | Type    | Default | Optional | Description
| modelName                 | String  | n/a     | no       | The name of a model.
| failIfUnsupported         | Boolean | true    | yes      | By default, the library will raise an error when trying to store a non-supported model. When set to `false`, the procedure returns an empty result.
|===

.Results
[opts="header",cols="1,1,4"]
|===
| Name          | Type     | Description
| modelName     | String   | The name of the stored model.
| storeMillis   | Integer  | The number of milliseconds it took to store the model.
|===
--


=== Example

[role=query-example, no-result=true]
--
.Store a model on disk:
[source, cypher, role=noplay]
----
CALL gds.alpha.model.store('my-model')
YIELD
  modelName,
  storeMillis
----
--

[.alpha]
[[catalog-model-load]]
== Loading models from disk

GDS will discover available models from the configured store location upon database startup.
During discovery, only model metadata is loaded, not the actual model data.
In order to use a stored model, it has to be explicitly loaded.

=== Syntax

[.model-load-syntax]
--
.Remove a model from the catalog:
[source, cypher, role=noplay]
----
CALL gds.alpha.model.load(modelName: String)
YIELD
    modelName: String,
    loadMillis: Integer
----

.Parameters
[opts="header",cols="1,1,1m,1,4"]
|===
| Name          | Type   | Default | Optional | Description
| modelName     | String | n/a     | no      | The name of a model.
|===

.Results
[opts="header",cols="1,1,4"]
|===
| Name          | Type     | Description
| modelName     | String   | The name of the loaded model.
| loadMillis    | Integer  | The number of milliseconds it took to load the model.
|===
--

=== Example

[role=query-example, no-result=true]
--
.Store a model on disk:
[source, cypher, role=noplay]
----
CALL gds.alpha.model.load('my-model')
YIELD
  modelName,
  loadMillis
----
--

To verify if a model is loaded, we can use the xref:model-catalog/list.adoc[`gds.beta.model.list`] procedure.
The procedure returns flags to indicate if the model is stored and if the model is loaded into memory.
The operation is idempotent, and skips loading if the model is already loaded.

[.alpha]
[[catalog-model-delete]]
== Deleting models from disk

To remove a stored model from disk, it has to be deleted.
This is different from dropping a model.
Dropping a model will remove it from the in-memory model catalog, but not from disk.
Deleting a model will remove it from disk, but keep it in the in-memory model catalog if it was already loaded.


=== Syntax

[.model-delete-syntax]
--
.Remove a model from the catalog:
[source, cypher, role=noplay]
----
CALL gds.alpha.model.delete(modelName: String)
YIELD
    modelName: String,
    deleteMillis: Integer
----

.Parameters
[opts="header",cols="1,1,1m,1,4"]
|===
| Name          | Type   | Default | Optional | Description
| modelName     | String | n/a     | no      | The name of a model.
|===

.Results
[opts="header",cols="1,1,4"]
|===
| Name          | Type     | Description
| modelName     | String   | The name of the loaded model.
| deleteMillis  | Integer  | The number of milliseconds it took to delete the model.
|===
--

=== Example

[role=query-example, no-result=true]
--
.Store a model on disk:
[source, cypher, role=noplay]
----
CALL gds.alpha.model.delete('my-model')
YIELD
  modelName,
  deleteMillis
----
--
