[[algorithms-ml-linkprediction]]
= Link Prediction
:entity: relationship
:result: relationships
:algorithm: Link Prediction


[abstract]
--
This section describes the Link Prediction Model in the Neo4j Graph Data Science library.
--

This topic includes:

* <<algorithms-ml-linkprediction-intro, Introduction>>
* <<algorithms-ml-linkprediction-syntax, Syntax>>
* <<algorithms-ml-linkprediction-examples, Examples>>
** <<algorithms-ml-linkprediction-examples-mutate, Mutate>>


[[algorithms-ml-linkprediction-intro]]
== Introduction

Link Prediction models are used to predict non-existing relationships between nodes in a graph based on the nodes' properties.
The node properties are used as input features for specific machine learning model candidates.
The model candidates are trained on parts of the input graph and evaluated using a specific metric.
Creating these parts is a necessary pre-processing step called <<algorithms-ml-train-test-splitting>>.

The part of the input graph used for training is called the _train set_.
The part of the input graph used for evaluation is called the _test set_.

The training process follows this outline:

1. The train set is divided into a number of validation folds, consisting of a train part and a validation part.
2. Each model candidate is trained on each train part and evaluated on the respective validation part.
3. The model with the highest average score according to the metric will win the training.
4. The winning model will then be evaluated on the whole train set as well as the test set.
5. The winning model will be registered in the <<model-catalog-ops, Model Catalog>>.

Trained models may then be used to predict the probability of a relationship between two nodes.

[[algorithms-ml-train-test-splitting]]
=== Train/Test Splitting

The Link Prediction training takes as input two relationship types that are used to construct subgraphs representing the parts of the graph used for training and testing, respectively.
Creating these relationship types must be done before training a Link Prediction model.
The relationship types must have a integer property called `label`, with value either `0` or `1`, which denotes a negative or a positive example relationship in the original graph, respectively.

By using the `gds.alpha.ml.splitRelationships()` procedure it is possible to produce the necessary train/test splits.


=== Metrics

The Link Prediction model in the Neo4j GDS library supports only the Area Under the Precision-Recall Curve metric, abbreviated as AUCPR.


[[algorithms-ml-linkprediction-syntax]]
== Syntax

include::../../shared/syntax-intro-named-graph.adoc[]

WARNING: The named graphs must be projected in the `UNDIRECTED` orientation for the Triangle Count algorithm.

.Link Prediction syntax per mode
[.tabbed-example]
====

[.include-with-train]
======
.Run Link Prediction in train mode on a named graph:
[source]
----
CALL gds.alpha.ml.linkPrediction.train(
  graphName: String,
  configuration: Map
) YIELD
  trainMillis: Integer,
  modelInfo: Map,
  configuration: Map
----

include::../../common-configuration/common-parameters-named-graph.adoc[]

include::../../common-configuration/common-train-configuration-named-graph.adoc[]

include::specific-train-configuration.adoc[]

.Results
[opts="header",cols="1,1,6"]
|===
| Name          | Type    | Description
| trainMillis   | Integer | Milliseconds used for training.
| modelInfo     | Map     | Information about the training and the winning model.
| configuration | Map     | Configuration used for the train procedure.
|===
======


[.include-with-mutate]
======
.Run Link Prediction in mutate mode on a named graph:
[source]
----
CALL gds.alpha.ml.linkPrediction.predict.mutate(
  graphName: String,
  configuration: Map
)
YIELD
  createMillis: Integer,
  computeMillis: Integer,
  postProcessingMillis: Integer,
  mutateMillis: Integer,
  relationshipsWritten: Integer,
  configuration: Map
----

include::../../common-configuration/common-parameters-named-graph.adoc[]

include::../../common-configuration/common-mutate-configuration-named-graph.adoc[]

include::specific-configuration.adoc[]

.Results
[opts="header",cols="1,1,6"]
|===
| Name                 | Type    | Description
| createMillis         | Integer | Milliseconds for creating the graph.
| computeMillis        | Integer | Milliseconds for running the algorithm.
| postProcessingMillis | Integer | Milliseconds for computing the global metrics.
| mutateMillis         | Integer | Milliseconds for adding properties to the in-memory graph.
| relationshipsWritten | Integer | Number of relationships created.
| configuration        | Map     | Configuration used for running the algorithm.
|===
======
====

[[algorithms-ml-linkprediction-examples]]
== Examples

//TODO

[[algorithms-ml-linkprediction-examples-mutate]]
=== Mutate

//TODO