[[algorithms-celf]]
[.beta]
= CELF
:description: This section describes the Cost Effective Lazy Forward (CELF) influence maximization algorithm in the Neo4j Graph Data Science library.
:entity: influenceMaximization
:result: spread
:algorithm: CELF


include::partial$/operations-reference/beta-note.adoc[]

This topic includes:

* xref::algorithms/influence-maximization/celf.adoc#alpha-algorithms-celf-intro[Introduction]
* xref::algorithms/influence-maximization/celf.adoc#alpha-algorithms-celf-syntax[Syntax]
* xref::algorithms/influence-maximization/celf.adoc#alpha-algorithms-celf-examples[Examples]
** xref::algorithms/influence-maximization/celf.adoc#alpha-algorithms-celf-examples-stream[Stream]

[[alpha-algorithms-celf-intro]]
== Introduction
The CELF algorithm for influence maximization aims to find `k` nodes that maximize the expected spread of influence in the network.
It simulates the influence spread using the Independent Cascade model, which calculates the expected spread by taking the average spread over the `mc` Monte-Carlo simulations.
In the propagation process, a node is influenced in case that a uniform random draw is less than the probability `p`.

Leskovec et al. 2007 introduced the CELF algorithm in their study https://www.cs.cmu.edu/~jure/pubs/detect-kdd07.pdf[Cost-effective Outbreak Detection in Networks] to deal with the NP-hard problem of influence maximization.
The CELF algorithm is based on a "lazy-forward" optimization.
Τhe CELF algorithm dramatically improves the efficiency of the xref::algorithms/influence-maximization/greedy.adoc[Greedy] algorithm and should be preferred for large networks.

[[alpha-algorithms-celf-syntax]]
== Syntax


.CELF syntax per mode
[.tabbed-example, caption = ]
====

[.include-with-stream]
======

.Run CELF in stream mode on a named graph.
[source, cypher, role=noplay]
----
CALL gds.beta.influenceMaximization.celf.stream(
  graphName: String,
  configuration: Map
)
YIELD
  nodeId: Integer,
  spread: Float
----

include::partial$/algorithms/common-configuration/common-parameters.adoc[]

.Configuration
[opts="header",cols="3,2,3m,2,8"]
|===
| Name          | Type   | Default | Optional | Description
include::partial$/algorithms/common-configuration/common-stream-stats-configuration-entries.adoc[]
include::partial$/algorithms/alpha/influence-maximization/specific-configuration.adoc[]
|===

.Results
[opts="header"]
|===
| Name         | Type       | Description
| nodeId       | Integer    | Node ID.
| spread       | Float      | The spread gained by selecting the node.
|===
======

[.include-with-mutate]
======

.Run CELF in mutate mode on a named graph.
[source, cypher, role=noplay]
----
CALL gds.beta.influenceMaximization.celf.mutate(
  graphName: String,
  configuration: Map
)
YIELD
  mutateMillis: Integer,
  nodePropertiesWritten: Integer
----

include::partial$/algorithms/common-configuration/common-parameters.adoc[]

.Configuration
[opts="header",cols="3,2,3m,2,8"]
|===
| Name          | Type   | Default | Optional | Description
include::partial$/algorithms/common-configuration/common-mutate-configuration-entries.adoc[]
include::partial$/algorithms/alpha/influence-maximization/specific-configuration.adoc[]
|===

.Results
[opts="header"]
|===
| Name                   | Type      | Description
| mutateMillis           | Integer   | Milliseconds for adding properties to the projected graph.
| nodePropertiesWritten  | Integer   | Number of properties added to the projected graph.
|===
======

[.include-with-write]
======

.Run CELF in write mode on a named graph.
[source, cypher, role=noplay]
----
CALL gds.beta.influenceMaximization.celf.write(
  graphName: String,
  configuration: Map
)
YIELD
  writeMillis: Integer,
  nodePropertiesWritten: Integer
----

include::partial$/algorithms/common-configuration/common-parameters.adoc[]

.Configuration
[opts="header",cols="3,2,3m,2,8"]
|===
| Name          | Type   | Default | Optional | Description
include::partial$/algorithms/common-configuration/common-write-configuration-entries.adoc[]
include::partial$/algorithms/alpha/influence-maximization/specific-configuration.adoc[]
|===

.Results
[opts="header"]
|===
| Name                   | Type      | Description
| writeMillis            | Integer   | Milliseconds for adding properties to the projected graph.
| nodePropertiesWritten  | Integer   | Number of properties added to the Neo4j database.
|===
======

====


[[alpha-algorithms-celf-examples]]
== Examples

:algorithm-name: {algorithm}
:graph-description: social network
:image-file: influence-maximization.svg
include::partial$/algorithms/shared/examples-intro.adoc[]

.The following Cypher statement will create the example graph in the Neo4j database:
[source, cypher, role=setup-query]
----
CREATE
  (a:Person {name: 'Jimmy'}),
  (b:Person {name: 'Jack'}),
  (c:Person {name: 'Alice'}),
  (d:Person {name: 'Ceri'}),
  (e:Person {name: 'Mohammed'}),
  (f:Person {name: 'Michael'}),
  (g:Person {name: 'Ethan'}),
  (h:Person {name: 'Lara'}),
  (i:Person {name: 'Amir'}),
  (j:Person {name: 'Willie'}),

  (b)-[:FRIEND_OF]->(c),
  (c)-[:FRIEND_OF]->(a),
  (c)-[:FRIEND_OF]->(g),
  (c)-[:FRIEND_OF]->(h),
  (c)-[:FRIEND_OF]->(i),
  (c)-[:FRIEND_OF]->(j),
  (d)-[:FRIEND_OF]->(g),
  (f)-[:FRIEND_OF]->(e),
  (f)-[:FRIEND_OF]->(g),
  (g)-[:FRIEND_OF]->(a),
  (g)-[:FRIEND_OF]->(b),
  (g)-[:FRIEND_OF]->(h),
  (g)-[:FRIEND_OF]->(e),
  (h)-[:FRIEND_OF]->(i);
----

In the example, we will use the CELF algorithm to find `k` nodes subset.

.The following statement will project the graph and store it in the graph catalog.
[source, cypher, role=graph-project-query no-play]
----
CALL gds.graph.project(
  'myGraph',
  'Person',
  'FRIEND_OF'
);
----

In the following examples we will demonstrate using the CELF algorithm on this graph.


[[alpha-algorithms-celf-examples-stream]]
=== Stream

In the `stream` execution mode, the algorithm returns the {result} for each node.
This allows us to inspect the results directly or post-process them in Cypher without any side effects.

For more details on the `stream` mode in general, see xref::common-usage/running-algos.adoc#running-algos-stream[Stream].

[role=query-example]
--
.The following will run the algorithm, and stream results:
[source, cypher, role=noplay]
----
CALL gds.beta.influenceMaximization.celf.stream('myGraph', {seedSetSize: 3, concurrency: 4})
YIELD nodeId, spread
RETURN gds.util.asNode(nodeId).name AS Name, spread
ORDER BY spread ASC
----

.Results
[opts="header"]
|===
| Name      | spread
| "Michael" | 1.08
| "Ceri"    | 1.08
| "Alice"   | 1.6
|===
--
