[[algorithms-greedy]]
[.alpha]
= Greedy
:description: This section describes the Greedy influence maximization algorithm in the Neo4j Graph Data Science library.
:entity: influenceMaximization
:result: spread
:algorithm: Greedy


include::partial$/operations-reference/alpha-note.adoc[]

This topic includes:

* xref::algorithms/influence-maximization/greedy.adoc#alpha-algorithms-greedy-intro[Introduction]
* xref::algorithms/influence-maximization/greedy.adoc#alpha-algorithms-greedy-syntax[Syntax]
* xref::algorithms/influence-maximization/greedy.adoc#alpha-algorithms-greedy-examples[Examples]
** xref::algorithms/influence-maximization/greedy.adoc#alpha-algorithms-greedy-examples-stream[Stream]

[[alpha-algorithms-greedy-intro]]
== Introduction
The Greedy algorithm for influence maximization aims to find `k` nodes that maximize the expected spread of influence in a network.
It simulates the influence spread using the Independent Cascade model, which calculates the expected spread by taking the average spread over the `mc` Monte-Carlo simulations.
In the propagation process, a node is influenced in case that a uniform random draw is less than the probability `p`.

Kempe et al. 2003 introduced the Greedy algorithm in their study https://www.cs.cornell.edu/home/kleinber/kdd03-inf.pdf[Maximizing the Spread of Influence through a Social Network] to deal with the *NP*-hard problem of influence maximization.
The Greedy algorithm successively selecting the node within the maximum marginal gain approximation in polynomial time.
For large networks xref::algorithms/influence-maximization/celf.adoc[CELF] algorithm should be used.

[[alpha-algorithms-greedy-syntax]]
== Syntax

include::partial$/operations-reference/alpha-note.adoc[]

.Greedy syntax per mode
[.tabbed-example, caption = ]
====

[.include-with-stream]
======

.Run Greedy in stream mode on a named graph.
[source, cypher, role=no-play]
----
CALL gds.alpha.influenceMaximization.greedy.stream(
  graphName: String,
  configuration: Map
)
YIELD
  nodeId: Integer,
  spread : Float
----

include::partial$/algorithms/common-configuration/common-parameters.adoc[]

.Configuration
[opts="header",cols="3,2,3m,2,8"]
|===
| Name          | Type   | Default | Optional | Description
include::partial$/algorithms/common-configuration/common-stream-stats-configuration-entries.adoc[]
include::partial$/algorithms/alpha/influence-maximization/specific-configuration.adoc[]
|===

.Results
[opts="header"]
|===
| Name         | Type       | Description
| nodeId       | Integer    | Node ID.
| spread       | Float      | The spread gained by selecting the node.
|===
======
[.include-with-stats]
======
.Run Greedy in stats mode on a named graph.
[source, cypher, role=no-play]
----
CALL gds.alpha.influenceMaximization.greedy.stats(
  graphName: String,
  configuration: Map
)
YIELD
  nodes: Integer,
  computeMillis: Integer,
----

include::partial$/algorithms/common-configuration/common-parameters.adoc[]

.Configuration
[opts="header",cols="3,2,3m,2,8"]
|===
| Name          | Type   | Default | Optional | Description
include::partial$/algorithms/common-configuration/common-stream-stats-configuration-entries.adoc[]
include::partial$/algorithms/alpha/influence-maximization/specific-configuration.adoc[]
|===

.Results
[opts="header",cols="1,1,6"]
|===
| Name                   | Type      | Description
| nodes                  | Integer   | The number of nodes in the graph.
| computeMillis          | Integer   | Milliseconds for running the algorithm.
|===
======
====


[[alpha-algorithms-greedy-examples]]
== Examples

:algorithm-name: {algorithm}
:graph-description: social network
:image-file: influence-maximization.svg
include::partial$/algorithms/shared/examples-intro.adoc[]

.The following Cypher statement will create the example graph in the Neo4j database:
[source, cypher, role=setup-query no-play]
----
CREATE
  (a:Person {name: 'Jimmy'}),
  (b:Person {name: 'Jack'}),
  (c:Person {name: 'Alice'}),
  (d:Person {name: 'Ceri'}),
  (e:Person {name: 'Mohammed'}),
  (f:Person {name: 'Michael'}),
  (g:Person {name: 'Ethan'}),
  (h:Person {name: 'Lara'}),
  (i:Person {name: 'Amir'}),
  (j:Person {name: 'Willie'}),

  (b)-[:FRIEND_OF]->(c),
  (c)-[:FRIEND_OF]->(a),
  (c)-[:FRIEND_OF]->(g),
  (c)-[:FRIEND_OF]->(h),
  (c)-[:FRIEND_OF]->(i),
  (c)-[:FRIEND_OF]->(j),
  (d)-[:FRIEND_OF]->(g),
  (f)-[:FRIEND_OF]->(e),
  (f)-[:FRIEND_OF]->(g),
  (g)-[:FRIEND_OF]->(a),
  (g)-[:FRIEND_OF]->(b),
  (g)-[:FRIEND_OF]->(h),
  (g)-[:FRIEND_OF]->(e),
  (h)-[:FRIEND_OF]->(i);
----

In the example, we will use the Greedy algorithm to find `k` nodes subset.

.The following statement will project the graph and store it in the graph catalog.
[source, cypher, role=graph-project-query no-play]
----
CALL gds.graph.project(
  'myGraph',
  'Person',
  'FRIEND_OF'
);
----

In the following examples we will demonstrate using the Greedy algorithm on this graph.


[[alpha-algorithms-greedy-examples-stream]]
=== Stream

In the `stream` execution mode, the algorithm returns the {result} for each node.
This allows us to inspect the results directly or post-process them in Cypher without any side effects.

For more details on the `stream` mode in general, see xref::common-usage/running-algos.adoc#running-algos-stream[Stream].

[role=query-example]
--
.The following will run the algorithm, and stream results:
[source, cypher, role=no-play]
----
CALL gds.alpha.influenceMaximization.greedy.stream('myGraph', {seedSetSize: 3, concurrency: 4})
YIELD nodeId, spread
RETURN gds.util.asNode(nodeId).name AS Name, spread
ORDER BY spread ASC
----

.Results
[opts="header"]
|===
| Name      | spread
| "Michael" | 1.08
| "Ceri"    | 1.08
| "Alice"   | 1.6
|===
--
