plugins {
    id 'buildlogic-gds-java'
}

description = 'Neo4j Graph Data Science :: Compression :: Uncompressed Codec'
group = 'org.neo4j.gds'

dependencies {
    annotationProcessor project(':annotations')

    compileOnly openGds.jetbrains.annotations

    implementation project(':annotations')
    implementation project(':compression-api')
    implementation project(':compression-common')
    implementation project(':core-api')
    implementation project(':core-utils')
    implementation project(':collections')
    implementation project(':concurrency')
    implementation project(':graph-dimensions')
    implementation project(':memory-access')
    implementation project(':memory-info')
    implementation project(':memory-usage')

    implementation openGds.commons.lang3
    implementation openGds.hppc

    testImplementation project(':test-utils')
}
