[[logging]]
= Logging

[abstract]
--
This chapter contains details for functionality available in the Neo4j Graph Data Science Library that doesn't belong in any of the other categories.
--

== Utility procedures

[.beta]
=== Progress Logging Procedure

This is a procedure that can show the log entries of a long-running task or algorithm.

[NOTE]
====
In order to use the Progress Logging feature, you must first enable it via Neo4j configuration,
by setting `gds.progress_tracking_enabled=true` in the `neo4j.conf` configuration file of your Neo4j installation.
====

==== Syntax

.Getting the proggress of tasks:
[source, cypher, role=noplay]
----
CALL gds.beta.listProgress()
YIELD
  id,
  taskName,
  message
----

.Results
* `id`: generated identifier of the running task.
* `taskName`: the name of the running task, i.e. `Node2Vec`.
* `message`: the progress log message, same as what is logged to the `debug.log` file.

==== Examples

Assuming we just started `gds.beta.node2vec.stream` procedure.

[source, cypher, role=noplay]
----
CALL gds.beta.listProgress()
YIELD
  id,
  taskName,
  message
----

.Results
[opts="header"]
|===
| id                                     | taskName   | message
| "d21bb4ca-e1e9-4a31-a487-42ac8c9c1a0d" | "Node2Vec" | "[gds-1] Node2Vec 42%"
|===
