[[logging]]
= Logging

[abstract]
--
This section describes logging features in the Neo4j Graph Data Science library.
--

In the GDS library there are two types of logging: debug logging and progress logging.

*Debug logging* provides information about events in the system.
For example, when an algorithm computation completes, the amount of memory used and the total runtime may be logged.
Exceptional events, when an operation fails to complete normally, are also logged.
The debug log information is useful for understanding events in the system, especially when troubleshooting a problem.

*Progress logging* is performed to track the progress of operations that are expected to take a long time.
This includes graph projections, algorithm computation, and result writing.

All log entries are written to the log files configured for the Neo4j database.
For more information on configuring Neo4j logs, please refer to the https://neo4j.com/docs/operations-manual/current/monitoring/logging/#logging[Neo4j Operations Manual].


[[logging-progress-logging]]
[.beta]
== Progress-logging procedure

Progress events may also be tracked by the GDS library itself.
This makes it possible to inspect progress via Cypher, in addition to looking in the log files.
To enable this feature, the Neo4j configuration must include the entry `gds.progress_tracking_enabled=true`.
When the feature is enabled, a procedure is loaded that can be called to show progress events for currently running tasks.

The list progress procedures has two modes, depending on whether a `jobId` parameter was set:
First, if `jobId` is not set, the procedure will produce a single row for each progress currently running.
This can be seen as the summary of those tasks, displaying the overall progress of a particular task for example.
Second, if the `jobId` parameter is set it will show a detailed view for the given running job.
The detailed view will produce a row for each step or task that job will perform during execution.
It will also show how tasks are structured as a tree and print progress for each individual task.

[[logging-progress-logging-syntax]]
=== Syntax

.Getting the progress of tasks:
[source, cypher, role=noplay]
----
CALL gds.beta.listProgress(jobId: String)
YIELD
  jobId,
  taskName,
  progress,
  progressBar,
  status,
  timeStarted,
  elapsedTime
----

.Parameters
[opts="header",cols="1,1,1,1,4"]
|===
| Name              | Type          | Default   | Optional  | Description
| jobId             | String        | "         | yes       | The jobId of a running task. This will trigger a detailed overview for that particular task.
|===

.Results
[opts="header",cols="1m,1,6"]
|===
| Name          | Type      | Description
| jobId         | String    | A generated identifier of the running task.
| taskName      | String    | The name of the running task, i.e. `Node2Vec`.
| progress      | String    | The progress of the job shown as a percentage value.
| progressBar   | String    | The progress of the job shown as an ASCII progress bar.
| status        | String    | The current status of the job, i.e. `RUNNING` or `CANCELED`.
| timeStarted   | LocalTime | The local wall clock time when the task has been started.
| elapsedTime   | Duration  | The duration from `timeStarted` to now.


[[logging-progress-logging-examples]]
=== Examples

Assuming we just started `gds.beta.node2vec.stream` procedure.

[source, cypher, role=noplay]
----
CALL gds.beta.listProgress()
YIELD
  id,
  taskName,
  progress
----

.Results
[opts="header"]
|===
| id                                     | taskName   | progress
| "d21bb4ca-e1e9-4a31-a487-42ac8c9c1a0d" | "Node2Vec" | "42%"
|===
