[[logging]]
= Logging

[abstract]
--
This section describes logging features in the Neo4j Graph Data Science Library.
--

In the GDS library there are generally two types of logging: debug logging and progress logging.

*Debug logging* is performed as part of any operation, detailing activities or events that are deemed interesting for analysis purpose.
This includes troubleshooting after an unexpected error as well as system administrator monitoring.

*Progress logging* is performed to track the progress of operations that are expected to take a long time.
This includes graph projections, algorithm computation, and result writing.

All log entries are written to the physical logs configured by the database configuration.
For more information on configuring physical logs, please refer to the https://neo4j.com/docs/operations-manual/current/monitoring/logging/#logging[Neo4j Operations Manual].


[.beta]
== Progress Logging Procedure

Progress logging events may also be maintained by the GDS library itself.
To enable this, the Neo4j configuration must include the entry `gds.progress_tracking_enabled=true`.
This enables a procedure that can show the log entries of a long-running task or algorithm.

=== Syntax

.Getting the progress of tasks:
[source, cypher, role=noplay]
----
CALL gds.beta.listProgress()
YIELD
  id,
  taskName,
  message
----

.Results
* `id`: generated identifier of the running task.
* `taskName`: the name of the running task, i.e. `Node2Vec`.
* `message`: the progress log message, same as what is logged to the `debug.log` file.

=== Examples

Assuming we just started `gds.beta.node2vec.stream` procedure.

[source, cypher, role=noplay]
----
CALL gds.beta.listProgress()
YIELD
  id,
  taskName,
  message
----

.Results
[opts="header"]
|===
| id                                     | taskName   | message
| "d21bb4ca-e1e9-4a31-a487-42ac8c9c1a0d" | "Node2Vec" | "[gds-1] Node2Vec 42%"
|===
