[appendix]
[[appendix-b]]
= Migration from Graph Algorithms v3.5
:description: If you have previously used Graph Algorithm v3.5, you can find the information you will need to migrate to using the Graph Data Science library in this section.


== Who should read this guide

This documentation is intended for users who are familiar with the Graph Algorithms library.
We assume that most of the mentioned operations and concepts can be understood with little explanation.
Thus we are intentionally brief in the examples and comparisons.
Please see the dedicated chapters in this manual for details on all the features in the Graph Data Science library.

== Syntax Changes

In this section we will focus on side-by-side examples of operations using the syntax of the Graph Algorithms library and Graph Data Science library, respectively.

This section is divided into the following sub-sections:

* xref::appendix-b/migration-algos-common.adoc[Common Changes]
* xref::appendix-b/migration-memory-estimation.adoc[Memory estimation]
* xref::appendix-b/migration-named-graph.adoc[Graph creation - Named Graph]
* xref::appendix-b/migration-cypher-projection.adoc[Graph creation - Cypher Queries]
* xref::appendix-b/migration-graph-list.adoc[Graph listing]
* xref::appendix-b/migration-graph-info.adoc[Graph info]
* xref::appendix-b/migration-graph-remove.adoc[Graph removal]
* xref::appendix-b/migration-product-algos.adoc[Production-quality algorithms]


