[[introduction]]
= Introduction
:description: This chapter provides a brief introduction of the main concepts in the Neo4j Graph Data Science library.


The Neo4j Graph Data Science (GDS) library provides efficiently implemented, parallel versions of common graph algorithms, exposed as Cypher procedures.
Additionally, GDS includes machine learning pipelines to train predictive supervised models to solve graph problems, such as predicting missing relationships.

[[introduction-tiers]]
== API tiers

The GDS API comprises Cypher procedures and functions.
Each of these exist in one of three tiers of maturity:

* Production-quality
** Indicates that the feature has been tested with regards to stability and scalability.
** Features in this tier are prefixed with `gds.<operation>`.
* Beta
** Indicates that the feature is a candidate for the production-quality tier.
** Features in this tier are prefixed with `gds.beta.<operation>`.
* Alpha
** Indicates that the feature is experimental and might be changed or removed at any time.
** Features in this tier are prefixed with `gds.alpha.<operation>`.


[[introduction-algorithms]]
== Algorithms

Graph algorithms are used to compute metrics for graphs, nodes, or relationships.

They can provide insights on relevant entities in the graph (centralities, ranking), or inherent structures like communities (community-detection, graph-partitioning, clustering).

Many graph algorithms are iterative approaches that frequently traverse the graph for the computation using random walks, breadth-first or depth-first searches, or pattern matching.

Due to the exponential growth of possible paths with increasing distance, many of the approaches also have high algorithmic complexity.

Fortunately, optimized algorithms exist that utilize certain structures of the graph, memoize already explored parts, and parallelize operations.
Whenever possible, we've applied these optimizations.

The Neo4j Graph Data Science library contains a large number of algorithms, which are detailed in the xref:algorithms/index.adoc[Algorithms] chapter.


[[introduction-algorithms-traits]]
=== Algorithm traits

Algorithms in GDS have specific ways to make use of various aspects of its input graph(s).
We call these _algorithm traits_.
When an algorithm supports an algorithm trait this indicates that the algorithm has been implemented to produce well-defined results in accordance with the trait.
The following algorithm traits exist:

[[introduction-algorithms-directed]]
Directed::
The algorithm is well-defined on a directed graph.

[[introduction-algorithms-undirected]]
Undirected::
The algorithm is well-defined on an undirected graph.

[[introduction-algorithms-homogeneous]]
Homogeneous::
The algorithm will treat all nodes and relationships in its input graph(s) similarly, as if they were all of the same type.
If multiple types of nodes or relationships exist in the graph, this must be taken into account when analysing the results of the algorithm.

[[introduction-algorithms-heterogeneous]]
Heterogeneous::
The algorithm has the ability to distinguish between nodes and/or relationships of different types.

[[introduction-algorithms-weighted]]
Weighted::
The algorithm supports configuration to set node and/or relationship properties to use as weights.
These values can represent _cost_, _time_, _capacity_ or some other domain-specific properties, specified via the xref:common-usage/running-algos.adoc#common-configuration-node-weight-property[nodeWeightProperty], nodeProperties and xref:common-usage/running-algos.adoc#common-configuration-relationship-weight-property[relationshipWeightProperty] configuration parameters.
The algorithm will by default consider each node and/or relationship as equally important.


[[introduction-catalog]]
== Graph Catalog

In order to run the algorithms as efficiently as possible, GDS uses a specialized graph format to represent the graph data.
It is therefore necessary to load the graph data from the Neo4j database into an in memory graph catalog.
The amount of data loaded can be controlled by so called graph projections, which also allow, for example, filtering on node labels and relationship types, among other options.

For more information see xref:management-ops/index.adoc[Graph Management].


[[introduction-editions]]
== Editions

The Neo4j Graph Data Science library is available in two editions.

* The open source Community Edition includes all algorithms and features, but is limited to four CPU cores.
* The Neo4j Graph Data Science library Enterprise Edition:
** Can run on an unlimited amount of CPU cores.
** Supports the role-based access control system (RBAC) from Neo4j Enterprise Edition.
** xref::production-deployment/causal-cluster.adoc[Support running GDS as part of Neo4j Causal Cluster deployment.]
** xref::common-usage/monitoring-system.adoc[Monitor a system's capacity and analytics workload]
** Supports various additional graph catalog features
*** xref::management-ops/backup-restore.adoc[Backup and restore graphs]
*** xref::management-ops/create-cypher-db.adoc[Run cypher queries against a projected graph]
*** xref:installation/installation-apache-arrow.adoc[Import and export data via Apache Arrow]
** Supports various additional model catalog features
*** Storing unlimited amounts of models in the model catalog
*** xref:model-catalog/publish.adoc[Publishing a stored model]
*** xref:model-catalog/store.adoc#model-catalog-store-ops[Persisting a stored model to disk]
** Supports an xref:production-deployment/feature-toggles.adoc#bit-id-map-feature-toggle[optimized graph implementation]
** xref:management-ops/defaults-and-limits.adoc[Configure defaults and limits]

For more information see xref:installation/System-requirements.adoc#system-requirements-cpu[System Requirements - CPU].
