[[linkprediction-pipelines]]
[.beta]
= Link prediction pipelines
:description: This section describes Link prediction pipelines in the Neo4j Graph Data Science library.
:entity: relationship
:result: relationships
:max-trials: 10

include::partial$/operations-reference/beta-note.adoc[]


Link prediction is a common machine learning task applied to graphs: training a model to learn, between pairs of nodes in a graph, where relationships should exist.
More precisely, the input to the machine learning model are _examples_ of node pairs.
During training, the node pairs are labeled as adjacent or not adjacent.

In GDS, we have Link prediction pipelines which offer an end-to-end workflow, from feature extraction to link prediction.
The training pipelines reside in the xref:pipeline-catalog/index.adoc[pipeline catalog].
When a training pipeline is xref:machine-learning/linkprediction-pipelines/training.adoc[executed], a prediction model is created and stored in the xref:model-catalog/index.adoc[model catalog].

A training pipeline is a sequence of three phases:
[upperroman]
. From the graph three sets of node pairs are derived: feature set, training set, test set. The latter two are labeled.
. The nodes in the graph are augmented with new properties by running a series of steps on the graph with only relationships from the feature set.
. The train and test sets are used for training a link prediction pipeline. Link features are derived by combining node properties of node pairs.

For the training and test sets, positive examples are xref:machine-learning/linkprediction-pipelines/config.adoc#linkprediction-configure-splits[selected] from the relationships in the graph.
The negative examples are sampled from non-adjacent nodes.

One can xref:machine-learning/linkprediction-pipelines/config.adoc#linkprediction-adding-node-properties[configure] which steps should be included above.
The steps execute GDS algorithms that create new node properties.
After configuring the node property steps, one can xref:machine-learning/linkprediction-pipelines/config.adoc#linkprediction-adding-features[define] how to combine node properties of node pairs into link features.
The training phase (III) trains multiple model candidates using cross-validation, selects the best one, and reports relevant performance metrics.

After xref:machine-learning/linkprediction-pipelines/training.adoc[training the pipeline], a prediction model is created.
This model includes the node property steps and link feature steps from the training pipeline and uses them to generate the relevant features for predicting new relationships.
The prediction model can be applied to infer the probability of the existence of a relationship between two non-adjacent nodes.

NOTE: xref:machine-learning/linkprediction-pipelines/predict.adoc[Prediction] can only be done with a prediction model (not with a training pipeline).

This segment is divided into the following pages:

* xref:machine-learning/linkprediction-pipelines/config.adoc[Configuring the pipeline]
* xref:machine-learning/linkprediction-pipelines/training.adoc[Training the pipeline]
* xref:machine-learning/linkprediction-pipelines/predict.adoc[Applying a trained model for prediction]
* xref:machine-learning/linkprediction-pipelines/theory.adoc[Theoretical considerations]
