[[supported-neo4j-versions]]
= Supported Neo4j versions

Below is the compatibility matrix for The GDS library vs Neo4j. In general, you can count on the latest version of GDS supporting the latest version of Neo4j and vice versa, and we recommend you always upgrade to that combination.

We list software with major and minor version only, e.g. GDS library 1.5. You should read that as any patch version of that major+minor version, but again, do upgrade to the latest patch always, to ensure you get all bug fixes included.

Not finding your version of GDS or Neo4j listed? Time to upgrade!

[opts=header]
|===
| Neo4j Graph Data Science | Neo4j version
.3+<.^|`1.7`
| `4.3`
| `4.2`
| `4.1` footnote:neo411bug[There is a bug in Neo4j 4.1.1 that can lead to an exception when using Cypher projection. If possible, use the lastest patch version.]
.4+<.^|`1.6`
| `4.3`
| `4.2`
| `4.1` footnote:neo411bug[There is a bug in Neo4j 4.1.1 that can lead to an exception when using Cypher projection. If possible, use the lastest patch version.]
| `4.0`
|`1.1`
| `3.5`
|===
