[[configuration-settings1]]
= Configuration Settings
:description: This section describes the available configuration settings in the Neo4j Graph Data Science library.

This page describes the available configuration settings in GDS.
Refer to The https://neo4j.com/docs/operations-manual/current/configuration/neo4j-conf/#neo4j-conf[neo4j.conf] file for details on how to use configuration settings.


All settings

* <<gds.arrow.abortion_timeout, gds.arrow.abortion_timeout>>: label:enterprise-edition[Enterprise Edition] The maximum time to wait for the next command before aborting the import process.
* <<gds.arrow.advertised_listen_address, gds.arrow.advertised_listen_address>>: label:enterprise-edition[Enterprise Edition] Address that clients should use to connect to the GDS Arrow Flight Server.
* <<gds.arrow.batch_size, gds.arrow.batch_size>>: label:enterprise-edition[Enterprise Edition] The batch size used for arrow property export.
* <<gds.arrow.enabled, gds.arrow.enabled>>: label:enterprise-edition[Enterprise Edition] Enable the GDS Arrow Flight Server.
* <<gds.arrow.encryption.never, gds.arrow.encryption.never>>: label:enterprise-edition[Enterprise Edition] Never activate server-side encryption for the GDS Arrow Flight Server.
* <<gds.arrow.listen_address, gds.arrow.listen_address>>: label:enterprise-edition[Enterprise Edition] Address the GDS Arrow Flight Server should bind to.
* <<gds.cluster.tx.max.size, gds.cluster.tx.max.size>>: label:enterprise-edition[Enterprise Edition] Set the maximum transaction size for GDS on Read Replica
* <<gds.cluster.tx.min.size, gds.cluster.tx.min.size>>: label:enterprise-edition[Enterprise Edition] Set the minimum transaction size for GDS on Read Replica
* <<gds.enterprise.license_file, gds.enterprise.license_file>>: Sets the location of the file that contains the Neo4j Graph Data Science library license key
* <<gds.export.location, gds.export.location>>: Sets the export location for file based exports.
* <<gds.model.store_location, gds.model.store_location>>: label:enterprise-edition[Enterprise Edition] Sets the location where persisted models are stored.
* <<gds.progress_tracking_enabled, gds.progress_tracking_enabled>>: Enable progress logging tracking.
* <<gds.validate_using_max_memory_estimation, gds.validate_using_max_memory_estimation>>: Use maximum memory estimation in procedure memory guard.


[[gds.arrow.abortion_timeout]]
`gds.arrow.abortion_timeout` label:enterprise-edition[Enterprise Edition]

* The maximum time to wait for the next command before aborting the import process.
* defaultValue: `10m`
* validValues: a duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d` default unit is `s`)
* dynamic: `false`


[[gds.arrow.advertised_listen_address]]
`gds.arrow.advertised_listen_address` label:enterprise-edition[Enterprise Edition]

* Address that clients should use to connect to the GDS Arrow Flight Server.
* defaultValue: `:8491`
* validValues: a socket address in the format `hostname:port`, `hostname` or `:port`. If missing port or hostname it is acquired from `gds.arrow.listen_address`
* dynamic: `false`


[[gds.arrow.batch_size]]
`gds.arrow.batch_size` label:enterprise-edition[Enterprise Edition]

* The batch size used for arrow property export.
* defaultValue: `10000`
* validValues: an integer
* dynamic: `true`


[[gds.arrow.enabled]]
`gds.arrow.enabled` label:enterprise-edition[Enterprise Edition]

* Enable the GDS Arrow Flight Server.
* defaultValue: `false`
* validValues: a boolean
* dynamic: `false`


[[gds.arrow.encryption.never]]
`gds.arrow.encryption.never` label:enterprise-edition[Enterprise Edition]

* Never activate server-side encryption for the GDS Arrow Flight Server.
* defaultValue: `false`
* validValues: a boolean
* dynamic: `false`


[[gds.arrow.listen_address]]
`gds.arrow.listen_address` label:enterprise-edition[Enterprise Edition]

* The maximum time to wait for the next command before aborting the import process.
* defaultValue: `10m`
* validValues: a duration (Valid units are: `ns`, `μs`, `ms`, `s`, `m`, `h` and `d` default unit is `s`)
* dynamic: `false`


[[gds.cluster.tx.max.size]]
`gds.cluster.tx.max.size` label:enterprise-edition[Enterprise Edition]

* Set the maximum transaction size for GDS write back when running in Neo4j Cluster.
* defaultValue: `100000`
* validValues: an integer, must be set greater than or equal to the value of `gds.cluster.tx.min.size`
* dynamic: `false`


[[gds.cluster.tx.min.size]]
`gds.cluster.tx.min.size` label:enterprise-edition[Enterprise Edition]

* Set the minimum transaction size for GDS write back when running in Neo4j Cluster.
* defaultValue: `10000`
* validValues: an integer
* dynamic: `false`


[[gds.enterprise.license_file]]
`gds.enterprise.license_file`

* Sets the location of the file that contains the Neo4j Graph Data Science library license key.
* defaultValue: `No Value`
* validValues: an absolute path
* dynamic: `false`


[[gds.export.location]]
`gds.export.location`

* Sets the export location for file based exports.
* defaultValue: `No Value`
* validValues: an absolute path
* dynamic: `false`


[[gds.model.store_location]]
`gds.model.store_location` label:enterprise-edition[Enterprise Edition]

* Sets the location where persisted models are stored.
* defaultValue: `No Value`
* validValues: an absolute path
* dynamic: `false`


[[gds.progress_tracking_enabled]]
`gds.progress_tracking_enabled`

* Enable progress logging tracking.
* defaultValue: `true`
* validValues: a boolean
* dynamic: `false`


[[gds.validate_using_max_memory_estimation]]
`gds.validate_using_max_memory_estimation`

* Use maximum memory estimation in procedure memory guard.
* defaultValue: `false`
* validValues: a boolean
* dynamic: `false`
