plugins {
    id 'buildlogic-gds-java'
}

description = 'Neo4j Graph Data Science :: Algorithms'

group = 'org.neo4j.gds'

dependencies {
    annotationProcessor project(':annotations')
    annotationProcessor project(':config-generator')
    annotationProcessor openGds.immutables.builder
    annotationProcessor openGds.immutables.value
    annotationProcessor neo4j.annotations
    annotationProcessor openGds.recordBuilder

    compileOnly openGds.recordBuilder
    compileOnly openGds.immutables.builder
    compileOnly openGds.immutables.value.annotations
    compileOnly openGds.jetbrains.annotations

    implementation openGds.commons.math3

    // Neo4j dependencies
    compileOnly(neo4j.annotations) { transitive = false }

    implementation project(':algo-common')
    implementation project(':algo-params-common')
    implementation project(':annotations')
    implementation project(':centrality-configs')
    implementation project(':centrality-params')
    implementation project(':community-configs')
    implementation project(':community-params')
    implementation project(':compression-common')
    implementation project(':config-api')
    implementation project(':core')
    implementation project(':core-utils')
    implementation project(':gds-values')
    implementation project(':graph-schema-api')
    implementation project(':memory-usage')
    implementation project(':miscellaneous-params')
    implementation project(':ml-algo')
    implementation project(':ml-core')
    implementation project(':ml-params')
    implementation project(':logging')
    implementation project(':model-catalog-api')
    implementation project(':node-embeddings-configs')
    implementation project(':node-embeddings-params')
    implementation project(':path-finding-params')
    implementation project(':pregel')
    implementation project(':progress-tracking')
    implementation project(':scaling-utils')
    implementation project(':similarity-params')
    implementation project(':string-formatting')
    implementation project(':termination')

    // TEST DEPENDENCIES
    testAnnotationProcessor project(':annotations')

    testImplementation project(':algorithms-machinery')
    testImplementation project(':gdl-graph')
    testImplementation project(':gdl-junit-extension')
    testImplementation project(':ml-test-utils')
    testImplementation project(':test-utils')
    testImplementation openGds.gdl
}
