Here we create a Neo4j database and xref:management-ops/graph-creation/graph-project.adoc[project] it into memory.

[source, cypher, role=noplay]
----
CREATE
  (alice:Person { name: 'Alice', age: 23 }),
  (bob:Person { name: 'Bob', age: 42 }),
  (carl:Person { name: 'Carl', age: 31 }),

  (alice)-[:KNOWS]->(bob),
  (bob)-[:KNOWS]->(alice),
  (alice)-[:KNOWS]->(carl)
----

.Project `Person` nodes and `KNOWS` relationships:
[source, cypher, role=noplay]
----
CALL gds.graph.project(
  'social_network',
  'Person',
  'KNOWS',
  { nodeProperties: 'age' }
)
YIELD
  graphName, nodeCount, relationshipCount
----

.Results
[opts="header"]
|===
| graph            | nodeCont | relationshipCount
| "social_network" | 3        | 3
|===


Next, we create an ephemeral database from the projected graph.

.Create a new database `gdsdb` using our `social_network` graph:
[source, cypher, role=noplay]
----
CALL gds.ephemeral.database.create(
  'gdsdb',
  'social_network'
)
----

We can use the Neo4j `SHOW DATABASES` command to verify that the new database has been created successfully.

[source, cypher, role=noplay]
----
SHOW DATABASES
----

.Results
[opts="header"]
|===
| name     | address          | role         | requestedStatus | currentStatus  | error  | default  | home
| "neo4j"  | "localhost:7687" | "standalone" | "online"        | "online"       | ""     | true     | true
| "system" | "localhost:7687" | "standalone" | "online"        | "online"       | ""     | false    | false
| "gdsdb"  | "localhost:7687" | "standalone" | "online"        | "online"       | ""     | false    | false
|===

Finally, we switch to the newly created database to start using it.

[source, cypher, role=noplay]
----
:use gdsdb
----