[[algorithms-link-prediction-pipelines-predict]]
== Applying a trained model for prediction
:modelType: Link prediction pipeline model
:entity: relationship

In the previous sections we have seen how to build up a Link Prediction training pipeline and train it to produce a predictive model.
After <<algorithms-ml-linkprediction-pipelines-train, training>>, the runnable model is of type `Link prediction pipeline` and resides in the model catalog.

The trained model can then be applied to a graph in the graph catalog to create a new relationship type containing the predicted links.
The relationships also have a property which stores the predicted probability of the link, which can be seen as a relative measure of the model's prediction confidence.

Since the model has been trained on features which are created using the feature pipeline, the same feature pipeline is stored within the model and executed at prediction time.
As during training, intermediate node properties created by the node property steps in the feature pipeline are transient and not visible after execution.

When using the model for prediction, the relationships of the input graph are used in two ways.
First, the input graph is fed into the feature pipeline and therefore influences predictions if there is at least one step in the pipeline which uses the input relationships (typically any node property step does).
Second, predictions are carried out on each node pair that is not connected in the input graph.

The predicted links are sorted by score before the ones having score below the configured `threshold` are discarded.
Finally, the configured `topN` predictions are stored back to the in-memory graph.

It is necessary that the predict graph contains the properties that the pipeline requires and that the used array properties have the same dimensions as in the train graph.
If the predict and train graphs are distinct, it is also beneficial that they have similar origins and semantics, so that the model is able to generalize well.

=== Syntax

.Link Prediction syntax per mode
[.tabbed-example, caption = ]
====
[.include-with-mutate]
======
.Run Link Prediction in mutate mode on a named graph:
[source, cypher, role=noplay]
----
CALL gds.alpha.ml.pipeline.linkPrediction.predict.mutate(
  graphName: String,
  configuration: Map
)
YIELD
  createMillis: Integer,
  computeMillis: Integer,
  postProcessingMillis: Integer,
  mutateMillis: Integer,
  relationshipsWritten: Integer,
  linksConsidered: Integer,
  configuration: Map
----

include::../../common-configuration/common-parameters-named-graph.adoc[]

// not reusing common-configuration/common-mutate-configuration-named-graph.adoc as mutateProperty has a default
.Configuration
[opts="header",cols="1,1,2m,1,5"]
|===
| Name                                                          | Type              | Default           | Optional | Description
| modelName                                                     | String            | n/a               | no       | The name of a Link Prediction model in the model catalog.
| <<common-configuration-node-labels,nodeLabels>>               | List of String    | ['*']             | yes      | Filter the named graph using the given node labels.
| <<common-configuration-relationship-types,relationshipTypes>> | List of String    | ['*']             | yes      | Filter the named graph using the given relationship types.
| <<common-configuration-concurrency,concurrency>>              | Integer           | 4                 | yes      | The number of concurrent threads used for running the algorithm.
| mutateRelationshipType                                        | String            | n/a               | no       | The relationship type used for the new relationships written to the in-memory graph.
| mutateProperty                                                | String            | 'probability'     | yes      | The relationship property in the GDS graph to which the result is written.
|===

include::specific-predict-configuration.adoc[]

.Results
[opts="header",cols="1,1,6"]
|===
| Name                 | Type    | Description
| createMillis         | Integer | Milliseconds for creating the graph.
| computeMillis        | Integer | Milliseconds for running the algorithm.
| postProcessingMillis | Integer | Milliseconds for computing the global metrics.
| mutateMillis         | Integer | Milliseconds for adding properties to the in-memory graph.
| relationshipsWritten | Integer | Number of relationships created.
| linksConsidered      | Integer | Number of links considered.
| configuration        | Map     | Configuration used for running the algorithm.
|===
======

[.include-with-stream]
======
.Run Link Prediction in stream mode on a named graph:
[source, cypher, role=noplay]
----
CALL gds.alpha.ml.pipeline.linkPrediction.predict.stream(
  graphName: String,
  configuration: Map
)
YIELD
  node1: Integer,
  node2: Integer,
  probability: Float
----

include::../../common-configuration/common-parameters-named-graph.adoc[]

include::../../common-configuration/common-stream-stats-configuration-named-graph.adoc[]

include::specific-predict-configuration.adoc[]

.Results
[opts="header",cols="1,1,6"]
|===
| Name        | Type    | Description
| node1       | Integer | Node ID of the first node.
| node2       | Integer | Node ID of the second node.
| probability | Float   | Predicted probability of a link between the nodes.
|===
======
====

[[algorithms-link-prediction-pipelines-predict-examples]]
=== Example

In this example we will show how to use a trained model to predict new relationships in your in-memory graph.
In order to do this, we must first have an already trained model registered in the Model Catalog.
We will use the model which we trained in the <<algorithms-ml-linkprediction-pipeline-examples-train-query, train example>> which we gave the name `lp-pipeline-model`.
The algorithm excludes predictions for existing relationships in the graph.

[[algorithms-link-prediction-pipelines-predict-examples-stream]]
==== Stream

[role=query-example, group=lp]
--
[source, cypher]
----
CALL gds.alpha.ml.pipeline.linkPrediction.predict.stream('myGraph', {
  modelName: 'lp-pipeline-model',
  topN: 5,
  threshold: 0.45
})
 YIELD node1, node2, probability
 RETURN gds.util.asNode(node1).name AS person1, gds.util.asNode(node2).name AS person2, probability
 ORDER BY probability DESC, person1
----

We specified `threshold` to filter out predictions with probability less than 45%, and `topN` to further limit output to the top 5 relationships.

.Results
[opts="header"]
|===
| person1   | person2   | probability
| "Alice"   | "Chris"   | 0.5422350772807373
| "Chris"   | "Mark"    | 0.5364414066546659
| "Alice"   | "Mark"    | 0.5130009448848327
| "Alice"   | "Karin"   | 0.5123040606165334
| "Alice"   | "Greg"    | 0.51204718863418
|===

We can see, that our model predicts the most likely link is between Alice and Chris.
--


[[algorithms-link-prediction-pipelines-predict-examples-mutate]]
==== Mutate

In this example we will show how to write the predictions to your in-memory graph.
We will use the model `lp-pipeline-model`, that we trained in the <<algorithms-ml-linkprediction-pipelines-train, train example>>.


[role=query-example, group=lp]
--
[source, cypher]
----
CALL gds.alpha.ml.pipeline.linkPrediction.predict.mutate('myGraph', {
  modelName: 'lp-pipeline-model',
  mutateRelationshipType: 'KNOWS_PREDICTED',
  topN: 5,
  threshold: 0.45
}) YIELD relationshipsWritten
----

.Results
[opts="header"]
|===
| relationshipsWritten
| 10
|===
--
