plugins {
    id 'buildlogic-gds-java-plain'
}

description = 'Neo4j Graph Data Science :: Node Embedding Algorithms Parameters'

group = 'org.neo4j.gds'

dependencies {
    compileOnly openGds.jetbrains.annotations

    api project(':algo-params-common')
    implementation project(':annotations')
    api project(':concurrency')
    implementation project(':string-formatting')
}
