[[graph-generation]]
= Graph Generation

[abstract]
--
This section describes how random graphs can be generated in the Neo4j Graph Data Science library.
--

In certain use cases it is useful to generate random graphs, for example, for testing or benchmarking purposes.
For that reason the Neo4j Graph Algorithm library comes with a set of built-in graph generators.
The generator stores the resulting graph in the <<graph-catalog-ops, graph catalog>>.
That graph can be used as input for any algorithm in the library.

include::beta-note.adoc[tag=beta-note]

[NOTE]
====
It is currently not possible to persist these graphs in Neo4j.
Running an algorithm in write mode on a generated graph will lead to unexpected results.
====

The graph generation is parameterized by three dimensions:

 * node count - the number of nodes in the generated graph
 * average degree - describes the average out-degree of the generated nodes
 * relationship distribution function - the probability distribution method used to connect generated nodes


[[graph-generation-syntax]]
== Syntax

.The following describes the API for running the algorithm
[source, cypher]
----
CALL gds.beta.graph.generate(graphName: String, nodeCount: Integer, averageDegree: Integer, {
  relationshipDistribution: String,
  relationshipProperty: Map
})
YIELD name, nodes, relationships, generateMillis, relationshipSeed, averageDegree, relationshipDistribution, relationshipProperty
----

.Parameters
[opts="header",cols="1m,1,1m,1,4"]
|===
| Name                | Type    | Default | Optional | Description
| graphName           | String  | null    | no       | The name under which the generated graph is stored.
| nodeCount           | Integer | null    | no       | The number of generated nodes.
| averageDistribution | Integer | null    | no       | The average out-degree of generated nodes.
| configuration       | Map     | {}      | yes      | Additional configuration, see below.
|===

.Configuration
[opts="header",cols="1m,1,1m,1,4"]
|===
| Name                      | Type      | Default  | Optional | Description
| relationshipDistribution  | String    | UNIFORM  | yes      | The probability distribution method used to connect generated nodes. For more information see <<graph-generation-distribution>>.
| relationshipSeed          | Integer   | null     | yes      | The seed used for generating relationships.
| relationshipProperty      | Map       | {}       | yes      | Describes the method used to generate a relationship property. By default no relationship property is generated. For more information see <<graph-generation-relationship-property>>.
| aggregation               | String    | NONE     | yes      | The relationship aggregation method cf. <<native-projection-syntax-relationship-projections, Native Projection.>>.
| orientation               | String    | NATURAL  | yes      | The method of orienting edges. Allowed values are NATURAL, REVERSE and UNDIRECTED.
| allowSelfLoops            | Boolean   | false    | yes      | Whether to allow relationships with identical source and target node.
|===

.Results
[opts="header",cols="1m,1,6"]
|===
| Name                      | Type       | Description
| name                      | String     | The name under which the stored graph was stored.
| nodes                     | Integer    | The number of nodes in the graph.
| relationships             | Integer    | The number of relationships in the graph.
| generateMillis            | Integer    | Milliseconds for generating the graph.
| relationshipSeed          | Integer    | The seed used for generating relationships.
| averageDegree             | Float      | The average out degree of the generated nodes.
| relationshipDistribution  | String     | The probability distribution method used to connect generated nodes.
| relationshipProperty      | String     | The configuration of the generated relationship property.
|===

[[graph-generation-distribution]]
== Relationship Distribution

The `relationshipDistribution` parameter controls the statistical method used for the generation of new relationships.
Currently there are three supported methods:

* `UNIFORM` - Distributes the outgoing relationships evenly, i.e., every node has exactly the same out degree (equal to the average degree). The target nodes are selected randomly.
* `RANDOM` - Distributes the outgoing relationships using a normal distribution with an average of `averageDegree` and a standard deviation of `2 * averageDegree`. The target nodes are selected randomly.
* `POWER_LAW` - Distributes the incoming relationships using a power law distribution. The out degree is based on a normal distribution.


[[graph-generation-seed]]
== Relationship Seed

The `relationshipSeed` parameter allows, to generate graphs with the same relationships, if they have no property.
Currently the `relationshipProperty` is not seeded, therefore the generated graphs can differ in their property values.
Hence generated graphs based on the same `relationshipSeed` are not identical.

[[graph-generation-relationship-property]]
== Relationship Property

The graph generator is capable of generating a relationship property.
This can be controlled using the `relationshipProperty` parameter which accepts the following parameters:

.Configuration
[opts="header",cols="1m,1,1,1,4"]
|===
| Name    | Type      | Default | Optional  | Description
| name    | String    | null    | no        | The name under which the property values are stored.
| type    | String    | null    | no        | The method used to generate property values.
| min     | Float     | 0.0     | yes       | Minimal value of the generated property (only supported by `RANDOM`).
| max     | Float     | 1.0     | yes       | Maximum value of the generated property (only supported by `RANDOM`).
| value   | Float     | null    | yes       | Fixed value assigned to every relationship (only supported by `FIXED`).
|===

Currently, there are two supported methods to generate relationship properties:

* `FIXED` - Assigns a fixed value to every relationship. The `value` parameter must be set.
* `RANDOM` - Assigns a random value between the lower (`min`) and upper (`max`) bound.
